### ISSUE TITLE
1000!

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1000]
![image](https://user-images.githubusercontent.com/156149/27874883-88695b3e-61b1-11e7-8e97-a91ce6906868.png)

(source: https://www.floweraura.com/send-cakes/black-forest-cake)

**Comment by fredck** [comment]
Happy 1000!!!

**Comment by scofalik** [comment]
I can't believe I created 999th issue and haven't noticed. 😢

**Comment by Reinmar** [comment]
I've been waiting for 1000th for a long time :P

**Comment by Reinmar** [comment]
Let's go on a diet this year. Closing! :D
