### ISSUE TITLE
Support for `keyup` event on document

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-engine#1026]
In order to detect whether the user keeps the <kbd>Backspace</kbd> key, we need to add support for the `keyup` event called on `Document`.

It's required in order to implement a test case **II** from here – https://github.com/ckeditor/ckeditor5-typing/issues/61#issuecomment-314705304.

**Comment by Reinmar** [comment]
We agreed on a different solution – that the `keydown` could have a "sequence" property with the number identifying thre 1st, 2nd, etc. press (without release).

**Comment by Reinmar** [comment]
OTOH, exposing keyup may be more flexible. But you'll need much more code in ckeditor/ckeditor5-typing#61  to handle that.

OTTH... we'd actually need to count which exactly key does this sequence apply to. So perhaps that generic sequence in `keydown` isn't a good idea. E.g. `ctrl+backspace` is already two keydowns but you'd expect that sequence is `1` ;/

Let's better add the keyup then and have the code inside the typing feature.

**Comment by Reinmar** [comment]
There's also the third option – to have keyup fired by the `KeyObserver` and the sequence handled by the `DeleteObserver`.
