### ISSUE TITLE
Node#getCommonAncestor() – add includeSelf option

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1036]
Well, it turns out that the method we introduced in #1033 does not really solve the case that I have in the hands. And we realised that it's quite common that if you have a structure like:

```html
<a><b></b></a>
```

And elements "a" and "b" as some targets, then you may be interested that the entire target is still "a". So, it's more like "get common container".

PS. Turns out that `getAncestors()` already have `includeNode`. So, if in this case we can have non ancestors returned, then we can definitely do the same in `getCommonAncestor()`. But, I'd also like to rename `includeNode` to `includeSelf`.

**Comment by pjasiun** [comment]
Shouldn't `Node#getCommonAncestor()` always include self? What is an use-case to use it without it?

**Comment by Reinmar** [comment]
To check what contains those two nodes. Besides "ancestor" means a parent+ of the node, so it would be super strange if it returned the node itself.

Besides, by introducing this option we'll have parity with `getAncestors()`.

**Comment by pjasiun** [comment]
I mean, as long as it's not `<a><b></b></a>` it does not change anything if you include self or not. And if it's `<a><b></b></a>` `getCommonAncestor` without self will return the parent of `a` what does not seams to be an expected behavior for anybody.

**Comment by Reinmar** [comment]
I checked CKEditor 4 in the meantime and it works like you proposed.

But it doesn't feel right to have `getAncestors()` doing something else than `getCommonAncestor()`. "Common ancestor" is a well known term so I wouldn't feel safe to have it work in this way. Besides parity with `getAncestors()`, the option gives you the flexibility **and awareness**. The latter makes it worth to implement it even if we're never going to use it. Just so people know.

BTW. The option is 0 lines of additional code.
