### ISSUE TITLE
Postfixing should be simpler

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1101]
It's pretty common case that some plugin listens on the change event and what to apply some changes.

It's pretty simple to make it works, but you need a lot of know-how to make it works well. You need to remember about couple thing.
 - You need to `enqueueChanges`, otherwise there might be no render call.
 - Check if the batch is not transparent, otherwise, some not obvious problems in collaboration will appear.
 - Remember that before `enqueueChanges` block some other changes may happen and that we need to check it again inside the block if the condition is still valid.
 - Take care not to apply a fix for every `enqueueChanges` if it's needed only once.

We need a helper which will do all of this for us, so all fixers will work well. It could get 2 functions as parameters: condition and action, and take care about everything.

**Comment by pjasiun** [comment]
Related: https://github.com/ckeditor/ckeditor5-engine/issues/654.

**Comment by scofalik** [comment]
> Remember that before enqueueChanges block some other changes may happen and that we need to check it again inside the block if the condition is still valid.

Recently we had that dilemma with @Reinmar. We agreed that having "empty" `doc.enqueueChanges` call is fine, so it's fine to check only inside `doc.enqueueChanges`. However, I could imagine that might be some cases where we, for some reason, need to check before calling `enqueueChanges`, and inside the call.

> Take care not to apply a fix for every enqueueChanges if it's needed only once.

I am not sure how you want to prevent this :S. I mean, isn't this the same as just checking whether a change still should be applied (so the same as point above)?

**Comment by pjasiun** [comment]
> Remember that before enqueueChanges block some other changes may happen and that we need to check it again inside the block if the condition is still valid.
> Recently we had that dilemma with @Reinmar. We agreed that having "empty" doc.enqueueChanges call is fine, so it's fine to check only inside doc.enqueueChanges. However, I could imagine that might be some cases where we, for some reason, need to check before calling enqueueChanges, and inside the call.
> 
> Take care not to apply a fix for every enqueueChanges if it's needed only once.
> I am not sure how you want to prevent this :S. I mean, isn't this the same as just checking whether a change still should be applied (so the same as point above)?

It would be very bad for the efficiency. You will add callback function for event change, even if it's not needed.

**Comment by pjasiun** [comment]
Instead, we should:
 - check the condition,
 - if passed, add `enqueueChanges` block,
 - save the information that the block is added and do not add it again for the following changes,
 - when enter to the `enqueueChanges` block check the condition again,
 - execute action.

**Comment by pjasiun** [comment]
It's partially done, together with introducing differ, and will be fixed by https://github.com/ckeditor/ckeditor5-engine/issues/1207.
