### ISSUE TITLE
Spaces inside <code> should be rendered in a normal way

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1126]
We assumed that subsequent spaces must be rendered in "as is" way in `<code>` elements, without encoding them to pairs of "space + nbsp". However, this isn't correct, as we learned in https://github.com/ckeditor/ckeditor5-basic-styles/pull/55#issuecomment-327470839.

**Comment by scofalik** [comment]
Maybe it will let us skip looking backward in space-replace algorithm.

**Comment by Reinmar** [comment]
It has nothing to do with that. We just need to remove `code` from the `preElements` array which introduces special behaviour for them.

**Comment by fredck** [comment]
Exactly... apart from styling, I don't see much difference between `code` and `strong`, for example.

**Comment by scofalik** [comment]
Well, we look back because we assumed that there are elements in which we don't want to convert spaces to `&nbsp;`s. `<code>` was supposed to be such an element. If this is not a case, then why should we look back?

**Comment by Reinmar** [comment]
> If this is not a case, then why should we look back?

You might be right that we don't need to look back if we'd assume that previous text node's last space is always converted to nbsp, but this is unrelated from the `<code>` stuff. We assumed that spaces inside `<code>` are preformatted anyway, so that they behave like nbsps.

**Comment by scofalik** [comment]
Okay I won't argue because I don't remember that algorithm and all the cases precisely.
