### ISSUE TITLE
Children nodes are inserted to new parent without first removing them from their old parent

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#1139]
I spotted a bug that crashed editor during rendering. It appeared that `Renderer` wants to re-render a part of a tree that is detached from main tree. What was weird about that tree was that detached-root had a child but that child's `parent` property was set to `null`. Similarly, that child also had a child which also had `parent` set to `null`.

After debugging it appeared that in `view.Writer` some nodes were supposed to be moved from one node to another, however those nodes were not removed from their original parent before appending to new parent, which caused this bug.

**Comment by scofalik** [comment]
While I am at it, I'll check the whole code for `appendChildren` and `insertChildren` usage and will fix it where needed.

**Comment by Reinmar** [comment]
Is it https://github.com/ckeditor/ckeditor5-engine/issues/1038?

**Comment by scofalik** [comment]
Yes, it is.

Alternatively, we can solve it by adding more logic in `appendChildren`/`insertChildren`.

**Comment by Reinmar** [comment]
I'm for more logic inside `appendChildren()` (or whichever is the lowest level method).

**Comment by Reinmar** [comment]
PJ is too:

> I agree that appendChild should remove them from the previous parent. In the model, #858 will (should) solver it. However, we should solve it in the view too.
