### ISSUE TITLE
[FF] Browser steals selection on CLTR+K

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#1154]
### Steps to reproduce

1. Open a sample, for example: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/balloon-editor.html
2. Select some text.
3. Press <kbd>Ctrl</kbd> + <kbd>K</kbd> to open link balloon.

### Expected result

Field in balloon is focused.

### Current result

Browser steals selection and focuses in search bar.

### Notes

I think this is because we cannot cancel default event.

**Comment by Reinmar** [comment]
Strange that it doesn't work. I don't recall problems with handling this keystroke. 

But, why did you report this in ckeditor5-engine?

**Comment by scofalik** [comment]
Sorry, wrong repo, I'll move it.

**Comment by scofalik** [comment]
https://github.com/ckeditor/ckeditor5-link/issues/153
