### ISSUE TITLE
[Safari] Selection moves to the beginning of the editor after focusing the editor for the first time

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-engine#1155]
## Steps to reproduce
1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds/classic-editor.html.
2. Focus the editor.

## Current result
The caret has appeared at the beginning of the editor.

## Other information
OS: MacOS X
Browser: Safari 11
Release: 0.11.0

**Comment by scofalik** [comment]
I can reproduce it once every 4-5 tries, so I cannot be 100% sure, but this issue seems to be related to https://github.com/ckeditor/ckeditor5-engine/issues/1153 and the fix for that issue makes it that I can't reproduce it even once.

**Comment by Mgsy** [comment]
> I can reproduce it once every 4-5 tries, so I cannot be 100% sure, but this issue seems to be related to #1153 and the fix for that issue makes it that I can't reproduce it even once.

I can confirm that your fix solves this issue.
