### ISSUE TITLE
Remove the renderer-skipped-selection-rendering warning

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1158]
We added it to monitor how often it's logged. Now we know, so we can remove it because the console looks bad when full of those.

**Comment by pjasiun** [comment]
At the very beginning, we had an idea of different log levels. Maybe we should introduce it now? In fact, we already met the problem with the need to log some additional information for debugging. We introduced it as a separate plugin then. Maybe we should move this option to this plugin too, or improve the whole mechanism introducing some log levels.

**Comment by Reinmar** [comment]
I have mixed feelings.

On the one hand, perhaps oooone day such a warning would let you figure out some bug. Imagine – you're trying to figure out why selection isn't refreshed. You have debugging mode on (it'd need to be on by default in our tests) and you quickly realise what's that.

On the other hand, polluting our code with warnings like that which we'll use once every 3 years is not a good idea. We need to be careful when doing so because we will affect the code size.

So, if we'll find the right ballance, then ok. But this means quite a lot of work – turning on debug mode in our all manual and automated tests, adding support for 2 levels of verbosity, perhaps adding support for minifying these warnings.

Therefore, here I'd remove this warning. And I'd get back to this once we have at least one more case where we'd like to use it (unless the case you mention is really this one cause it doesn't sound).
