### ISSUE TITLE
[Chrome/Safari] The selection moves to the beginning of the editor after collapsing it in read only mode

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-engine#1168]
## Steps to reproduce
1. Create the `Header 1` and the paragraph.
2. Enter `read only` mode.
3. Select part of the paragraph.
4. Click on the selection to collapse it.

## Current result
The selection moves to the beginning of the editor (you can see that dropdown points to the `Header 1`).

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31712957-f010efc0-b3fc-11e7-8273-6e7c436f995c.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Opera
Release: 1.0.0-Alpha1

**Comment by Reinmar** [comment]
IMO, this is "fine" or at least – not harmful :) Unless we see how this could cause any problems to anyone.
