### ISSUE TITLE
Prevent adding inline filler to elements with contenteditable=false

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-engine#1170]
There are situations when browsers put selection inside `contenteditable=false` elements (https://github.com/ckeditor/ckeditor5-image/issues/19) and we render inline filler there. Block fillers are blocked by `getFillerOffset()` but inline fillers are not blocked in any way there.

The solution might be to block rendering it if the nearest ancestor with `contenteditable` attribute has it set to `false`.

**Comment by pjasiun** [comment]
This is strange because inline filler should be rendered only where the selection is. First of all, the collapsed selection should not be placed in not editable elements. Maybe we should fix the selection position to move it out of the not editable elements first?

**Comment by szymonkups** [comment]
That was the first approach but here https://github.com/ckeditor/ckeditor5-image/issues/19#issuecomment-279407966 I described why this fails.
