### ISSUE TITLE
onpaste event

### ISSUE THREAD

**Issue by wenmingtang** [ckeditor/ckeditor5-engine#1185]
Does anyone know how I can attach an onpaste event in CKEditor5?

I basically want to grab CTRL + V data and add few text to it and then add it to the editor.

Thanks.

**Comment by Reinmar** [comment]
Hey! Great question – pity that you haven't asked it on StackOverflow :)

Anyway, quick answer – see the https://github.com/ckeditor/ckeditor5-clipboard's code. This plugin (which is available by default in all builds) expose additional events using which you can processed the content which was pasted before that content is inserted into the model.

You can read about so-called "input/output pipelines" in https://docs.ckeditor.com/ckeditor5/latest/api/module_clipboard_clipboard-Clipboard.html.

**Comment by wenmingtang** [comment]
Thanks, @Reinmar 

 I want an `afterPaste` event, It looks like `ckeditor5-clipboard` can't be implemented.

**Comment by Reinmar** [comment]
Why do you need the `afterPaste` event? Could you explain your use cases for it?

CKEditor 5 has a bit different architecture so some things need to be achieved differently with it. However, in general, this architecture is far more powerful so it's just a matter of understanding what you want to achieve and I'm sure that we'll find a way to do that.

**Comment by wenmingtang** [comment]
@Reinmar 
I want to `afterPaste` event when to do something.

such as localize remote images, then change the `img` Dom node of editing area.

**Comment by Reinmar** [comment]
So, generally you have two options:

* Listen on the [`editor.data#insertContent`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_controller_datacontroller-DataController.html#event:insertContent) event and process the content before it gets inserted into the editor. This event is fired when `editor.data.insertContent()` is used (and it's, of course, used by the clipboard plugin). Processing the content which gets through this event will ensure that you support also other features which may use it, not only pasting.
* Listen on the [`editor.document#change`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_document-Document.html#event:change) event and make changes to the model after the content was inserted there. This event is fired with granular information about changes applied to the model (through operations).  E.g. the image upload plugin uses this method to [upload images which were inserted into the content](https://github.com/ckeditor/ckeditor5-upload/blob/626ff075da05745ef1300cb2190b621253039e24/src/imageuploadengine.js#L78-L105).

> change the img Dom node of editing are

Please note that you can't change nodes in the DOM directly. You need to change their properties in the model. Othwerise, the editor will revert your changes.

**Comment by wenmingtang** [comment]
@Reinmar in `1.0.0-beta.1` version, The above method doesn't working. Can you help me? Thank you.

**Comment by Reinmar** [comment]
Do you mean `insertContent()`? It was moved to [`editor.model.insertContent()`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_model-Model.html#function-insertContent).

**Comment by wenmingtang** [comment]
In the `1.0.0-alpha.2` version, My code is as follows:

```
ClassicEditor
    .create(document.querySelector('#article_body'), {
        // configure
    })
    .then(editor => {

        // 暂时不起作用
        editor.document.on('change', (evt, type, data) => {
            addLoaderListener();

            console.log(evt, type, data)

            if (type === 'insert' || type === 'reinsert') {
                for (const value of data.range) {
                    if (value.type === 'elementStart' && value.item.name === 'image') {
                        const imageElement = value.item;
                        const uploadId = imageElement.getAttribute('uploadId');
                        const uploadStatus = imageElement.getAttribute('uploadStatus');

                        if (!uploadId && !uploadStatus) {
                            tryUploadRemoteImage(editor, imageElement); // Automatically upload paste’s images to the server.
                        }
                    }
                }
            }
        });
    })
    .catch(error => {
        console.log(error)
    });
```

But  in the1.0.0-beta.1 version,

the method ` editor.document.on('change', (evt, type, data)` is not working.

Are there any other similar methods?

**Comment by wenmingtang** [comment]
@scofalik Thanks.
So, I want to achieve the above purpose(Automatically upload paste’s images to the server.), what other methods?

**Comment by wenmingtang** [comment]
Resolved, reference: 
https://github.com/ckeditor/ckeditor5-image/blob/master/src/imageupload/imageuploadediting.js#L78
