### ISSUE TITLE
How to disable debug tools?

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-engine#1193]
When tests are executed as a single entry point, two tests fail:

https://github.com/ckeditor/ckeditor5-engine/blob/82335aee6426a7418416927fbe0db5d471c71465/tests/model/document/document.js#L113-L141

and

https://github.com/ckeditor/ckeditor5-engine/blob/82335aee6426a7418416927fbe0db5d471c71465/tests/model/document/document.js#L143-L153

![image](https://user-images.githubusercontent.com/2270764/33311417-0e1636cc-d425-11e7-99ad-50c9b8e08c33.png)

In order to fix these tests, I can add a method `toJSON` into `operation` object (`toJSON: sinon.spy())`. But I'm not sure whether this solution is proper. I would like to disable engine debug tools but I guess it's tricky.

This ticket is a last blocker for https://github.com/ckeditor/ckeditor5-dev/issues/290.

**Comment by Reinmar** [comment]
Do you mean that running all tests together means unintentionally enabling debug tools? That should be fixed in general, not just for broken tests.

**Comment by szymonkups** [comment]
> Do you mean that running all tests together means unintentionally enabling debug tools? That should be fixed in general, not just for broken tests.

When debug tools' tests are executed they're enabled for testing purposes but there is no functionality to disable them. We should create `disableEngineDebug()` function to revert changes made by enabling them.

**Comment by jodator** [comment]
I think that those tests are broken as they use `Object` instead of `Operation` instance for checking if something is done on operation.
Also this should be changed:
https://github.com/ckeditor/ckeditor5-engine/blob/ddb1c9f5a2017d2af3a57e39192f3b896452e186/src/dev-utils/enableenginedebug.js#L550
to `JSON.stringify( operation )`.

**Comment by szymonkups** [comment]
> I think that those tests are broken as they use Object instead of Operation instance for checking if something is done on operation.

Yes, but the main problem is that engine debug tools are enabled and they shouldn't be. Please look at my comment here: https://github.com/ckeditor/ckeditor5-dev/issues/290#issuecomment-346858435.

**Comment by pomek** [comment]
I decided to create a function which allows disabling engine debug functions.
