### ISSUE TITLE
Fix selection position in a post-fixer

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1229]
Since now it should be possible to write also postfixes for selection, we should try to replace `Schema.getNearestSelectionRange` ([moved from document](https://github.com/ckeditor/ckeditor5-engine/issues/1227)) with a postfixer which will automatically move the selection to the proper place.

**Comment by pjasiun** [comment]
See also: https://github.com/ckeditor/ckeditor5-engine/issues/1228.

**Comment by Reinmar** [comment]
I changed the title of this ticket because it's not about replacing the existing method with something, but about creating a post-fixer. What happens with this method is a side topic.

**Comment by Reinmar** [comment]
Use case to consider: https://stackoverflow.com/questions/49358150/is-there-any-way-to-select-all-the-content-of-ckeditor-5-by-code/49358509#49358509

**Comment by Reinmar** [comment]
I think it's done. @jodator's selection postfixer was needed for tables but it covered far more cases and fixed many issues.
