### ISSUE TITLE
[Docs] Schema isBlock vs extends $block

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1248]
Reading schema docs it was unclear for me: is it possible (in a real case) to create an element which `isBlock` but which do not extend `$block`?

The problem with schema is, that it is kind of a social contract. There are a lot of things you can do: no one stop you if you try to define anything in any way. But it will work only if everybody will understand it the same way. One feature, which understands `$block` differently, may break the whole schema.

This is why I would be very direct when it comes to schema docs. For instance, if we don't know any case in which `isBlock` should be set any other way than extending `$block`, write this. If we do know such case, we should write it too.

**Comment by Reinmar** [comment]
PS. Generally I agree that we could do something about it and I saw it as a flaw from the beginning, but I haven't seen a viable solution.

**Comment by Reinmar** [comment]
I didn't see confusion from others regarding this, so perhaps I was right saying that our own doubts and confusion came from the past.
