### ISSUE TITLE
Modify SchemaContext

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1250]
At this moment, the schema is not mutable and there is no easy way to create one schema based on another. The simplest way right now is to create a new definition and the new schema based on it. Even the current docs do not look very simple:

https://github.com/ckeditor/ckeditor5-engine/blob/d00c24c0fefad47f6a48abe8bd43c71ee8fddf58/src/model/schema.js#L1018

You also, need to remember about all these fixes done in the `SchemaContext` creator if you want to get items from the position manually:

https://github.com/ckeditor/ckeditor5-engine/blob/d00c24c0fefad47f6a48abe8bd43c71ee8fddf58/src/model/schema.js#L877-L890

This is why I think that schema `SchemaContext` should have methods like `add`/`delete` or `push`/`pop` to create one context based one another. These methods could modify the context object, but if we want to keep a context immutable (as @Reinmar suggested) these methods could return the new context object (do not change the current one).

Also, `checkChild` and `checkAttribute` should accept `SchemaContext` instance. To do so, we could make `SchemaContext` constructor accepts `SchemaContext` instance as a parameter. In such case, the same (or even the same instance) should be returned from the constructor.

**Comment by Reinmar** [comment]
Off topic:

```js
	constructor( context ) {
		if ( Array.isArray( context ) ) {
			if ( context[ 0 ] && typeof context[ 0 ] != 'string' && context[ 0 ].is( 'documentFragment' ) ) {
				context.shift();
			}
		}
		else {
			// `context` is item or position.
			// Position#getAncestors() doesn't accept any parameters but it works just fine here.
			context = context.getAncestors( { includeSelf: true } );

			if ( context[ 0 ].is( 'documentFragment' ) ) {
				context.shift();
			}
		}

		this._items = context.map( mapContextItem );
	}
```

Why is the `documentFragment` check implemented twice? It can be done once, after the `if-else` part, once `context` is an array.

**Comment by Reinmar** [comment]
> Also, checkChild and checkAttribute should accept SchemaContext instance. To do so, we could make SchemaContext constructor accepts SchemaContext instance as a parameter. In such case, the same (or even the same instance) should be returned from the constructor.

I'd go with the same instance. Since it's immutable anyway, that doesn't matter.

**Comment by pjasiun** [comment]
We decided to call it `concat`and it will accept any form of the schema definition, which can be string now too (it is useful also in other cases). Such string will be treated as a name of a single element.

**Comment by Reinmar** [comment]
I'm afraid that I don't like the new method and other changes. I don't understand why we needed it.

Plus, I'd ask for clarification about this:

> Also, checkChild and checkAttribute should accept SchemaContext instance. To do so, we could make SchemaContext constructor accepts SchemaContext instance as a parameter. In such case, the same (or even the same instance) should be returned from the constructor.

Because once it landed it just looks very... unnecessary.

Let's talk further under #1263.

**Comment by Reinmar** [comment]
Another thing to fix – instead of writing everywhere in the API docs that a param is of this type:

```
{module:engine/model/schema~SchemaContextDefinition|module:engine/model/schema~SchemaContext}
```

Add `module:engine/model/schema~SchemaContext` to be a proper definition of `module:engine/model/schema~SchemaContextDefinition`. Inception ;)
