### ISSUE TITLE
Introduce `Schema#checkMerge()`

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-engine#1251]
`Schema#checkMerge()` will check whether two elements can be merged.

See more: https://github.com/ckeditor/ckeditor5-engine/issues/1240.

**Comment by Reinmar** [comment]
This method will have two set of params:

```js
checkMerge( position )
checkMerge( baseElement, elementToMerge )
```

The first option will be aligned to `Writer#merge()`. The other option will allow checking any two elements (if e.g. one of them wasn't inserted into the tree yet).
