### ISSUE TITLE
New mechanism for creating custom UIElements

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-engine#1254]
We want to avoid extending basic view classes. `UIElements` use inheritance to provide custom `render()` method in child classes. 
This can be done without inheritance:

```js
class UIElement extends Element {
    render() {
       return this.createDomElement();
   }

   createDomElement() {
       // Create and return base dom element.
   }
}

// Actual UIElement usage.
const uiElement = new UIElement();
uiElement.render = function() {
    const element = this.createDomElement();
    // Further custom modifications to the element.
   
    return element;
}
```

**Comment by Reinmar** [comment]
An alternative method name came to my mind – `toDomElement()`. WDYT? Or is it worse because it sounds like it's always returning the same DOM element?

**Comment by szymonkups** [comment]
`viewUIElement.toDomElement()` sounds OK to me. We can give a note in docs that this method always creates a new DOM node.

**Comment by pjasiun** [comment]
Let's keep `createDomElement()`. This is what you do in the `render` method: create DOM.
