### ISSUE TITLE
SchemaContext should accept a string

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1262]
Now `SchemaContext` accepts array of strings as context (names of elements). It should be possible to use a single string as a single element name.

Thanks to such change we will be able to rollback such changes: https://github.com/ckeditor/ckeditor5-clipboard/commit/5a8971f6d7d15295127362b8668190a6a4db37a9

Moreover, `SchemaContext.concat` accepts a string, so it is strange that `SchemaContext.constructor` do not accept it.

Also, all methods which accept array usually accept also array item and convert it to the one item array.

**Comment by Reinmar** [comment]
Passing strings to `SchemaContext` was meant to be a temporary thing and should be removed or at least not recommended as it doesn't provide some information (element attributes) which are normally available. Therefore, I don't think that we need to extend anything. Quite the contrary – we should stop using the string format ;)

So, my question – where do we have to use the string format?

**Comment by Reinmar** [comment]
I reported https://github.com/ckeditor/ckeditor5-engine/issues/1263 because I found all the additions a bit unclear.

**Comment by pjasiun** [comment]
One example is in my post:

> Thanks to such change we will be able to rollback such changes: ckeditor/ckeditor5-clipboard@5a8971f

Another is: https://github.com/ckeditor/ckeditor5-engine/blob/15d5d65716a382f3d0efb7c328936f083faddf5f/src/controller/datacontroller.js#L216 (usage of o the same method).

Another might be autoparagraphing, where all we know is that we want to extend the schema context with `paragraph` element (however it is a case of `push`/`concat`).

I agree that whenever we have an element we should use it since it has not only the name but also attributes. However, it happens that all we have is element name and creating an element in such case is simply annoying (especially because you need to use `writer` to do so).

**Comment by Reinmar** [comment]
OK, let's keep it then. We'll simply need to make it clear in the docs that "if you have an element, then use it".
