### ISSUE TITLE
Schema.concat()'s behaviour is confusing

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1263]
What does the below code do?

```js
const ctx = new SchemaContext( foo );

const ctx2a = ctx.concat( foo.getFirstChild() );
const ctx2b = ctx.concat( new SchemaContext( foo.getFirstChild ) );
```

You may expect to have the below twice:

```
[someRoot, fooParent, foo, fooChild]
```

But you won't. The latter version will contain this:

```
[someRoot, fooParent, foo, someRoot, fooParent, foo, fooChild]
```

The reason why the first version works is that `concat()` casts the param to an array. This is very significant, but hard to spot detail, which, got me by surprise. Especially that the code misses API docs. A code sample is a must in such cases. It says more than 1000 words.

However, I'll go even further – where will be the opposite of `concat()`? What if you'll want to get just a piece of the current context? Are we going to introduce `slice()`? ;)

Finally, I don't get why we had to allow passing `SchemaContext` to `concat()`.  Why can you pass there an entire context while you can't pass a position? I'd say that you shouldn't need to do either of them but maybe I don't see some cases.

## Alternative API

I think that we should look for an alternative API. One which:

* won't create the confusion of how it works when passing a single "thing",
* ~one which won't require supporting `new SchemaContext( ctx )` and passing a context instance to the method that we'll create~ EDIT: one which won't require supporting passing an entire context instance to the method that we'll create,
* one which has a clear opposite method.

So, why not getting back to the initially proposed `push()` and `pop()`?

```js
ctx2 = ctx.push( foo.getFirstChild() );

ctx3 = ctx.push( foo ).push( bar );
```

What was wrong with it that we had to introduce`concat()`?

**Comment by Reinmar** [comment]
cc @oskarwrobel @pjasiun

**Comment by Reinmar** [comment]
PS. In https://github.com/ckeditor/ckeditor5/issues/798 I explained that using strings, if possible, should not be common.

**Comment by Reinmar** [comment]
I got slightly confused about passing a context instance to `SchemaContext()`. For a moment I thought that it was connected with making `concat()` works. Then I realised that passing context instance to `concat()` is a separate thing – and this bit still requires clarification because it seems to be incorrect.

**Comment by Reinmar** [comment]
Another thing to fix – instead of writing everywhere in the API docs that a param is of this type:

```
{module:engine/model/schema~SchemaContextDefinition|module:engine/model/schema~SchemaContext}
```

Add `module:engine/model/schema~SchemaContext` to be a proper definition of `module:engine/model/schema~SchemaContextDefinition`. Inception ;) It all goes through the constructor anyway and the constructor supports that.

**Comment by oskarwrobel** [comment]
> You may expect to have the below twice:
>
> [someRoot, fooParent, foo, fooChild]
> But you won't. The latter version will contain this:
>
> [someRoot, fooParent, foo, someRoot, fooParent, foo, fooChild]

This is a bug. Maybe `SchemaContext` as a param is too much.

> Add module:engine/model/schema\~SchemaContext to be a proper definition of module:engine/model/schema~SchemaContextDefinition. Inception ;) It all goes through the constructor anyway and the constructor supports that.

We were talking about it and we wanted to do it tomorrow :)

**Comment by pjasiun** [comment]
> What does the below code do?
> 
> const ctx = new SchemaContext( foo );
> 
> const ctx2a = ctx.concat( foo.getFirstChild() );
> const ctx2b = ctx.concat( new SchemaContext( foo.getFirstChild ) );
> You may expect to have the below twice:
> 
> [someRoot, fooParent, foo, fooChild]
> But you won't. The latter version will contain this:
> 
> [someRoot, fooParent, foo, someRoot, fooParent, foo, fooChild]

This is designed behavior. The point was to prevent adding the whole path when a user adds an element, only this element should be added. Since it is confusing I agree that we do not need to support `SchemaContext` instance as the parameter there.

> The reason why the first version works is that concat() casts the param to an array. This is very significant, but hard to spot detail, which, got me by surprise. Especially that the code misses API docs. A code sample is a must in such cases. It says more than 1000 words.

I agree that samples to this code are needed, however, note that docs for the new code is not complete yet. We decided to merge these changes not to block others and work on the documentation after the merge.



> Another thing to fix – instead of writing everywhere in the API docs that a param is of this type:
> 
> {module:engine/model/schema~SchemaContextDefinition|module:engine/model/schema~SchemaContext}

Because it behaves differently, not like the `SchemaContextDefinition` and does not accept all its parameters.

> So, why not getting back to the initially proposed push() and pop()?
> 
> ctx2 = ctx.push( foo.getFirstChild() );
> 
> ctx3 = ctx.push( foo ).push( bar );
> What was wrong with it that we had to introduceconcat()?

The `push` suggests that it changes this object, not that it returns a new instance. In fact, I was not able to explain @oskarwrobel why it is that important to keep schema context immutable and feel that the nicest API we would achieve if the schema context would behave like an array, with `push` and `pop` methods.

**Comment by Reinmar** [comment]
> This is designed behavior. The point was to prevent adding the whole path when a user adds an element, only this element should be added. Since it is confusing I agree that we do not need to support SchemaContext instance as the parameter there.



Let's remove it then.



> We decided to merge these changes not to block others and work on the documentation after the merge.

Sure. I've been merging the initial docs with a delay too. But anyway, that'd be another thing to improve in this ticket.

> Because it behaves differently, not like the SchemaContextDefinition and does not accept all its parameters.

@oskarwrobel wrote something opposite ;) And I think you misunderstood the point. The point was that if `SchemaContext` is a proper `checkChild()` and `checkAttribute()` param, `SchemaContextDefinition` *must* include it. Otherwise, everywhere, in the entire engine API where a param which is then passed to any of these methods will need to be documented, you will need to always remember to specify that:

```
{module:engine/model/schema~SchemaContextDefinition|module:engine/model/schema~SchemaContext}
```

**Comment by pjasiun** [comment]
> > Because it behaves differently, not like the SchemaContextDefinition and does not accept all its parameters.
> 
> @oskarwrobel wrote something opposite ;)

My bad. I thought that you are asking why `concat` do not use `SchemaContextDefinition` as a parameter not about `checkChild()` and `checkAttribute()`. And, yes, we talked about it yesterday and for sure it should be done in the inception way. :)

**Comment by Reinmar** [comment]
> The push suggests that it changes this object, not that it returns a new instance. In fact, I was not able to explain @oskarwrobel why it is that important to keep schema context immutable and feel that the nicest API we would achieve if the schema context would behave like an array, with push and pop methods.

The concept of making things immutable doesn't come from me, naturally. For a very brief explanation, you can see the intro to https://facebook.github.io/immutable-js/.

The problem I have in this specific context is the fact that schema context instances are passed around as arguments. Similarly to positions and ranges. All these things define some concrete state. They encapsulate it, secure it and build API on top of it. We expect a position to be immutable because, otherwise, we need excessive cloning everywhere. The same is with the context. The basic fact that you want to change it during conversion (for which it's a param!) means that you may affect some code executed after you change it "just for a moment". Just like with the previous approach when we've been pushing to an array just to pop 2 lines later – it's just super ugly, but, most importantly, **unsafe**. You need to remember to pop and be sure that some code doesn't actually depend on the old value in the meantime.

I'm not an extreme fan of immutability, but I see its value in cases like this or positions and ranges.

BTW, [`List.push()`](https://facebook.github.io/immutable-js/docs/#/List/push) creates a new `List` ;)

**Comment by pjasiun** [comment]
Well, you will be still able to do so, by:
```js
arg[ 0 ] = arg[ 0 ].push( 'foo' );
```

But I get your point.

As for the name, both `push` and `concat` are fine for me. However, since we do not support `context.concat( otherContext )` anymore, `push` may makes more sense. Also, we do not need to support arrays, so `push` which accepts only `element` or `string` is better for me.
