### ISSUE TITLE
Model position as parent+offset

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1283]
I think that we made a mistake designing model position as an array of offsets.

The model position we have now is a path of offsets in ancestors. It means that it will be broken whenever an element is added before any ancestor. The solutions suppose to be live position, but the problem with live position is that you need to remember to detach it when it is not needed anymore. It makes live position not an option when you need to return position, what is, unfortunately, a common case.

Recently, working with @oskarwrobel on view to model conversion refactoring we met this problem.

There is [`splitToAllowedParent`](https://github.com/ckeditor/ckeditor5-engine/blob/226dcc6bddf9e7af73298b423332f5fcaa8e3272/src/conversion/viewconversiondispatcher.js#L487-L498) method which is used, for instance when an image is inserted in the paragraph. In such case, paragraph is split because image should be inserted directly into the `$root` element:

```
<paragraph>foo[]bar</paragraph> 
-> <paragraph>foo</paragraph>[1]<paragraph>[2]bar</paragraph>
-> <paragraph>foo</paragraph><image><paragraph>[2']bar</paragraph>

```

The method should return the split position [1] and the position in the newly created element [2] where next converter should continue conversion. Unfortunately, after image insertion position `[2]` will not be valid anymore (because of reasons mentioned before [2] != [2']). `LivePosition` also should not be returned because one may forget to detach it later. This is why this method return parent element instead of position what is just a workaround.

This is only one example of problems we have because of the current position representation.

We represent positions this way because of OT. For transformation, we need a position representation which can exist without document tree. For such usage, current representation makes a lot of sense. Unfortunately, it does not make much sense for all other use cases. For all other use cases position as parent+offset would be far better. Beside problem mentioned before:
 - live position implementation would be far more simple, and, in many cases, it will be not be needed to use live position. Parent+offset position will be broken only when something is inserted into the same parent, before the offset. That's a huge advantage since such position does not need to listen on document changes.
 - there will be the same representation of the position in the view and model.

This is why I propose to keep the current position as `PathPosition` or `StaticPosition` for operations and transformations usage and introduce new `Position` with parent+offset representation for all local use cases.

**Comment by scofalik** [comment]
Seems reasonable. From the top of my head, I can't think of any problems outside of OT. However, positions are used in so many places that this would require deeper research before starting any work.

It is true, that operating on that "new" position's parent would not require changing the position, but it might still require sending some kind of event representing that the position had changed. Some features might need this.

**Comment by pjasiun** [comment]
> BTW. This will require HUGE refactoring. I hope you understand this. And by HUGE I mean really HUGE. (So many algorithms in engine base on old positions and paths transformations.)

I know. But the current position, in basic plugins, makes sense only when the document does not change. The new position will work in such cases the same way but also let you use it when the document changes. It meant that, up to some point, the change should not break plugins and we can introduce it later.
 
> EDIT: OTOH, is there much sense bothering though, if that's just one case? You can easily
> return { parent, offset } object if you need that in that one or two cases we might have. I'd do this refactor only after there is a critical mass of places where we are screwed like this.

So far there are no enough reasons to work on it. But I remember that this topic appears every now and then, and we should start collecting all cases. We will work on it when we will have enough reasons.

**Comment by oskarwrobel** [comment]
It sounds good in general but I'm a bit scared when I think about all places (including tests) we'll need to change (and I'm sure I know maybe a half of them).

**Comment by Reinmar** [comment]
I don't see a big value in doing such a change. Yes, parent+offset positions are more natural way of thinking (if you know DOM ranges) and they are more forgiving, but it's "more", not "completely". If your code would split the parent of the position on an offset before the position, that position will become invalid anyway. So, there's some gain, but it's still unsafe to rely on this.
