### ISSUE TITLE
Do not expose both converters and helpers

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1306]
Right not both "helpers" (like `downcastAttributeToElement`) and "converters" (like `wrap`) are exposed. As long as we do not need both, we should limit exports only to "helpers" which can be call "converters". Current "converters" should be just a part or it, which is not exposed as separate function. It can even be merged into the single function.

**Comment by ma2ciek** [comment]
I remember, that on the latest TM some of us weren't sure about this change.

cc @scofalik

**Comment by Reinmar** [comment]
We were sure that we want to make it now, because we can always re-expose some things if needed. But we can't hide things which are published that easily.

**Comment by Reinmar** [comment]
PS. Of course, unless, when working on this task, we'll realise that we need some of them even now :D

**Comment by pjasiun** [comment]
So, in `downcast-converters.js`only these functions should be exported:
```
downcastElementToElement
downcastAttributeToElement
downcastAttributeToAttribute
downcastMarkerToElement
downcastMarkerToHighlight
```

While this should **not** be exported:
```
insertElement
insertText
remove
insertUIElement
removeUIElement
changeAttribute
wrap
highlightText
highlightElement
removeHighlight
createViewElementFromHighlightDescriptor
```

The tricky part here might be, how to modify tests to avoid using private functions.

**Comment by pomek** [comment]
> how to modify tests to avoid using private functions

Not only the tests but also [dev-utils/model](https://github.com/ckeditor/ckeditor5-engine/blob/a7c7eda1a50f1b03c306a953795f4d01f77268c9/src/dev-utils/model.js#L36).

**Comment by pjasiun** [comment]
> Not only the tests but also dev-utils/model.

For dev-utils we may have protected API.

**Comment by Reinmar** [comment]
I'll quote myself from #1556:

> I'm actually unsure now about hiding them :D With time, I got the feeling that most questions about conversion are questions about some odd cases. Like, extending existing converters, overriding some things, etc. I can't tell from my experience which of the functions we need, but if these helpers are used in our converters, there's a high chance that they can help in people's scenarios.

**Comment by pjasiun** [comment]
See my reply in https://github.com/ckeditor/ckeditor5-engine/issues/1556#issuecomment-423473492.

**Comment by Reinmar** [comment]
As I thought – I actually had to use `insertElement()` and not `downcastElementToElement()`. Using `insertElement()` allowed me to perform some custom actions (mapping) while still reusing 90% of the logic.

**Comment by Reinmar** [comment]
I'm closing this :D We're not going to do it anyway.

**Comment by pjasiun** [comment]
I believe it was fixed by https://github.com/ckeditor/ckeditor5-engine/pull/1613.
