### ISSUE TITLE
writer.setSelection improvements

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1308]
There are two problems with the current `writer.setSelection` implementation (both model and view).

1. It missleanding when single `element` is passed as a parameter. `writer.setSelection( image )` means `writer.setSelection( image, 0 )` and will put a collapsed selection in the offset `0` in the image. It is unexpected.
2. It is not possible to set a fake selection using this method.

Updated API should looks like this:
```js
witer.setSelection( paragraph, 'in' );
// Do: witer.setSelection( Range.createIn( paragraph ) );

witer.setSelection( paragraph, 'on' );
// Do: witer.setSelection( Range.createOn( paragraph ) );

witer.setSelection( paragraph, 0 );
witer.setSelection( paragraph, 'after' );
// Works the same way as now.

witer.setSelection( paragraph );
// Throws an exception.

witer.setSelection( range, { backward: true } );
witer.setSelection( paragraph, 'in', { backward: true } );
// Set backward selection. It should be object instead of the boolean value.

viewWiter.setSelection( range, { fake: true, label: 'Foo' } );
// Set fake selection. With 'Foo' as the label. 
```

**Comment by ma2ciek** [comment]
> It is not possible to set a fake selection using this method.

That's only view case, right?

> It missleanding when single element is passed as a parameter. writer.setSelection( image ) means writer.setSelection( image, 0 ) and will put a collapsed selection in the offset 0 in the image. It is unexpected.

I'd fix that API on the `Selection#setTo()` and level. So the `Writer` and `DocumentSelection` will only call this method.

**Comment by pjasiun** [comment]
> It is not possible to set a fake selection using this method.
> 
> That's only view case, right?

Yep.

> I'd fix that API on the Selection#setTo() and level. So the Writer and DocumentSelection will only call this method.

:+1:

**Comment by ma2ciek** [comment]
Maybe we could even change a little bit API to be more consistent? I mean, the first parameter would be `selectable` and the second `options`.

witer.setSelection( paragraph, { place: 'in' } );
// Do: witer.setSelection( Range.createIn( paragraph ) );

witer.setSelection( paragraph, { place: 'on' } );
// Do: witer.setSelection( Range.createOn( paragraph ) );

witer.setSelection( paragraph, { offet: 0 } );
witer.setSelection( paragraph, { offset: 'after' } );
// Works the same way as now.

witer.setSelection( paragraph );
// Throws an exception.

witer.setSelection( range, { backward: true } );
witer.setSelection( paragraph, { place: 'in', backward: true } );
// Set backward selection. It should be object instead of the boolean value.

viewWiter.setSelection( range, { fake: true, label: 'Foo' } );
// Set fake selection. With 'Foo' as the label.

**Comment by ma2ciek** [comment]
The syntax will be a little bit longer, but more explicit.

**Comment by pjasiun** [comment]
There are 2 problems with syntax you proposed.
 - It is not compatible with `Position.createAt` syntax (https://github.com/ckeditor/ckeditor5-engine/blob/8eba5e91872fff752e1950a9d2f9c19b8c41c057/src/model/position.js#L643-L662).
 - Element with no offset is incorrect. `options` should be additional, optional paramenters, not obligatory.

**Comment by ma2ciek** [comment]
I've done the first part, but have still some questions about the `fake` selection part.

Can it be changed like this:
```js
viewWiter.setSelection( range, { fake: true } ) // Should it clear selection label?
viewWiter.setSelection( range, { label: true } ); // Can it be invoked like this?
```
If the fake part is omitted, should this method change it? Or should it only when setting `{ fake: false }`?

I was wondering, whether we can remove the `setFake` method, but it won't be handy as the `setTo` method always sets range.

**Comment by pjasiun** [comment]
`setSelection`/`setTo` should be (for now) the only way to set fake selection and it should a new selection, what means it should reset all properties which are not defined. Usually, the fake selection is connected to the range an label and it does not make sense to change only a single property.

**Comment by ma2ciek** [comment]
So, assuming:

`writer#setFakeSelection()` and `Selection#setFake()` should be dropped after that change and view's `Selection#setTo()` should reset all properties.

Note: Model's `Selection#setTo()` doesn't change its attributes, so here is a little inconsistency.

**Comment by pjasiun** [comment]
> Note: Model's Selection#setTo() doesn't change its attributes, so here is a little inconsistency.

Does not? As I see in the code:
```
writer.setSelection
-> documentSelection._setTo
-> selection.setTo
-> selection._refreshAttributes()
-> selection._updateAttributes( true ); // true means that all attribute will be changed
```

**Comment by ma2ciek** [comment]
Hmm, right, `DocumentSelection` does it.
