### ISSUE TITLE
Conversion docs `for` describes non-existing `conversion.customConverter`.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-engine#1335]
I couldn't find `customConverter` on current API:

https://github.com/ckeditor/ckeditor5-engine/blob/28bde7404f8066e09eb2a0d30bca41420197093f/src/conversion/conversion.js#L97-L100

**Comment by jodator** [comment]
And I've found it again ¯\_(ツ)_/¯

Are doing anything with this? Looks like usefult but its API could change to:
```js
editor.conversion.for( 'downcast' ).addCustom( 'insert:paragraph', myConverter );
```

cc @Reinmar

**Comment by jodator** [comment]
I can also introduce it while working on #1556 TBH.

**Comment by Reinmar** [comment]
I think we resolved this already cause I cannot find any remains of this code. But please verify it, @jodator
