### ISSUE TITLE
@return used instead of @returns in api docs

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#1341]
Simply, there are multiple uses of `@return` instead of `@returns` in the api docs. It is probably correctly recognized by docs builder (cause no errors are thrown). Still, I think it is correct to use just one form.

**Comment by ma2ciek** [comment]
JSDoc, unfortunately, provides many aliases for some symbols :/

**Comment by jodator** [comment]
A "simple" fix for IntelliJ platform: 

Edit the `~/where/ide/config/files/are/config/options/options.xml` and add a line: `<property name="javascript.return.tag" value="returns" />`. Restart. Now the auto-annotator will use `@returns` tag.

Mine was in: `~/.PhpStorm2018.1/config/options`.

**Comment by Reinmar** [comment]
I fixed all `@return` occurrences.
