### ISSUE TITLE
Upcasting an element that has multiple attributes may not work

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#1348]
When trying to write additional converters for link-related attributes I realized that I am unable to do it using the new, refactored helpers. Here's why:

1. The original converter, declared in Link feature, converts `linkHref` model attribute to `<a href="">` view element. And the other way around.
2. Upcasting `<a href="">` causes consuming not only `href` attribute but also tagname `a` is consumed.
3. Another converter (let's say for `linkRel`) does not convert because `a` is already consumed.

We checked with @jodator how it works in Font Size and Font Family plugins. Unfortunately there's a bug. `<span class="text-huge" style="font-family: ... ">` is not read correctly - only `class` is read and converted to font size.

We need some kind of workaround for this.

**Comment by jodator** [comment]
I'd propose some switch that allows others to consume the same tag: `isBuffet: true` or something similar ;)

**Comment by jodator** [comment]
OK, after some fiddling I've got this working by changing this line:

https://github.com/ckeditor/ckeditor5-engine/blob/28bde7404f8066e09eb2a0d30bca41420197093f/src/conversion/upcast-converters.js#L141

to:
```js
const converter = _prepareToAttributeConverter( config, !config.view.dontConsumeName );
```

and I have some doubts about this.

First of all the name is just ugly but requires only to be set as `true` but on the other hand you have to ensure that this value is set in every `view` config - which might be not so cool

So maybe we should introduce `atributeToElementButNotConsumingTheElement()` converter?

/cc @scofalik

**Comment by scofalik** [comment]
`atributeToElementButNotConsumingTheElement()` is too much hassle, it would not differ much than the already existing converter and we would have to add also in `Conversion` class (two-way converter).

I am also against any flag that has negation in its name. It should be either `consumeName` or something that has opposing meaning but does not have negation in the name. I am okay with `consumeName` and we need to just decide whether we want it to be `true` or `false` by default.

Having `true` by default is backward compatible. Also, you can skip it for Basic Styles features and Link... something else?

Having `false` by default is a cleaner code. Then, you can skip it for most other features, which use "generic" `<span>` element.

🤷‍♂️

**Comment by jodator** [comment]
`atributeToElementButNotConsumingTheElement()` the name is obviosly wrong but I don't have a better proposal - so proposing it as a concept not the name.

**Comment by jodator** [comment]
@scofalik but isn't this flag `consumeName` view config dependand?

Let's look at the alternative Bold definition:
```js
editor.conversion.attributeToElement( {
	model: BOLD,
	view: {
		name: 'span',
		style: {
			'font-weight': 'bold'
		},
		// Here should be defined that consumeName:
		consumeName: false
	},
	upcastAlso: [
		'b',
		'strong',
		{
			name: 'span', // not really valid I suppose
			style: {
				'font-weight': 'bolder'
			},
			// Here *could* be defined that consumeName:
			consumeName: false
		},
		{
			style: {
				'font-weight': 900
			}
		}
	]
} );
```

**Comment by jodator** [comment]
OK so I'd go with `consumeName: false` as default. This would require to change some definitions:

As an example the bold feature:
```js
editor.conversion.attributeToElement( {
    model: BOLD,
    // was: view: 'strong',
    view: {
        name: 'strong',
        consumeName: true
    },
    upcastAlso: [
        // was: 'b'
        {
            name: 'b',
            consumeName: true
        },
        {
            style: {
                'font-weight': 'bold'
            }
        }
    ]
} );
```

Features requiring adding `consumeName: true`:
- code (`<code>`)
- italic (`<i>`, `<em>`)
- strikethrough (`<s>`, `<del>`, `<strike>`)
- underline (`<u>`)
- highlight
Features that will be left untouched (mostly those using `<span>`):
- font size
- font family

**Comment by jodator** [comment]
But we will need to change the API / docs as the `view` is a `MatcherPattern` that does not have this property `consumeName`... :face_with_head_bandage:

**Comment by pjasiun** [comment]
A remember that we (me with @scofalik) talked about this issue when it appeared and agreed that name should be consumed if the converter is from the element with no attributes, so `<strong>` should consume name, but `<span style: 'font-weight'='bold'>` should not consume name (should consume only the style). We considered some cases and were not able to find any case when it would lead to an issue. I think it should work this way, and I am against introducing any `consumeName` property.

**Comment by jodator** [comment]
@pjasiun: What with `<mark class="marker-green">`?

**Comment by Reinmar** [comment]
I think that I agree with @pjasiun. I came to the same (or similar) conclusion when reading your discussion above.

What I'd like to point here is that we have two simple features – bold and link. If you need to understand what consumption is in order to correctly implement them, then I think this is a mood killer.

Therefore, it'd be best to avoid the need to specify this param in such cases. I think that the param can exist to let you control this if you don't like the default behaviour, but the default should be good.

And, from what I can see, the default can be this:

* If the `view` specifies the name only, then you consume the name,
* If the `view` specifies something more than the name – consume those things only.

---

> @pjasiun: What with `<mark class="marker-green">`?

If you'll go with the default, no big harm will happen – only the class will be consumed and everything will work correctly (am I right?).

But, if we feel that the highlight feature should not allow for the `<mark>` element being used with e.g. two classes (`marker-green` and `my-class-for-whatever-feature-I-like`) and being upcasted by two features, then it could pass `consumeName: true` to override the default behaviour. But I really don't think that we need that in case of that feature.
