### ISSUE TITLE
Two-step caret movement fails when link is followed/preceded by a widget

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1352]
![image](https://user-images.githubusercontent.com/156149/37301820-fd07d1cc-2629-11e8-9b08-f2e8b4bc927f.png)

When an image is right after a link, you cannot escape the link – you're either inside it or move the caret to the image.

**Comment by oleq** [comment]
If I got the TC right, we fixed that in https://github.com/ckeditor/ckeditor5-engine/issues/1301

![kapture 2018-04-20 at 11 04 05](https://user-images.githubusercontent.com/1099479/39042216-924d54e0-448a-11e8-9f6e-5794986836f7.gif)
