### ISSUE TITLE
Should model.Writer#setTextData() be removed?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1363]
I can't see it used... and it shouldn't be used at all because it changes the text node's data directly:

```js
	/**
	 * Sets the text content for the specified `textNode`.
	 *
	 * @param {String} value New value.
	 * @param {module:engine/model/text~Text} textNode Text node that will be updated.
	 */
	setTextData( value, textNode ) {
		textNode._data = value;
	}
```

**Comment by pjasiun** [comment]
https://github.com/ckeditor/ckeditor5-list/blob/d2023267caa88eb383b1fab773e137c233cf5b8d/src/converters.js#L456

https://github.com/ckeditor/ckeditor5-list/blob/d2023267caa88eb383b1fab773e137c233cf5b8d/src/converters.js#L461

**Comment by pjasiun** [comment]
This is the view writer, and I believe it should works allways. You should usually not change view without changes in the model, but it is a different topic.

**Comment by Reinmar** [comment]
It's the view writer? In upcast converters? I'm a bit lost. I was talking about the model writer which has the `setTextData()` method.

**Comment by pjasiun** [comment]
Ach, I agree then. Model marker should not have this method.
