### ISSUE TITLE
downcastAttributeToElement does not support downcasting from specified model element

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#1370]
`downcastAttributeToAttribute` converter lets us specify from which model element the attribute is converted. This is an example configuration:

```
downcastAttributeToAttribute( {
	model: {
		name: 'image',
		key: 'source'
	},
	view: 'src'
} );
```

In this case, `source` attribute is converted only from images.

The same is not possible with `downcastAttributeToElement`. There are two things we can do now:

1. Assume that this kind of conversion always happens for `$text`. This is quite a rational assumption given that the converter uses `wrap` converter which is meant to wrap parts of view in `AttributeElement`. I don't know if there's any other real case. Maybe if we will add inline elements or something.

2. Provide support for `name` in config.

**Comment by pjasiun** [comment]
2

**Comment by Reinmar** [comment]
What will this converter do? What kind of element will it create and what's the use case in general?

**Comment by scofalik** [comment]
It doesn't matter what kind of element will it create because we are talking here about `model` part of config, so about the part that is converted (and consumed).

In short, we are deciding whether we should give control over the event name to which the converter will be added. It could be `attribute:attrName` or `attribute:attrName:elementName`. In the second case, only `attrName` set on `elementName` will be converted.

We could also hardcode `$text` in the place of `elementName`, but then the inline features (like for example smileys) would not be wrapped (so a smiley might break a link, for example). So we should definitely go with solution 2. as it is future-proof.
