### ISSUE TITLE
Retain Inline styles and Tags in CKEditor

### ISSUE THREAD

**Issue by ArvindBS** [ckeditor/ckeditor5-engine#1374]
I am using CKEditor 5 inline editor build 1.0.0-alpha.2. CKEditor automatically strips all the style classes. I am using it to send email. Please help.

**Comment by Reinmar** [comment]
Please see https://stackoverflow.com/questions/47734328/ckeditor-5-allow-span-elements-and-attributes.

If you have more (specific) questions, StackOverflow will be the best place to ask them.
