### ISSUE TITLE
How to have a command which works on `$text` and `$block` both ?

### ISSUE THREAD

**Issue by gauravjain028** [ckeditor/ckeditor5-engine#1376]
I need to use `upcastAttributeToAttribute` with style tag of each html/tag (block).  I want to create a plugin for text color. I have added font tag if user select any text and then apply color on it. But I do not want to add font tag if use has selected any `$block`. 

So far my converters are like

```
export default class UcColorEditing extends Plugin {
    /**
     * @inheritDoc
     */
    init() {
        const editor = this.editor;
        // Allow bold attribute on text nodes.
        editor.model.schema.extend( '$text', { allowAttributes: 'textColor' } );
        editor.model.schema.extend( '$block', { allowAttributes: 'blockTextColor' } );

        // Build converter from model to view for data and editing pipelines.

        editor.conversion.for( 'downcast' )
            .add( downcastAttributeToElement( {
                model: 'textColor',
                view: ( modelAttributeValue, viewWriter ) => {
                    return viewWriter.createAttributeElement( 'font', { style: 'color:' + modelAttributeValue } );
                }
            } ) );

        editor.conversion.for( 'downcast' )
            .add( downcastAttributeToAttribute( {
                model: 'blockTextColor',
                view: modelAttributeValue => ( { key: 'style', value: { color : modelAttributeValue } } )
            } ) );


        editor.conversion.for( 'upcast' )
            .add( upcastElementToAttribute( {
                view: {
                    name: 'font'
                },
                model: {
                    key: 'textColor',
                    value: viewElement => viewElement.getStyle( 'color' )
                }
            } ) );

        editor.conversion.for( 'upcast' )
            .add( upcastAttributeToAttribute( {
                view: {
                    key: 'style',
                    value: {
                        color:/[\S]+/
                    }
                },
                model: {
                    key: 'blockTextColor',
                    value: viewElement => {
                        return viewElement.getStyle( 'color' );
                    }
                }
            } ) );

        // Create bold command.
        editor.commands.add( 'ucColor', new UcColorCommand( editor, 'blockTextColor' ) );
        editor.commands.add( 'ucColor', new UcColorCommand( editor, 'textColor' ) );
    }
}

```

I have 2 more things to do 
-1 : how to decide when to execute command with `textColor` attribute or `blockTextColor` attribute.
-2 : When I do like `writer.setAttribute( 'blockTextColor', data.textColor, range );` in command, it gives me js error `Uncaught TypeError: Cannot read property '_setStyle' of undefined`  due to second upcast. I think it is related with viewElement is undefined. 

Any idea how can I get it done?

**Comment by jodator** [comment]
Hi @gauravjain028 sorry for the delay, but here is what I've tested and what works. As always please remember that is better to ask question on [StackOveflow with CKEditor 5 tag](https://stackoverflow.com/questions/tagged/ckeditor5).

I've used your `UcColorEditing` class with minor change: there is only one `'ucColor'` command.

```js
editor.commands.add( 'ucColor', new UcColorCommand( editor ) );
```

Ad. 1. I've created a `UcColorCommand` that accepts a `value` as an option and it either apply `textColor` to a selected text or `blockTextColor` to a collapsed attribute parent.

Ad. 2. I didn't get this error but I've filtered out `validRanges()` from selection.

The command that worked for me is:
```js
class UcColorCommand extends Command {
	refresh() {
		// TODO: this should change whether selection allows to set - as now it is hardcoded
		this.isEnabled = true;
		this.value = true;
	}

	execute( options = {} ) {
		const model = this.editor.model;
		const document = model.document;
		const selection = document.selection;

		// Take the color from options.value.
		const color = options.value;

		model.change( writer => {
			// Selection is collapsed - work on selection parent.
			if ( selection.isCollapsed ) {
				// Take the first parent from selection
				const parent = Array.from( selection.getSelectedBlocks() )[ 0 ];

				// If color is passed - set the attribute. Remove otherwise.
				if ( color ) {
					writer.setAttribute( 'blockTextColor', color, parent );
				} else {
					writer.removeAttribute( 'blockTextColor', parent );
				}
			}
			// Selection is not collapsed - work on selected text.
			else {
				// Get ranges on which 'textColor' attribute can be set.
				const ranges = model.schema.getValidRanges( selection.getRanges(), 'textColor' );

				for ( const range of ranges ) {
					// If color is passed - set the attribute. Remove otherwise.
					if ( color ) {
						writer.setAttribute( 'textColor', color, range );
					} else {
						writer.removeAttribute( 'textColor', range );
					}
				}
			}
		} );
	}
}
```

So there is only one command named `'ucColor'` (in your code I think that the first one was overwritten by the latter).

To execute it use:
```js
// to set attribute (depending on selection)
editor.execute( { value: 'red' } );

// to remove attribute (depending on selection)
editor.execute();

**Comment by gauravjain028** [comment]
@jodator Thanks for your reply.
I will try that solution. But I have 1 question : for example if I select whole content of a `p` tag, then according to code, it will still be applicable by `textColor` and will add the font tag. Is there any way to apply color on block if I have selected all the content of block?

**Comment by jodator** [comment]
@gauravjain028 Yes. I've checked how the ranges are passed from a selection.

You'll get a range for each of selected block so you can check if a range [is flat](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_range-Range.html#member-isFlat) and if [start position](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_range-Range.html#member-start) is at [start](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_position-Position.html#member-isAtStart) and the [end position](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_range-Range.html#member-end) at [end](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_model_position-Position.html#member-isAtEnd) of a block:

```js
const shouldUseBlock = range.isFlat && range.start.isAtStart && range.end.isAtEnd;

// this is the block you are looking for:
const parent = range.start.parent;
```

**Comment by Reinmar** [comment]
Can we close this issue now?
