### ISSUE TITLE
Group names in Conversion#for() are ungrammatical

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1377]
Currently:

```js
conversion.for( 'dataDowncast' ).add()
conversion.for( 'editingDowncast' ).add()
conversion.for( 'downcast' ).add()
conversion.for( 'upcast' ).add()
```

The problem is that "to downcast" is a verb. Not a noun. So you use it "it downcasts the data". Or "it's used for data downcasting", in which case "downcasting" is a noun.

The other problem is that `for()` should accept a noun. For him, for it, for this cause, etc. So, we can't have this:

```js
conversion.for( 'downcastData' ).add()
```

We should have this:

```js
conversion.for( 'dataDowncasting' ).add()
conversion.for( 'editingDowncasting' ).add()
conversion.for( 'downcasting' ).add()
conversion.for( 'upcasting' ).add()
```

Which... looks bad to me because "editing downcasting" look like two random verbs here. Also, it's a bit weird that we add them before "downcasting". They concreticise the pipeline, so... let's try like with events:

```js
conversion.for( 'downcast:data' ).add()
conversion.for( 'downcast:editing' ).add()
conversion.for( 'downcast' ).add()
conversion.for( 'upcast' ).add()
```

Better... except the fact that we again got back to for+verb. Fortunately, I think I can live with that because once we got rid of strange word pairs like "data downcast" and "editing downcast" it's acceptable.

However, if you have an idea for a better method name than `for()`, please share it!

**Comment by Reinmar** [comment]
PS. Perhaps the good thing about the last proposal is that we'll change only these two specific conversion names, while leaving the most popular "downcast" and "upcast".

**Comment by scofalik** [comment]
Let's go with the last one. Sounds good, have good association.

**Comment by pjasiun** [comment]
For me `conversion.for( 'dataDowncast' )` is a shortcut for `conversion.for( 'dataDowncastPipeline' )`. I think it will be misleading for devs if we will call it `downcast` in one place and `downcasting` in other. 

Last option with `:` is fine as long as it will not blow up any event.

Also, as much as I agree that names in the code should be good and clear, we should remember that we are writing code, not an essay.

**Comment by Reinmar** [comment]
> Also, as much as I agree that names in the code should be good and clear, we should remember that we are writing code, not an essay.

And we should remember that good code is easy to read ;P

**Comment by scofalik** [comment]
Dispatchers groups have nothing to do with events.

**Comment by oleq** [comment]
TBH, only the "current one" makes sense to me. 

```js
conversion.for( 'dataDowncasting' ).add()
conversion.for( 'editingDowncasting' ).add()
```
is overengineered and
```js
conversion.for( 'downcast:data' ).add()
conversion.for( 'downcast:editing' ).add()
```
looks like a part of an event system.

BTW, according to http://www.dictionary.com/browse/downcast "downcast" is a noun too.

**Comment by scofalik** [comment]
> BTW, according to http://www.dictionary.com/browse/downcast "downcast" is a noun too.

Told you, @Reinmar.

**Comment by pjasiun** [comment]
> > Also, as much as I agree that names in the code should be good and clear, we should remember that we are writing code, not an essay.
> 
> And we should remember that good code is easy to read ;P

You know that changing "downcast" to "downcasting" does not make code far more easy to read, don't you?

**Comment by Reinmar** [comment]
> BTW, according to http://www.dictionary.com/browse/downcast "downcast" is a noun too.

I like this!

> a shaft down which air passes, as into a mine (opposed to upcast).

!!! Perfect analogy.

So, `dataDowncast` is fine now. ❤️
