### ISSUE TITLE
Inconsistent order of params in the model writer

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1378]
I've just had to write this:

```js
	for ( const block of blocks ) {
		if ( !block.is( 'foo' ) ) {
			writer.rename( block, 'foo' );
			writer.setAttribute( 'fooClass', fooClass, block );
		}
	}
```

And I suffer. Was there any particular reason why the order doesn't match?

**Comment by Reinmar** [comment]
The same here:

```js
		writer.setAttributes( {
			'bold': true,
			'italic': true
		}, range );
```

If range was first, it'd be easier to format.

**Comment by scofalik** [comment]
It was done like this to achieve consistency. The target is always last.

**Comment by Reinmar** [comment]
In `writer.rename( block, 'foo' )` the target is first. In `split()` as well.

Uh... but then I found `append()`, `setTextData()`...

This isn't common to specify a target of a method at the very end. And it's not even consistent within the writer itself.

**Comment by pjasiun** [comment]
I don't think that order is inconsistent. It is `fun( what?, where? )` for all methods. I remember we spend some time thinking about it and to make all methods work the same way. 

However, I agree that it's strange. Even recently I was surprised why it is this way.

We should change if we can do with the other order (what, where). I would make more sense, but may not work for all methods.

**Comment by Reinmar** [comment]
Right now we have e.g. this:

```js
appendElement( name, [ attributes ], parent )
insertElement( name, [ attributes ], itemOrPosition, [ offset ] )
```

Whichever order we'll choose we won't avoid a messed order in which optional params are in the middle. But I think that I'm ok with this order:

```js
insertElement( name, [ attributes ], itemOrPosition, [ offset ] )
```

Here, name+attrs is the subject and "where"  is the place.

In `setAttribute( attrs, item )` the subject comes second. So I think that perhaps only `set/removeAttribute()` are wrong here. The rest seems fine. In all other methods I checked, the subject comes first.

**Comment by Reinmar** [comment]
OK, maybe one more:

```js
setTextData( value, textNode )
```

**Comment by Reinmar** [comment]
Argh... nvmnd. I'm closing this. It was absolutely confusing at first but `rename()` + `setAttribute()` is the most ridiculous looking pair of all. The rest is more acceptable and it indeed follows the `"what", "where"` rule. It only looks bad if you think about it as `"subject", < the rest >`.
