### ISSUE TITLE
Make the Mapper in the DataController usable outside the conversion scope

### ISSUE THREAD

**Issue by CHItA** [ckeditor/ckeditor5-engine#1415]
The purpose of this change would be to make it possible to use the `Mapper` in the `DataController` outside the conversion phase (in my specific case, it would be in a `DataProcessor` implementation). 

Moving the `this.mapper.clearBindings()` [lines](https://github.com/ckeditor/ckeditor5-engine/blob/master/src/controller/datacontroller.js#L170-L171) to the beginning of the `toView()` method would make this possible, and hopefully would not conflict with how the editor would behave. I have not tested this solution, therefore the actual solution to the problem could be more difficult.

To create an issue came up in the answer of [this question on stackoverflow](https://stackoverflow.com/questions/50039861/ckeditor5-view-model-position-and-range-conversion), and the question contains a more detailed explanation of why I would need this feature.

**Comment by pjasiun** [comment]
It is not recommended to use mapper and model in `DataProcessor `. It breaks layers separation: data controller should convert between data and view. If any data from the model is needed it should be converted to view earlier.

However, the change you propose looks good. It will be safer for the next conversion to clear bindings at the beginning, and it will be let people to get read mapper biding.

**Comment by pjasiun** [comment]
Sure, this is why I said that I'm fine with it :)

**Comment by CHItA** [comment]
Yeah, I understood, I just felt the need to add the standard disclaimer that I know you don't recommend doing what I'm doing (although I probably should start with that with all my CKE5 questions). :)
