### ISSUE TITLE
Block filler must be rendered in empty lines created by <br>

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1422]
![may-30-2018 11-51-21](https://user-images.githubusercontent.com/156149/40713361-0784198a-6400-11e8-8704-dc3aca77afc4.gif)

Unfortunately, we must achieve this when rendering a block which ends with a line break:

```html
<p>...<br>BLOCK_FILLER</p>
```

`BLOCK_FILLER` is a `<br data-cke-filler=true>` inside the editing view and `&nbsp;` in the data.

So, we need to adjust the logic which decides where to place block fillers. In general, block filler is needed after a `<br>` if that `<br>` is the last node of a container element:

```html
<p>XXX<br>YYY<br>ZZZ<br>BLOCK_FILLER</p>
<p>XXX<br>YYY<br>ZZZ<br>ĄŚĆ</p>
<p><br>YYY<br>ZZZ<br>ĄŚĆ</p>
```

**Comment by pomek** [comment]
Unfortunately I won't help:

![image](https://user-images.githubusercontent.com/2270764/41082140-93a6ef72-6a2d-11e8-8b58-ad3c13c66f9c.png)

`Text` => <kbd>Space</kbd> => <kbd>Shift+Enter</kbd> => <kbd>a</kbd>
