### ISSUE TITLE
[FF] Complex selection when flashes spanning across a widget

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-engine#1440]
A followup of https://github.com/ckeditor/ckeditor5-engine/pull/1431#issuecomment-396207242.

![kapture 2018-06-19 at 11 39 26](https://user-images.githubusercontent.com/1099479/41598872-d1413f60-73d1-11e8-8dae-19883844e05d.gif)

**Comment by Reinmar** [comment]
I checked how the selection post-fixer fixes the selection:

![image](https://user-images.githubusercontent.com/156149/42282876-2554a718-7fa8-11e8-81a8-4fb44e41320b.png)

The fixed ranges ("before combining") are ok. The thing is, though, that they don't get combined. We select two ranges and I think that it may be breking Firefox. Those not combined ranges look reasonably, but still – Firefox starts doing weird things.

Another thing is that the whole selection is blinking. I think that we may need to stop re-rendering while it's being "done". E.g. I changed `toWidget()` so it stops setting `cE=false`. We stopped having the two-range selection problem but blinking was severe. So we'll have to fix two things here – setting a reasonable selection and avoiding blinking.

**Comment by Reinmar** [comment]
I made a quick fix which better merges ranges:

![image](https://user-images.githubusercontent.com/156149/42283296-55c8c31a-7fa9-11e8-9219-4c6695a51242.png)

It's not valid cause it looks like this now:

```js
		if ( combinedRanges.length > 1 ) {
			const r = new Range( combinedRanges[ 0 ].start, combinedRanges[ 1 ].end );
			combinedRanges = [ r ];
		}
```

But it prevented breaking the selection.

![jul-04-2018 16-44-44](https://user-images.githubusercontent.com/156149/42283400-9bef3248-7fa9-11e8-9745-d9d903645e5b.gif)

**Comment by Reinmar** [comment]
In fact... I think that we can do a quick fix here to always combine multi-range selections into a single-range selection. This only applies to Firefox and if it won't break anything in tables (which I think it won't), then we'll at least prevent breaking the selection. It will still blink, but we can handle this separately.

**Comment by jodator** [comment]
@Reinmar The proposed fix looks OK in this scenario. What about actual mutli-range selection?

I think that we cannot blindly merge mutli selection into one big selection:

1. Select some parts of text before image:
![selection_002](https://user-images.githubusercontent.com/247363/42309600-56dea0e0-8039-11e8-830f-5ca13722312c.png)

2. Merge `combinedRanges`:
![selection_003](https://user-images.githubusercontent.com/247363/42309615-663630ee-8039-11e8-8de4-10826638efb7.png)

ps.: Currently I'm debuging mergin only one of ranges and it looks like it doesn't work... only changing selection to one range looks like it "fixes" something.

**Comment by Reinmar** [comment]
> I think that we cannot blindly merge mutli selection into one big selection:

We don't have to support multi-range selections. Only one browser supports them anyway. And we can make shortcuts as I don't think any user actually knows how to create such selections.

Also, we're talking about combining ranges *if* they were fixed. Not always.

**Comment by jodator** [comment]
> Also, we're talking about combining ranges if they were fixed. Not always.

Yep only then it will happen so after testing it I'm OK with this change anyway.

I will make this change part of https://github.com/ckeditor/ckeditor5-engine/pull/1450.

**Comment by Reinmar** [comment]
I extracted the "flashing" part to https://github.com/ckeditor/ckeditor5-engine/issues/1457.

The fact that Firefox was breaking the selection (you were losing the anchor) was fixed in https://github.com/ckeditor/ckeditor5-engine/pull/1450 so I'm closing this ticket.
