### ISSUE TITLE
Engine crashes due to an infinite loop when loading incorrect data

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1441]
As reported on

https://stackoverflow.com/questions/50978203/ckeditor5-custom-container-element-recursion-error-on-paste

Quote:

---

```js
export default class MyWidgetPlugin extends Plugin {

  init() {

    const editor = this.editor;

    editor.model.schema.register('my-widget', {
      inheritAllFrom: '$root',
      isLimit: true,
    });

    editor.conversion.elementToElement({ model: 'my-widget', view: 'my-widget' });
    editor.commands.add('myWidget', new MyWidgetCommand(editor));

  }

}

class MyWidgetCommand extends Command {

  execute() {

    const editor = this.editor;
    const block = first(this.editor.model.document.selection.getSelectedBlocks());

    this.editor.model.change(writer => {

      const myWidget = writer.createElement('my-widget')
      writer.insert ( myWidget, block, 'after');
      writer.appendElement( 'paragraph', myWidget );

    });

  }

}
```

Inserting a widget injects this into the editor:

```html
<my-widget>
  <p></p>
</my-widget>
```

And I can type fine, but I can't paste. I'm guessing I got the schema wrong... have played around with quite a few different options.. but to no avail.

![ivwmk](https://user-images.githubusercontent.com/156149/41769571-06c9589e-7610-11e8-8ca1-f18899c049e4.png)

---

As I replied on SO, the schema is defined incorrectly. However, it should not crash.

**Comment by scofalik** [comment]
According to a reply on SO, your suggestion about Schema fixed the issue.

**Comment by scofalik** [comment]
BTW. I was unable to put a selection in that widget before I added `allowWhere: '$block'`.

**Comment by f1ames** [comment]
I have check this issue on `ClassicEditor` with both full plugin code (as posted in initial report) and a minimal sample:

```js
ClassicEditor
  .create( ... )
  .then( editor => {
    editor.model.schema.register( 'my-widget', {
      inheritAllFrom: '$root',
      isLimit: true,
    } );

    editor.conversion.elementToElement( {
      model: 'my-widget',
      view: 'my-widget'
    } );

    // Trigger issue:
    setTimeout( () => {
      const block = editor.model.document.selection.getSelectedBlocks().next().value;

      editor.model.change( writer => {
        const myWidget = writer.createElement( 'my-widget' );
        writer.insert( myWidget, block, 'after' );
        writer.appendElement( 'paragraph', myWidget );
      } );
    }, 1000 );
  } )
  .catch( ... );
```

and in both cases error is not thrown and `<my-widget><p></p></my-widget>` is inserted correctly. Also I have tried different plugins combinations and different content types inside custom widget but still weren't able to reproduce the issue.

It seems the error have been fixed somewhere along the way. Closing this issue.
