### ISSUE TITLE
How do I capitalize the first line?

### ISSUE THREAD

**Issue by zhaoyouliang** [ckeditor/ckeditor5-engine#1447]
When composing notes use ckeditor on his iPhone, I was used to the auto-capitalization feature his phone normally provides in other text areas.  He'd like the first letter in each line to automatically become capitalized.
this is question about iphone (Auto-Capitalization)

**Comment by Reinmar** [comment]
It's a DUP of https://github.com/ckeditor/ckeditor5/issues/1111. Am I right?

**Comment by zhaoyouliang** [comment]
Do you have a good way to do it ？@Reinmar 
thanks
