### ISSUE TITLE
Have just one MoveOperation

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#1461]
This is a follow-up after OT refactor PR:
https://github.com/ckeditor/ckeditor5-engine/pull/1459

Having just one `MoveOperation` with different `type` property value might simplify some places in the code. Right now, `RemoveOperation` and `ReinsertOperation` extends `MoveOperation` but aren't much different from it.

**Comment by pjasiun** [comment]
I hope this way we will be able to simplify `getTransformation` after this change.

See https://github.com/ckeditor/ckeditor5-engine/pull/1459/files#r204375812.
