### ISSUE TITLE
How to remove <p> and </p> in Ckeditor5?

### ISSUE THREAD

**Issue by sunfeng90** [ckeditor/ckeditor5-engine#1466]
When I use `window.editor.getData()` to get the data I have insert, but I commit got the content with `<p>`. How to remove the `<p>` and `<image>`.

**Comment by pjasiun** [comment]
Could you give more information? What kind of `<image>` you want to remove?

**Comment by sunfeng90** [comment]
When I insert a imge file to the content, I will got the `<figure class="image"><img src="https://upload.jdcf88.com/test/2018/7/25/15325125131092.png"></figure>`

When i insert 124455 to the content, I got `<p>232232323232323</p>`.How to solve? I want to got 124455  and https://upload.jdcf88.com/test/2018/7/25/15325125131092.png.How to delete the <p> and <figure> tags?

**Comment by sunfeng90** [comment]
I use `window.editor.getData()` to get the data I inserted before.

**Comment by Reinmar** [comment]
CKEditor 5 outputs HTML, not a plain text. If you need a different data format you'd need to implement a custom [data processor](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_dataprocessor_dataprocessor-DataProcessor.html) but that makes sense only in very specific cases. If you want to use a rich-text editor, then I'd recommend sticking to HTML.

**Comment by sunfeng90** [comment]
Thanks！

**Comment by sunfeng90** [comment]
I fixed this problem in following way: `export function ckEditorRemoveTags (data) {
  return data
    .replace('<p>', '')
    .replace('</p>', '')
    .replace('<figure class="image">', ',')
    .replace('<img src="', '')
    .replace('"></figure>', '')
}`.But when I edit the content, I cannot show the image.I only show the url.For example `2332323232323223,https://upload.jdcf88.com/test/2018/7/25/15325318644189.png`
