### ISSUE TITLE
Change context.aIsStrong to context.isStrong()

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#1469]
At the moment `context.aIsStrong` is a property and needs to be set before `transform()` calls:

```javascript
context.aIsStrong = true;
const newOpA = transform( opA, opB, context );

context.aIsStrong = false;
const newOpB = transform( opB, opA, context );
```

We should change it to a function that takes an operation and returns `true` or `false`, appropriately.

**Comment by scofalik** [comment]
When implementing this ticket I noticed that it is impossible at the moment, because of this:

```javascript
function transform( a, b, context = { aIsStrong: false } ) {
	const transformationFunction = getTransformation( a, b );

	return transformationFunction( a.clone(), b, context );
}
```

`a` operation is cloned before it is passed to `transformationFunction`. This means that a hypothetical `context.isStrong()` function will not work because `a` operation inside OT algorithm will be different than the one registered, for example, in `context.originalOperations`.

In order for that to work, we would have to either add `a.clone()` to original operations before firing `transformationFunction` (which might be redundant) or we would have to stop passing `a.clone()` which would mean that it would need to be moved to the most of algorithms.

Given those circumstances I change my mind, and I rather have simple object with properties as context in `transform()` and have those "local contexts" calculated beforehand in `transformSets()`. It is also better for unit tests.

So, in this ticket, instead of changing `aIsStrong` to `isStrong()`, I will change `wasUndone()` to `aWasUndone` and `bWasUndone`.

**Comment by pjasiun** [comment]
As we talked F2F, we could add a link from `a.clone()` to `a` in the context object. I think it will be still lighter if we will not create a new context object for each transformation. Also, after the transformation, you set the orginal operation of the cloned (and transformed operation) anyway: https://github.com/ckeditor/ckeditor5-engine/blob/00fbf7faba81b8e9c3caa3558a22e5a1b66ff17a/src/model/operation/transform.js#L125
so you could mark it directly after cloning it. However, I agree that it won't be the clearest solution. In fact, the clearest solution would be to clone inside `setTransformation` but it would cause the code to grow significantly.

**Comment by pjasiun** [comment]
After some additional time, I spent with this code I think that what we have now (a context which is passed to the transform function is a set of properties, not functions) is fine. It should be simpler for debugging.

However, the fact that we have 2 structures which are called "context" in the same file is misleading. For instance, one may expect that `initializeContext` will create the object which is accepted as `context` in transformation function. We should rename one of these. I think that "global" context could be renamed to "contextFactory" (`initializeContext` -> `initializeContextFactory`).

**Comment by scofalik** [comment]
🎉 👍
