### ISSUE TITLE
Error misses a description

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1479]
https://github.com/ckeditor/ckeditor5-engine/blob/master/src/model/selection.js#L434

Please try to imagine why people get this error (it's 5th most popular). I think they may be using broken installations with duplicated ckeditor5-engine or native `Range()` for instance. Would be good to explain both things.

**Comment by pjasiun** [comment]
I can imagine 2 cases:

1. Wrong build (the Range class and the Selection class comes from different builds).
2. One tries to use a native `Range` class here.

**Comment by Reinmar** [comment]
That's exactly what @scofalik documented in #1481 :)

**Comment by pjasiun** [comment]
I reopen this ticket because the PR is not yet merged.
