### ISSUE TITLE
Remove OperationFactory

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1508]
[`OperationFactory`](https://github.com/ckeditor/ckeditor5-engine/blob/763c0f79c97f9e54c2608689faec3ad2524b550b/src/model/operation/operationfactory.js) is not needed anymore and should be removed.

**Comment by scofalik** [comment]
It is used in OT tests and was very helpful there. But maybe it can be substituted by something smaller.

**Comment by oskarwrobel** [comment]
It is needed.

**Comment by oskarwrobel** [comment]
I mean it's needed not only in tests.
