### ISSUE TITLE
Rename `Writer` to `DowncastWriter`

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-engine#1515]
As we are going to introduce second `View Writer` called `UpcastWriter` (#1501), the former `Writer` needs to be renamed to keep things consistent. It will be renamed to `DowncastWriter` to play nicely with `UpcastWriter`.

Btw. isn't it a breaking API change?

**Comment by Reinmar** [comment]
Agree. It's a good moment to make this change.
