### ISSUE TITLE
How to enter text after an image？

### ISSUE THREAD

**Issue by wenmingtang** [ckeditor/ckeditor5-engine#1540]
If edit area only an image,
can’t enter text below image.
this is a bug?

<img width="1015" alt="wx20180912-151231 2x" src="https://user-images.githubusercontent.com/1620172/45408296-8955f500-b69e-11e8-811d-5f28aae7779d.png">

**Comment by ma2ciek** [comment]
Hi, @wenmingtang!

For now, you need to press <kbd>enter</kbd> to create a paragraph after the widget and press <kbd>shift</kbd> + <kbd>enter</kbd> to create a paragraph before the widget.

**Comment by ma2ciek** [comment]
There's a whole topic about this functionality - https://github.com/ckeditor/ckeditor5/issues/407

**Comment by scofalik** [comment]
I'll just add a quick note that this is just a temporary solution and we will be working on something better.
