### ISSUE TITLE
Markers created by a data pipeline are not marked as affectsData

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#1583]
When marker is created as a result of the data pipeline conversion it should be marked as `affectsData` because is a part of the data.

**Comment by ma2ciek** [comment]
As far as I understand this problem, the issue is caused by the `Writer#insert()` method, which doesn't mark `DocumentFragment`'s markers as affecting data.

https://github.com/ckeditor/ckeditor5-engine/blob/master/src/model/writer.js#L198-L209

I'll check my assumption.

**Comment by oskarwrobel** [comment]
https://github.com/ckeditor/ckeditor5-engine/blob/master/src/model/writer.js#L207 looks like that's the place we need to change. I think we can assume that all markers that are created as a conversion result always affects data. At least for now.

**Comment by ma2ciek** [comment]
It can be reproduced by getting the content containing markers with `editor.getData()` and then setting it on the editor with `editor.setData()`.
