### ISSUE TITLE
Error during conversion of text inside element when specific attribute converters are defined for both elements

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-engine#1587]
Follow up of https://github.com/ckeditor/ckeditor5/issues/1317.

Considering conversions defined like:

```js
editor.conversion.for( 'downcast' ).add( downcastAttributeToElement( {
    model: {
        key: 'test',
        name: '$text'
    },
    view: ( value, writer ) => {
        return writer.createAttributeElement( 'span', { test: value } );
    }
} ) );

editor.conversion.for( 'downcast' ).add( downcastAttributeToAttribute( {
    model: 'test',
    view: 'test'
} ) );
```

and setting model data like:

```js
const root = editor.model.document.getRoot();
const p = writer.createElement( 'paragraph' );
const text = writer.createText( 'FooBar', { 'test': 3 } );

writer.insert( text, p );
writer.insert( p, root );
```

throws an `Cannot read property '_setAttribute' of undefined` error:

![image](https://user-images.githubusercontent.com/1061942/47723953-ea895600-dc55-11e8-9770-b67b0d650cb9.png)

Works fine if text is inserted into `root`, but when inserted as a child of `p` the error is thrown. The interesting thing is when generic conversion is removed from the example above:

```js
// editor.conversion.for( 'downcast' ).add( downcastAttributeToAttribute( {
//    model: 'test',
//    view: 'test'
// } ) );
```

everything starts to work fine.

**Comment by pomek** [comment]
If you disable the first converter:

```js
editor.conversion.for( 'downcast' ).add( downcastAttributeToElement( {
    model: {
        key: 'test',
        name: '$text'
    },
    view: ( value, writer ) => {
        return writer.createAttributeElement( 'span', { test: value } );
    }
} ) );
```

the error still occur. And it even make a sense because in the second converter:

```js
editor.conversion.for( 'downcast' ).add( downcastAttributeToAttribute( {
    model: 'test',
    view: 'test'
} ) );
```

we want to convert every `[test]` attribute in model to view. Text without any wrapper cannot have any attribute. 

When I changed a little the test scenario:

```js
editor.model.change( writer => {
	const root = editor.model.document.getRoot();
	const p = root.getChild( 0 );
	const text = writer.createText( 'FooBar', /*{ 'test': 3 }*/ );

	writer.setAttribute('test', 3, p);

	writer.insert( text, p );
} );
```

In the view I got: `<p test="3">FooBar</p>` so it works.

**Comment by scofalik** [comment]
Your converters are fine. It should work correctly, as you intended, so there is a bug somewhere. You shouldn't do anything like this:

> IMHO when text node is encountered, the generic converter should act the same way as "text specific" one - wrapping text in a span with an attribute applied.

First, I think that the "generic" (or let's say `attributeToAttribute` converter) should not do anything because `attributeToElement` converter should have already consumed the attribute.

**Comment by pomek** [comment]
Recently I talked with @scofalik about the bug. I checked which converters are executed during for the test scenario. I put a `console.log` between those lines https://github.com/ckeditor/ckeditor5-engine/blob/bafd6359441651a5a32a7673f1538dcb0cdcc1c4/src/conversion/modelconsumable.js#L164-L166 and I printed out the item and the type.

For such scenario:

```js
conversion.for( 'downcast' ).add( downcastAttributeToElement( {
	model: {
		key: 'test',
		name: '$text'
	},
	view: ( value, writer ) => {
		return writer.createAttributeElement( 'span', { test: value } );
	},
} ) );

conversion.for( 'downcast' ).add( downcastAttributeToAttribute( {
	model: 'test',
	view: 'test'
} ) );

model.change( writer => {
	const foo = writer.createText( 'FooBar', { test: 3 } );
	writer.insert( foo, modelRoot );
} );
```

Calls look:

![image](https://user-images.githubusercontent.com/2270764/48423052-2cd78a80-e760-11e8-840a-6d2ae333c3e1.png)

After removing the `aToA` converter, calls look:

![image](https://user-images.githubusercontent.com/2270764/48423632-4d541480-e761-11e8-894b-39c4967b49c9.png)

So it seems that the `aToA` converter is called for `DocumentSelection`. It sounds like an issue with an attribute that can be added for both nodes – for a text and an element.

**Comment by f1ames** [comment]
One more thing to clarify, the direct cause of the error is the fact that `changeAttribute()` function uses internally `conversionApi.mapper.toViewElement()` method, passing `Text` node (`TextProxy` object to be precise) and this method operates only on `Element`'s: https://github.com/ckeditor/ckeditor5-engine/blob/71c4c199d0fbe228a74efc272d00b13f522f36ad/src/conversion/mapper.js#L209-L217
