### ISSUE TITLE
Impossible to select an object element in some cases

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1593]
The case is https://github.com/ckeditor/ckeditor5/issues/1331.

It should be possible to make such a selection:

```html
<div>[<div></div>]</div>
```

because `div` is marked as `isObject` (all objects are selectable).

However, that does not work. The reason why it works in the demo I created in that ticket is because I accidentally added:

```js
	editor.model.schema.extend( '$text', {
		allowIn: 'div'
	} );
```

Which made this scenario fall into "selection is allowed in text" case.

**Comment by jodator** [comment]
Might be fixed by: https://github.com/ckeditor/ckeditor5-engine/pull/1608.

**Comment by jodator** [comment]
Yes. It does. https://github.com/ckeditor/ckeditor5-engine/pull/1608/commits/1d54e748b5c6d62f0be169ed2f9943030806bb64
