### ISSUE TITLE
Strip Tag Span

### ISSUE THREAD

**Issue by elvispdosreis** [ckeditor/ckeditor5-engine#1621]
How do I configure CKEditor not to remove span tags from my html code the editor is removing some html codes

**Comment by Mgsy** [comment]
Hi, please take a look at our [schema ](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#schema) and [conversion ](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#conversion)documentation for a better understanding of how CKEditor 5 works. After reading it, you should be able to solve your problem on your own.
