### ISSUE TITLE
Help LivePosition._createAt get out of the undocumented zone

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#1689]
As noted by @jodator, `LivePosition._createAt` "lives in the undocumented zone". It would be nice to document it, like the other static creators (`_createAfter`, `_createBefore`).

**Comment by scofalik** [comment]
Hmm, but there's one problem, AFAICS -- `_createAt` does not take `stickiness` argument. But it is also a problem for `Position._createAt`. So this should be fixed together.

**Comment by jodator** [comment]
I don't recall exactly how the works on refactoring that  part went but the `stickiness` should be at least for `_createAt()` and also for `model.createPositionAt()` as well as as `writer.createPositionAt()`.
