### ISSUE TITLE
If data is a single widget, the widget is automatically removed 

### ISSUE THREAD

**Issue by istanishev** [ckeditor/ckeditor5-engine#1690]
I've updated to v13.0.0 and noticed odd behavior in case the editor content contains a single non-editable widget. In this case the widget is completely removed automatically (possibly) by the dataDowncast and editor.getData() returns empty string. Putting a single char before/after the widget makes getData() to return correctly both the widget representation and the new character. Removing the additional char, makes getData() to return empty string again.

It works fine when downgrading to v12.0.0.

**Comment by istanishev** [comment]
It turns out that if I use editor.getData('main','none') it works fine. So it seems that my widget is considered "empty".

**Comment by Reinmar** [comment]
Hi! Is it marked in the schema as `isObject`?

I've just checked that the media widget works fine:

![image](https://user-images.githubusercontent.com/156149/53623822-7d370300-3bfe-11e9-99cb-60d6573564b3.png)

But if I remove `isObject` from its schema definition it is indeed considered as "not a content".

**Comment by istanishev** [comment]
Sorry for the late reply. I confirm that adding the isObject=true fixes this.
