### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by mariomeraz** [ckeditor/ckeditor5-engine#1695]
Install CDN version for BLOG and save data from ckeditor 5 and show in read blog section, no render video.

try YouTube and Vimeo

<img width="1667" alt="Captura de pantalla 2019-03-14 a la(s) 18 37 55" src="https://user-images.githubusercontent.com/14825814/54400507-bb193a00-4688-11e9-99e8-603f44d1f4cd.png">

Any idea? thks

**Comment by Mgsy** [comment]
Hello, please read our [media embed feature guide](https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#displaying-embedded-media-on-your-website). Here's a part about displaying media on the website. 

If you want the plugin to produce non-semantic output, just set this [config option](https://ckeditor.com/docs/ckeditor5/latest/api/module_media-embed_mediaembed-MediaEmbedConfig.html#member-previewsInData) to `true`.
