### ISSUE TITLE
Better insertion methods in DowncastWriter

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1724]
`DowncastWriter`:

```js
writer.insert( writer.createPositionAt( container, 'end' ), node );
```

`model.Writer`:

```js
writer.append( node );

writer.insert( node, container, 'end' );
```

I see two issues here:

1. The param order is different.
2. The API lacks the `append()` method and a nicer `node`+`positionSpecifier` version.

We can introduce `append()` easily. But in order to introduce `container, 'end'` support we need to change the order of the params. I think we are able to do that in a backward compatible way in this case. The question is, wouldn't we have to change it in 30 other methods too?

**Comment by pjasiun** [comment]
Creating these APIs we tried to make these them as similar as possible, so the different order of parameters is a bug in the API, and I am sure we should fix it.

**Comment by scofalik** [comment]
> Creating these APIs we tried to make these them as similar as possible

I remember making changes to unify the APIs (params order). I also remember there were some cases where there was no correct way to do it. So please make sure that there aren't other places in the code which would be "incompatible" then.

**Comment by Reinmar** [comment]
I surely agree that this is a bug. It somehow slipped when we were refactoring the API.

However, my biggest doubt is – can we actually make this change in a backward compatible way now? Answering that requires research. Also, we'll need to accept that the code will get more complex for a year or so (a period when we'll keep support for the legacy API). Or... we should batch this completely backward incompatible change with other such changes and make a major release again.

Anyway, let's do a research first. Adding to it24 so we'll track it.

PS. We could actually add `append()` without any fuss now, so that can be a part of this work in it24.

**Comment by scofalik** [comment]
We could wait with this change for when we will have more breaking changes and then release a major?

**Comment by Reinmar** [comment]
Closing as part of https://github.com/ckeditor/ckeditor5-engine/issues/1542
