### ISSUE TITLE
Calling DataController#toModel blows up the previous conversionApi

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1732]
I can't debug it now, but it's really strange that in a synchronous code `conversionApi.writer` is first correct (line 385) and then it's suddenly null in 404.

![image](https://user-images.githubusercontent.com/156149/56849772-3c572400-68f9-11e9-953b-285b5351d4e8.png)

I guess this is the mechanism which prevents from doing changes outside the change block or something. But it's a bit strange that it kicks in here, although I know that I tried to do a pretty unconventional thing (calling `toModel()` during another element's conversion).

**Comment by Reinmar** [comment]
It works fine when I used `conversionApi.convertChildren()` like this:

```js

		for ( const slotName of Object.keys( viewSlots ) ) {
			// Ideally, every slot should have different element name so we can configure schema differently for them.
			const slotContainer = conversionApi.writer.createElement( 'blockSlot', { slotName } );

			conversionApi.writer.append( slotContainer, modelElement );

			conversionApi.convertChildren( viewSlots[ slotName ], conversionApi.writer.createPositionAt( slotContainer, 0 ) );
		}
```

Still, I wanted to verify it with you guys that the disappearing `conversionApi.writer` isn't something that we could improve.

**Comment by oskarwrobel** [comment]
Interesting problem.

**Comment by scofalik** [comment]
But why it disappears? It shouldn't. It has to be debugged, looks like a bug. Unless you have some ZWS in your code 😂

**Comment by oskarwrobel** [comment]
It disappears because `DataController#toModel` calls `UpcastDispatcher#convert` in the middle of the pending conversion. At the end of conversion called by `DataController#toModel` conversion API is cleaned up https://github.com/ckeditor/ckeditor5-engine/blob/42dcb25a6dc2cd13b7ce7042a7ca89ef023bf92a/src/conversion/upcastdispatcher.js#L203

The current implementation does not allow for calling one conversion while another is pending.

**Comment by scofalik** [comment]
Thanks for debugging this. I didn't look precisely but indeed, calling `.toModel` in the middle of conversion is not correct.

**Comment by Reinmar** [comment]
OK. I agree that it's invalid. However, it'd be good to secure the API from such invalid use of it.

OTOH, I think that triggering a conversion while converting something else is not a very common problem, so I'm closing this ticket.
