### ISSUE TITLE
There's a chicken-egg problem with model's `Node` API

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-engine#1752]
For some time I've tried to use proper `Node` or `Element` links in the docs based on the API. But today I've discovered that those classes have also identity problems.

So I don't understand why do `Node` knows about `Element` instances.

Basically the:
- `node.parent` (refers to `Element`)
- `node.nextSibling` / `node.prevSibling`
- `node.root`
- `node.document`
- `node.isBefore()` / `node.isAfter()`
- `node._remove()`

refers to `Element`-like API (the parent/children references) and maybe it would be nicer to move them around? I was reading both classes description shortly and probably there was some rationale behind `Node` vs `Element` API but I feel bad about parent class `Node` using child class `Element` and it's API. Also there's a lot of confusion when to document `Element` and when `Node`.

**Comment by scofalik** [comment]
It's pretty simple actually :).

`Node` is a primary block, building the model tree. `Element` is a `Node` that may have children. This is the difference. Neither of the methods you quoted operates on children (of `node`), so I don't understand where your confusion comes from. You should not combine parent/children references together, it's not the same "category". Every node can have a parent, but not every node can have children.

You use / document `Element` when you specifically mean something that can have children. Use `Text` when you know that you operate only on texts. Use `Node` when it is not clear / it can be both / it does not make a difference.

Right now, there are only two classes that inherit from `Node`, while the `Node` itself, AFAIR, is abstract thing. It's `Element` and `Text`. I could imagine that we may have some other tree-model building entity in the future (something to represent empty inline elements, like an emoji or something?) but there wasn't need for something like that yet.

**Comment by Reinmar** [comment]
There's actually one problem here. Usually, we say – program for an interface, not an implementation. The type of the `nextNode()` is `Node` cause, of course, it is a node. And that's fine.

So, could `parent` be `Node`? Yes. So why isn't it? Because in our degraded composite-like pattern implementation it's always an `Element`... or `DocumentFragment` which isn't a `Node` :D

So, yeah, we could perhaps iron this out. But do we really have a problem? Until we'll use TypeScript, which would be the only way to actually check the types, we can only theoretise about this.

**Comment by scofalik** [comment]
> So, could `parent` be `Node`

But that's just incorrect. Not every `Node` can be a parent. `Node` do not have the correct API to be a parent. We could have an abstract `ParentNode` class if we want to by Java-y...

**Comment by jodator** [comment]
Not Javy but in general its a bit of incorrect to parent class have reference to child that's what I'm saying.

Reading this makes me feel that the `Node` / `Element` separation is not clear enough or simply artificial.

**Comment by scofalik** [comment]
I am a bit lost what is the problem.

1. Existence of `Node#parent` property?
2. `Node#parent` being documented as `Element`?
3. Writing about `Element`s in `Node`, in general, given that `Element` "needs" `Node` in the first place?

The separation might be artificial (I think it is not but you could always argue) but I think it is pretty clear - `Element` may have children.

**Comment by jodator** [comment]
The point `2` - there shouldn't be such relations IMO. It makes whole `Node`/`Element` seems artificial as `Node` needs `Element` class to work while `Element` is a child of a `Node`.

**Comment by scofalik** [comment]
Okay, I understand. I can agree to disagree. I understand your point of view. It's not a problem for me as the distinction is quite clear for me and I don't have a problem telling when I should reference `Node` and when I should reference `Element`. But I can see why you don't like it.

**Comment by Reinmar** [comment]
> It makes whole `Node`/`Element` seems artificial as `Node` needs `Element` class to work while `Element` is a child of a `Node`.

It's really typical for tree structures to have this issue. That, plus cyclic deps. All solutions I've ever seen to that seemed totally artificial. If you strive for better API, then what we did seems quite natural (at least to me).

BTW, in DOM, `parentNode` is a `Node`, but then they have to explain that it can only be one of `Element`, `DocumentFragment`, and so on.

BTW2, if we'd define that `parent` is a `Node`, then this would be incorrect:

```js
node.parent.name; // -> 'p'
```

Because `node.parent` is of type `Node` and only `Element` has `name` defined.

**Comment by Reinmar** [comment]
> Because `node.parent` is of type `Node` and only `Element` has `name` defined.

OTOH, it's incorrect now too, because `parent` can be `DocumentFragment` 🤦‍♀️. What a great example I chose :D

**Comment by Reinmar** [comment]
That's why I wrote that I'd wait with such things until we use TypeScript :) Otherwise, we'll be playing the role of type validators ourselves.

**Comment by jodator** [comment]
Anyway, that was a small WTF for me. Also, I think that we sometimes use `Node` in the docs while using `Element` methods/properties.

**Comment by pjasiun** [comment]
That the classic implementation of the [composition pattern](https://en.wikipedia.org/wiki/Composite_pattern). It does not get what's the problem with having node -> element and element -> node references. BTW, see https://medium.com/content-uneditable/circular-dependencies-in-javascript-a-k-a-coding-is-not-a-rock-paper-scissors-game-9c2a9eccd4bc
