### ISSUE TITLE
Upcast converter for element:* gets data.modelRange == null 

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1773]
When talking about upcasting, if you try to convert an element's attribute you need to listen to `element:*` event (there's no dedicated event for attribute conversion). Unfortunately, if you'd try this way:

```js
editor.conversion.for( 'upcast' ).add( dispatcher => {
	dispatcher.on( 'element:p', ( evt, data, conversionApi ) => {
		console.log( data.modelRange );
		console.log( Array.from( data.modelCursor.root.getChildren() ) );
	} );
} );
```

You can get `data.modelRange == null` and the model tree to which you convert (second `console.log()`) may not have the element that's being converted yet. In this specific case above this will happen if you add this converter before the `Paragraph` and `Heading` plugins are loaded. That's because in this scenario your listener will be executed before the `Paragraph`'s element converter.

The solution is simple and is actually what all our converters added e.g. with `attributeToAttribute()` do – they use `priority: 'low'`:

```js
editor.conversion.for( 'upcast' ).add( dispatcher => {
	dispatcher.on( 'element:p', ( evt, data, conversionApi ) => {
		console.log( data.modelRange );
		console.log( Array.from( data.modelCursor.root.getChildren() ) );
	}, { priority: 'low' } );
} );
```

This way, no matter how early you'll add your callback, it will always be executed after the default priority element converter from e.g. `Paragraph` feature.

The above needs to be documented.

**Comment by Reinmar** [comment]
I checked `upcasthelpers.js` and a complete attribute to attribute converter is actually more complex than I thought. It goes like this:

```js

editor.conversion.for( 'upcast' ).add( dispatcher => {
	dispatcher.on( 'element', ( evt, data, conversionApi ) => {
		const { consumable, schema, writer } = conversionApi;

		if ( !consumable.consume( data.viewItem, { style: 'font-size' } ) ) {
			return;
		}

		// Edge case: the view element might not have been converted to any model element
		// (e.g. because it's not allowed in this place). However, its children may be converted
		// to something which can have the `fontSize` attribute (e.g. due to autoparagraphin).
		// But children conversion was not triggered yet (it happens after attribute conversion)
		// so you need to trigger it manually here.
		if ( !data.modelRange ) {
			// Convert children and set conversion result as a current data.
			data = Object.assign( data, conversionApi.convertChildren( data.viewItem, data.modelCursor ) );
		}

		const fontSize = data.viewItem.getStyle( 'font-size' );

		// Don't go for the model element after data.modelCursor because it might happen
		// that a single view element was converted to multiple model elements. Get all of them.
		for ( const item of data.modelRange.getItems( { shallow: true } ) ) {
			if ( schema.checkAttribute( item, 'fontSize' ) ) {
				writer.setAttribute( 'fontSize', fontSize, item );
			}
		}
	}, { priority: 'low' } );
} );
```

I'll document a simpler case, though – without that ugly `data.modelRange` edge case.

**Comment by thiberaw** [comment]
Just a simple thought and information that might/should be added in the documentation:
If you clone a build (e.g. _ckeditor5-build-decoupled-document_) plugins declaration in the _builtinPlugins_ array must not be changed.

For example, do not sort it alphabetically. If you do so, you won't have the same result with a given html provided to the editor through _editor.setData_.

There should be a declaration order defined in the documentation for those who want to start with a custom build.
