### ISSUE TITLE
TreeModel to TreeView conversion controller

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#179]
- Converter will listen on the change event on the Tree Model and modify Tree View using Writer class (https://github.com/ckeditor/ckeditor5-core/issues/164).

- It will be configurable, by callbacks fired for every converted item (element, text, attribute).

- Whole text with the same attribute will be a single converted item ("f" ( bold ), "o" ( bold ), "o" ( bold ), "b", "a", "r" will fire two text conversion events: one for "foo" and one for "bar").

- Callbacks can be assigned to the specific item types, because of the performance.

- It will be possible to register generic callback, called every time.

- Callbacks will have priorities.

- User will be able to set the position for the next converter callback (mess the document, and said where the conversion cursor should be put), by default the cursor will be moved to the next position.

- Each step will have a list of items to consume (text, element, attributes), and methods:
   - `consume` - will remove item from that list,
   - `isConsumed` - check if the item has been consumed.

- The list of items to consume will shrink, not grow, because we would end up with the whole list next to each item at the end of the conversion. We could initialise the list when it is used for the first time on each item.

- Generic attribute may be consumed by the specific converter, for example image converter may consume bold attribute on the image, so we will have `<img class="bold">` instead of `<b><img></b>`

- There will be tool to create basic converter (e.g. attribute converter).

**Comment by pjasiun** [comment]
During the F2F discussion with @scofalik we realised that the whole time we were thinking only about the insertion conversion, but the Model to View conversion controller needs to be able to convert all types on change (https://github.com/ckeditor/ckeditor5-core/blob/master/src/treemodel/document.js#L200-L206):
 - insert,
 - move,
 - remove,
 - add attribute,
 - remove attribute,
 - change attribute.

It might be tricky to map the range end positions on the remove event, because it will be fired after the range was removed (so the content is moved to the graveyard). Fortunately, all operations, besides attributes operations, operate only on the flat ranges, so we will be able to get the length of the removed content and calculate the end position before the remove.

**Comment by scofalik** [comment]
* Will add and remove attribute be handled by default / utils converters / convert-factories (you know, those `.registerAttributeConverter( attrName, callback )`)?
* Is converting for `move` necessary? It will be just position mapping and moving stuff in TreeView so I guess there will be one default function for this in `ConversionController` / `TreeController`? If someone wants to do something special when some nodes are moved they could listen to `change` event, so I don't think we need to worry about this conversion
* same for `remove` but as you said this will be a little bit tricker

**Comment by pjasiun** [comment]
> Will add and remove attribute be handled by default / utils converters / convert-factories (you know, those .registerAttributeConverter( attrName, callback ))?

I think that `registerAttributeConverter` will be a helper to do such conversion. It will be possible to execute any action, but `registerAttributeConverter` will handle most popular task which is wrapping an element.

> Is converting for move necessary? It will be just position mapping and moving stuff in TreeView so I guess there will be one default function for this in ConversionController / TreeController? If someone wants to do something special when some nodes are moved they could listen to change event, so I don't think we need to worry about this conversion
> same for remove but as you said this will be a little bit tricker

Somehow the `move` and `remove` should be applied on the `TreeView`, so some kind of the conversion controller is needed. I do not think it will be configurable at first, so it will be a fixed function, at least at the begging.

**Comment by pjasiun** [comment]
This is how converters would look like without helpers. Some improvement, like parameters grouping, is needed. Also position mapping cache might be introduced to store new positions returned from the writer. But I need to say I like how simple they are right now. What do you think?

```js
// Insert -> insert element

modelToView.on( 'insert:element:img', ( writer, modelPosition, modelNode, consume, mapper, mapper ) => {
	if( consume( modelNode, 'insert' ) ) {
		const viewPosition = mapper.toViewPosition( modelPosition );
		const viewNode = new ViewElement( 'img' );
		mapper.bind( modelNode, viewNode );
		writer.insert( viewPosition, viewNode );
	}
} );

// Insert -> insert element with attribute

modelToView.on( 'insert:element:img', ( writer, modelPosition, modelNode, consume, mapper ) => {
	if( consume( [ [ modelNode, 'insert' ], [ modelNode, 'attribute:add:src' ] ] ) ) { // Consume both or none.
		const viewPosition = mapper.toViewPosition( modelPosition );
		const viewNode = new ViewElement( 'img', { 'src': modelNode.getAttribute( 'src' ) } );
		mapper.bind( modelNode, viewNode );
		writer.insert( viewPosition, viewNode );
	}
} );


// Insert -> insert element with attribute if exists

modelToView.on( 'insert:element:img', ( writer, modelPosition, modelNode, consume, mapper ) => {
	consume( modelNode, 'insert' );
	const viewNode = new ViewElement( 'img' );

	if( consume( modelNode, 'attribute:add:src' ) ) {
		viewNode.setAttribute( 'src', modelNode.getAttribute( 'src' ) );
	}

	const viewPosition = mapper.toViewPosition( modelPosition );		
	mapper.bind( modelNode, viewNode );
	writer.insert( viewPosition, viewNode );
	}
} );

// Insert -> insert text

modelToView.on( 'insert:text', ( writer, modelPosition, modelText, consume, mapper ) => {
	if( consume( modelNode, 'insert' ) ) {
		const viewPosition = mapper.toViewPosition( modelPosition );
		const viewNode = new ViewText( modelText.data );
		writer.insert( viewPosition, viewNode );
	}
} );
 
// Insert -> insert structure with mapping

modelToView.on( 'insert:element:widget', ( writer, modelPosition, modelNode, consume, mapper ) => {
	if( consume( [ modelNode, 'insert' ], [ modelNode.child, 'insert' ] ) ) {
		const viewPosition = mapper.toViewPosition( modelPosition );
		
		const mask = new ViewElement( 'div', { 'class', 'mask' } );
		const caption = new ViewElement( 'div', { 'class', 'mask' } );
		const viewNode = new ViewElement( 'div', { 'data', 'widget' }, [ mask, caption ] );

		mapper.bind( modelNode, viewNode );
		mapper.bind( modelNode.child, caption );

		writer.insert( viewPosition, viewNode );
	}
} );

// Attribute -> wrap
modelToView.on( 'attribute:add:bold', ( writer, modelRange, modelItem, attributeKey, attributeValue, consume, mapper ) => {
	if( consume( modelItem, 'attribute:add:bold' ) ) {
		const viewRange = mapper.toViewRange( modelRange );
		const viewNode = new ViewElement( 'b' );
		const priority = 7;

		writer.wrap( viewRange, viewNode, priority );
	}
} );


// Attribute -> attribute

modelToView.on( 'attribute:change:alt', ( writer, modelRange, modelItem, attributeKey, attributeValue, consume, mapper ) => {
	if( consume( modelItem, 'attribute:add:alt' ) ) {
		const modelItem = mapper.toViewElement( modelItem );
		modelItem.setAttribute( 'alt', attributeValue );
	}
} );

// Attribute -> changing element type

modelToView.on( 'attribute:change:type', ( writer, modelRange, modelItem, attributeKey, attributeValue, consume, mapper ) => {
	if( modelItem.getAttribute( type ) === 'caption' && consume( modelItem, 'insert' ) ) {
		const oldElement = mapper.toViewElement( modelItem );
		const viewPosition = mapper.toViewPosition( modelRange.start );
		
		oldElement.remove();
		const newViewElement = new ViewElement( 'img' );

		mapper.bind( modelItem, newViewElement );
		writer.insert( viewPosition, viewNode );
	}
} );

```

**Comment by pjasiun** [comment]
And the last puzzle here is caching. On the one hand recalculating the position for every wrap would be pity. The standard case is inserting text with some attributes. It will be handled by the separate `insert` and multiple `wrap` (after the long talk we agreed it will be the best way). Each of these will change the position, but each of these is able to return the new position faster then recalculating it.

For example when we insert `bar` with `bold` and `underline` attributes, at the end of 
`<b><u>foo</u></b>`
it will be handled in 3 steps:
`<b><u>foo</u></b>bar` (insert)
`<b><u>foo</u>bar</b>` (wrap)
`<b><u>foobar</u></b>` (wrap)

Since moving it should not be a big deal, recalculating the position before `bar` would be expensive.

On the other hand caching is pure evil. Forcing converters to update position would make the API much more complicated and impossible in more complex cases. Even forcing developers to clear the cache for every custom case would looks bad.

The solution could be cleaning cache if it is not used. We could use the proxy pattern. `mapper` variable can be a `CachedMapper` which is a child of the `Mapper` class. All mapping methods (`toViewElement`, `toViewRange`, `toViewPosition`) will be able to take a second parameter, which is a boolean `useCache`. If it is undefined `cache` is cleaned. It means that for custom changes there is no need to take care.

But. When the second parameter is true, it means that the cached value is returned (if is available), cache is not cleaned and the developer know what he is doing, so he will update positions after the change. This way all helpers method will be implemented, so in the basic conversion positions will be reused.

I practice `modelToView.insert( 'img', () => new ViewElement( 'img' ) );` will do:
```js
modelToView.on( 'insert:element:img', ( writer, modelPosition, modelNode, consume, mapper ) => {
    if( consume( modelNode, 'insert' ) ) {
        const viewPosition = mapper.toViewPosition( modelPosition, true ); // use cache
        const viewNode = new ViewElement( 'img' );
        mapper.bind( modelNode, viewNode );
        const newViewPosition = writer.insert( viewPosition, viewNode );
        mapper.update( viewPosition, newViewPosition ); // update cache
    }
} );
```

Or `modelToView.wrap( 'src', () => new ViewElement( 'b' ), 7 );` will do:
```js
modelToView.on( 'attribute:add:bold', ( writer, modelRange, modelItem, attributeKey, attributeValue, consume, mapper ) => {
    if( consume( modelItem, 'attribute:add:bold' ) ) {
        const viewRange = mapper.toViewRange( modelRange, true ); // use cache
        const viewNode = new ViewElement( 'b' );
        const priority = 7;

        const newViewRange = writer.wrap( viewRange, viewNode, priority );
        mapper.update( viewRange.start, newViewRange.start ); // update cache
        mapper.update( viewRange.end, newViewRange.end );
    }
} );
```
At the same time all complex converters, like widget, can be unchanged. They will reset cache, what is fine. And, what is most important, we can implement such solution later.

**Comment by pjasiun** [comment]
For the `consume` method it takes the type of the change (note that we consume changes not elements) and the node, and:

 - if the change is on the list of changes to consume it consume the change and return `true`,
 - if the change have been already consumed return `false`,
 - if the change is not on the list of the consumable element it return `null`.

For example:
`consume( node, 'insert' );`
`consume( node, 'move' );`
`consume( node, 'attribute:add:bold' );`

It is also possible do pass the array of changes to consume. All or none of them will be consumed:
`consume( [ [ node, 'insert' ], [ node, 'attribute:add:src' ] );`

This should handle most of the cases. But because there are always cases we can not predict there will be two additional methods:
 - `consume.test( node, 'insert' );` will only check if it is possible to consume that change, without consuming it;
 - `consume.revert( node, 'insert' );` will mark the change as "unconsumed".

**Comment by pjasiun** [comment]
Also note that there is an update in the https://github.com/ckeditor/ckeditor5-core/issues/179#issuecomment-188820129 comment.

**Comment by scofalik** [comment]
Things I noticed reading your code snippets:
1. In third converter ` consume( data.node, 'insert' );` shoud be inside `if`
2.
```javascript
modelToView.insert( 'img', () => new ViewElement( 'img' ) );
modelToView.attribute( 'src', ( data ) => { 'src': data.value } );
```
Isn't exactly the same thing as example above, but I guess it's close enough. I guess it could be easily fixed if needed.
3. `const viewNode = new ViewText( modelText.data );` where the `modelText` come from? :)
4. Insert -> insert structure with mapping: I understand that we always look through changes from the top of tree to the bottom? So children will be already consumed? Anyway I am afraid that those widgets converters are a bit complicated :( Couldn't we create them using some helpers, too?
5. `    if( consume( data.item, 'attribute:add:bold' ) ) {` what is the difference between `data.node` and `data.item`?
6. `modelToView.wrap( 'src', () => new ViewElement( 'b' ), 7 );` this probably should be `'bold'` and `'strong'` right?

I like the converters and helper functions. Will `modelToView.wrap( 'src', () => new ViewElement( 'b' ), 7 );` also handle attribute removing or changing? It would be nice if it did. I see that what we previously called `tag` consumable, is now split between `insert` or `move`. I am worried that we will need to declare more converters than needed.
For `.wrap` I propose `.inline()` which would handle all types of changes connected with (mostly) changes on inline styles
For `.insert` or `.move` I propose `.element()` which will handle inserting, moving and removing of element.
`.attribute` may stay as it is but let's be sure that it does adding, changing and removing properly.

The thing is that if I want my `myElement` in tree model be just resolved to `<div class="myElement">` it should be doable in one line of code, no matter if I add it to Tree Model, change it's position in Tree Model or remove it from Tree Model.

I am not sure about consumables names. A list of what is possible and how it behaves would be nice.

I like the idea with caching.

**Comment by pjasiun** [comment]
> Things I noticed reading your code snippets:
> 1. In third converter consume( data.node, 'insert' ); shoud be inside if

I am not sure which version is the right one. Because of the performance, the event should be canceled when the action is consumed. It means that if `insert:element:img` event had been fired, the `insert` can be consumed and we do not need to check it.

> 2.
> 
> `modelToView.insert( 'img', () => new ViewElement( 'img' ) );`
> `modelToView.attribute( 'src', ( data ) => { 'src': data.value } );`
> Isn't exactly the same thing as example above, but I guess it's close enough. I guess it could be easily fixed if needed.

That's true. It should be:
```
modelToView.insert( 'img', () => new ViewElement( 'img' ) );
modelToView.attribute( 'src', ( data ) => data.node.name == 'img' ? { 'src': data.attributeValue } : null );
```

> 3. const viewNode = new ViewText( modelText.data ); where the modelText come from? :)

It was a bug. I have fixed it.

> 4. Insert -> insert structure with mapping: I understand that we always look through changes from the top of tree to the bottom? So children will be already consumed?

Yep.

Anyway I am afraid that those widgets converters are a bit complicated :( Couldn't we create them using some helpers, too?

I think that widgets feature will handle it. Widget may have a helper to create whole structure, drag handler, mask, attach all listener etc.. It is not only the matter of converter.

Also I do not think that we should create a helper for every case. This is a good example, because when I started to thinking about the helper for this case it was looking like: 

```
modelToView.insert( 'widget', () => new ViewElement( 'div', { 'data', 'widget' }, [ 
		new ViewElement( 'div', { 'class', 'mask' } ),
		new ViewElement( 'div', { 'class', 'caption' } )
	] ), [ 0, 'insert' ], // what to additionally consume
	[ [ [ 0 ], [ 0 ] ], [ [ 0, 0 ], [ 0, 2 ] ] ], // mapping
);
```

For such cases I prefer the longer version when one case more-less understand what is going on.

> 5. if( consume( data.item, 'attribute:add:bold' ) ) { what is the difference between data.node and data.item?

`Item` is `Node` or `TextFragment`.

> 6. modelToView.wrap( 'src', () => new ViewElement( 'b' ), 7 ); this probably should be 'bold' and 'strong' right?
> 

Fixed.

> I like the converters and helper functions. Will modelToView.wrap( 'src', () => new ViewElement( 'b' ), 7 ); also handle attribute removing or changing? It would be nice if it did. I see that what we previously called tag consumable, is now split between insert or move. I am worried that we will need to declare more converters than needed.

Wrap helper can create converters for both wrapping and unwrapping. 

But for the `move` and `remove` it is not insert which will handle it. Move and remove can be handled by the generic converter, it is the same action, regardless of the type of the element. If the element is moved, the corresponding element in the tree view should be moved. For some specific cases, specific `move` or `remove` converters may be created, but for the generic purpose there is no need to create anything more then `insert`, which can not be generic.

> For .wrap I propose .inline() which would handle all types of changes connected with (mostly) changes on inline styles

`inline` does not sounds good since we call inline element `attribute`, not `inline` in the `Writer`.

> For .insert or .move I propose .element() which will handle inserting, moving and removing of element.

We do not convert items. We convert actions. Because `move` and `remove` will be handled by the global converter (see comment above) calling `insert` converter `element` may be confusing.

> .attribute may stay as it is but let's be sure that it does adding, changing and removing properly.
> 
> The thing is that if I want my myElement in tree model be just resolved to <div class="myElement"> it should be doable in one line of code, no matter if I add it to Tree Model, change it's position in Tree Model or remove it from Tree Model.
> 
> I am not sure about consumables names. A list of what is possible and how it behaves would be nice.

Names for events will be:

For structure:
`(insert|move|remove):(element|text):[p|div|...]`
For example: `insert:text`, `move:element:p`.
For consumables we do not need second and third part, because it can be taken from the node so we pass only the first: `consume( node, 'insert' )`

For attributes:
`attribute:(add|remove|change):[bold|link|...]`
For example: `attribute:add:bold`, `attribute:change:link`.
For consumables, in this case we need all three parts, for example`consume( node, `attribute:add:bold )`, `consume( node, `attribute:change:link )`

> 
> I like the idea with caching.

:+1:

**Comment by pjasiun** [comment]
In the F2F discussion we decided to rename events to more meaning full:
```
insertItem:(element|text):[p|div|...]
moveItem:(element|text):[p|div|...]
removeItem:(element|text):[p|div|...]
addAttribute:[bold|link|...]
removeAttribute:[bold|link|...]
changeAttribute:[bold|link|...]
```

**Comment by pjasiun** [comment]
A also updated samples code.
