### ISSUE TITLE
Mark tests that are valid only for browser environment.

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-engine#212]
After completing issue [#84](https://github.com/ckeditor/ckeditor5/issues/84) from `ckeditor5` repository we need to mark tests that are not valid for Node.js environment ( for example using browser DOM API ). This can be achieved by adding `browser-only` tag to `bender-tags:` comment in test file.

**Comment by Reinmar** [comment]
For now there will be a lot of these tests, even for basic classes like the Editor. We'll need to work on this to remove those hard dependencies on the browser env from some of these classes.
