### ISSUE TITLE
treeModel.Item class as a base for Node and TextFragment

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#223]
`TextFragment` is not a `Node`, it can not be a child of the `Element`, but it share a big part of the interface with `Node`. It would be useful to have a common interface with properties and methods like `length`, `parent`, `hasAttribute`, `getAttribute`, `getAttributes`. This base class may even not implement any methods, since all methods on the `TextFragment` works different then on the `Node`, but it could define these methods, so the API would looks simpler.

Then, to get the position after the item during iteration I could do: 

`positionAfter = previousPosition.getShifterBy( item.length )`,

then current:

`positionAfter = previousPosition.getShifterBy( item instanceOf Node ? 1 : item.text.length )`

**Comment by scofalik** [comment]
This issue is outdated. We already did engine refactoring and are fine with what we have. All classes in model now has similar interface and view classes also got refactored to be as similar to model classes as possible.
