### ISSUE TITLE
Implement Editing controller

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#288]
Strongly connected to https://github.com/ckeditor/ckeditor5/issues/116.

**Comment by Reinmar** [comment]
In #301 I introduced base classes, but the real implementation is yet to be defined.

**Comment by pjasiun** [comment]
I pushed data and editing controllers prototypes to the https://github.com/ckeditor/ckeditor5-engine/tree/t/288 branch (https://github.com/ckeditor/ckeditor5-engine/commit/43948aba7b330bedcb5b1fcfe2cb927929150a70).

**Comment by pjasiun** [comment]
Should solve also https://github.com/ckeditor/ckeditor5-engine/issues/292 "Define a list of observers which are always registered by the EditingController".

**Comment by pjasiun** [comment]
Also related: https://github.com/ckeditor/ckeditor5-engine/issues/369 View.Document as an entry point for the view editing state

**Comment by pjasiun** [comment]
Should also fix: https://github.com/ckeditor/ckeditor5-engine/issues/402 Siblings should be merged when inline filler is removed

**Comment by pjasiun** [comment]
Let's split it into two tickets.
