### ISSUE TITLE
Define a list of observers which are always registered by the EditingController

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#292]
It will be more useful if some of the most popular observers were always plugged. It doesn't make sense for every feature to register its focus observer, because it's clear that it will always be used.

The list so far:

* focus
* mutation
* key

PS. This needs to be reflected in the documentation of tree view events whether this event is available by default or not. Also, this task should cover removing existing observer of those types from other places in the code (including the ckeditor5 repo).

**Comment by pjasiun** [comment]
Selection

**Comment by Reinmar** [comment]
It's becoming more and more important now: https://github.com/ckeditor/ckeditor5-engine/pull/397#issuecomment-218501354

Perhaps this should be done in the editing controller that you're going to work on next, @pjasiun.

**Comment by pjasiun** [comment]
Yep, that's the plan.

**Comment by pjasiun** [comment]
Default observers have been introduced in https://github.com/ckeditor/ckeditor5-engine/pull/442. Documentation has been updated too.

Still `addObserver`, for default observers, should be removed from all places in the code which do not need it anymore.

**Comment by pjasiun** [comment]
I removed `addObserver` from other repos. The ticket can be closed.
