### ISSUE TITLE
Tests: Create a convenient utils to test features

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#306]
In order to test a feature we'll need a tools to:

- [x] 1. Compare data and selection in the model with an expected value,
- [x] 2. Set data and selection in the model to a specified value (needed to test algorithms operating on the model and converters to the view),
- ~~3. Test the history (undo/redo) if needed (?),~~
- [x] 4. Compare data and selection in the view with an expected value,
- [x] 5. Set data and selection in the view to a specified value (needed to test converters to the model),
- ~~6. Way to browse contents of the model and view (needed for manual tests),~~
- ~~7. Compare DOM to an HTML string (https://github.com/ckeditor/ckeditor5-utils/issues/19) (needed for example for testing view rendering).~~
- [x] 8. Extend the tools created in 1. so they can print any position which is passed (useful for debugging).
- [x] 9. Publish these utils in `console.dump()` so you don't need to import anything. Such module, implementing this API should be loaded by default in tests and on demand in other envs. This method could be smart to accept any `( model element || model doc frag || view element || view doc frag ) && ( position || selection || range )`.
- [ ] 10. Use `[` and `]` in model test utils and pass additional selection parameters in the separate object.
- [ ] 11. Use view testing tools with converters for model testing.
- [x] 12. Make `setData()` of the model utils work in the same way as you would expect loading data to editor (so data should be rendered) – #455.

**Comment by Reinmar** [comment]
Main question is about the format of the expected values.

* In the view we may use something similar like in CKEditor 4, so a well formatted HTML string.
* It would be good to find a nice string pattern for the model, but that may be much harder due to complexities and format of the model.

**Comment by Reinmar** [comment]
OK, this is a quick proposal for a format that we'll use to set and read data and selection from the model. WDYT?

Full:

```html
<p><bold value=true><selection />foo</bold>bar</p>
<p><bold value=true>foo</bold><selection />bar</p> (when the selection doesn't have the bold attr)
<p><bold value=true>fo</bold><selection /><bold value=true>o</bold>bar</p>
<p><bold value=true><selection backwards>foo</selection></bold>bar</p>
<p><link value=http://foo><linkTitle value=something><selection>fo</selection>o</linkTitle></link>bar</p>
```

Ignore attribute values:

```
<p><bold>foo</bold>bar</p>
<p><link><linkTitle><selection>fo</selection>o</linkTitle></link>bar</p>
```

Ignore whitespaces (only possible to implement in methods like `setData()` and `compareData()`):

```html
<p>
	<link><linkTitle>
		<selection>fo</selection>o
	</linkTitle></link>
	bar
</p>
```

Possible options:

* ignore whitespaces (so you can type using nicely formatted template strings),
* ignore text attrs,
* ignore attrs values,
* ignore selection,
* some entities encoding (nbsps, etc.)

Notes:

* Due to the format of these HTML strings some characters will break the theoretical validity. E.g. a `"` or `<>` characters in attribute values will generate something that would be an incorrect HTML. The idea is that if you need to test such things, then these utils are not for you. Eventually, we can improve them in the future.
* It may be tricky to write selection as I proposed above. Matching selection attrs with text attrs to decide where and how to write selection will be challenging so I wonder if we could change something in the format to avoid that.
* Parsing the input in methods like `setData()` will need some very simple HTML parser. I think I'm gonna look for some or write it as we really don't need that much. Alternatively, I remember that we used something in the CKEditor 4 SDK builder that simplified HTML building in Node.js.

**Comment by pjasiun** [comment]
Do we want to merge siblings attributes (`<b>foo<u>bar</u></b>` instead of `<b>foo</b><b><u>bar</u></b>`)? If not I see no reason to merge selection. If we want to do it, we could try to use `treeView.Writer`. It should to all of the job for us.

**Comment by scofalik** [comment]
For starters, I don't like that attributes looks like elements. For sure these should look different. Then, you haven't proposed how attributes would look like on elements. Finally, I am not sure whether we want have two ways of representing selection. I guess that `<selection></selection>` will be fine for collapsed selection.

```html
<p paragraphAttribute="attrValue">foo</p>
<_attr bold="true">attribute bold on text</_attr>
```

**Comment by pjasiun** [comment]
Yep, agree with @scofalik.

**Comment by oleq** [comment]
@scofalik :+1:. What if we used namespace to make it clear? Like

```xml
<p><attr:bold value=true><selection />foo</attr:bold>bar</p>
```

Also: do we care about where the selection belongs at this stage?

```xml
<p><bold value=true><selection />foo</bold>bar</p>
```

Is this selection attached to "foo", offset 0 or to `<bold>` (`<p>`?) offset 0? Does it matter in the model anyway?

**Comment by scofalik** [comment]
It does not matter in the model. In the model the selection is at the position before "f" letter. (so in `<p>`, offset 0).

**Comment by Reinmar** [comment]
> Do we want to merge siblings attributes (<b>foo<u>bar</u></b> instead of <b>foo</b><b><u>bar</u></b>)? If not I see no reason to merge selection. If we want to do it, we could try to use treeView.Writer. It should do all the work for us.

Right. We should not merge attributes, because that will complicate the tool dramatically.

> `<$text bold="true">attribute bold on text</$text>`

I like this. It's matching how we define text in the schema and shows that one piece of text may have only one set of attributes. Remaining question is what if the text doesn't have any attribute. Should it be wrapped with `<$text>`? I'm for no.

> Also link will be a one attribute with value being an object with multiple properties, how do you want to handle it? I don't think that this example shows it.

Perhaps, but perhaps there will be a link attribute and a separate linkTitle, linkTarget, etc attributes for other features. My examples were showing this case - sorry for the confusion.

If an attribute will be a key-value set, it will be printed as JSON:

```html
<image value={"src":"foo","alt":"bar"} />
```

> I guess that <selection></selection> will be fine for collapsed selection.

I think that if we can write `<selection />` (which makes total sense in HTML) then why not. It's shorter.

**Comment by pjasiun** [comment]
> Should it be wrapped with <$text>? I'm for no.

+1

> Perhaps, but perhaps there will be a link attribute and a separate linkTitle, linkTarget

Some time ago we agreed that this would be a better solution, because you will be able to consume them separately. But we could have objects as attributes values anyway.

**Comment by scofalik** [comment]
Okay, I agree. I didn't know that we switched our idea on link attribute :)

**Comment by Reinmar** [comment]
As for testing the tree view - a good example of what we need to cover can be found in https://github.com/ckeditor/ckeditor5-engine/blob/master/tests/treeview/writer/insert.js (and other writer tests).

**Comment by Reinmar** [comment]
I'm implementing now a very simplified version of `getData( document )` using some very basic techniques like the tree walker and not caring about some edge cases.

However, once we'll have the converters in place, we'll be able to approach this using the conversion mechanims to convert model to the tree view and then using the function writing tree view to a string (which is on our list as well) convert that structure to a string. This will be much simpler implementation and a nice test for the conversion mechanism. But let's work on this in the future when all pieces are in place.

**Comment by Reinmar** [comment]
I got the first method working (see https://github.com/ckeditor/ckeditor5-engine/commit/54bbf741f4a17a8054f98ed968b0473a26ed842f). Now switching to setData() which sounds easier.

**Comment by Reinmar** [comment]
I added one more tool which would be very useful:

> 8. Extend the tools created in 1. so they can print any position which is passed (useful for debugging).

**Comment by pjasiun** [comment]
For the view we could have tools similar to CKEditor 4 tools:
```
<p><b>[foo]</b>bar</p> // Range in the element
<p><b>{foo}</b>bar</p> // Range in the text
<p><b>foo^</b>bar</p> // Collapsed range
<p><b>[f}oo</b>ba{r]</p> // Multiple ranges
```
Also there should be a config option to add information about the type of the element:
```
<container:p><attribute:b>[foo]</attribute:b>bar</container:p>
```
And about priorities:
```
<container:p><attribute:b priority=15>[foo]</attribute:b>bar</container:p>
```
Default priority could be hidden by default.

**Comment by Reinmar** [comment]
We also need to be able to define order of selection ranges and direction of the last range. That can be done as additional arguments (order of ranges can be a string like `'312' ` (first range in the pattern is really the third one in the selection, second is first and last is second).

**Comment by pjasiun** [comment]
We also talked that we could show selection in the similar way in the model, to make data more readable:
```
<p><bold value=true>foo^</bold>bar</p>
```
And have a separate method to get/compare selection attribute and additional data.

**Comment by Reinmar** [comment]
PS. As for support for multiple ranges – that won't be necessary for a couple of months, so you don't need to implement that. My model methods do not support this as well.

**Comment by Reinmar** [comment]
I added point 9 to the list. While implementing features it's really hard to debug your code because inspecting elements, positions, etc. is tiresome and just takes a lot of time:

> Publish these utils in `console.dump()` so you don't need to import anything. Such module, implementing this API should be loaded by default in tests and on demand in other envs. This method could be smart to accept any `( model element || model doc frag || view element || view doc frag ) && ( position || selection || range )`.

**Comment by pjasiun** [comment]
Related: https://github.com/ckeditor/ckeditor5-engine/issues/412.

**Comment by pjasiun** [comment]
The `<selection />` tag in the model output is too long. In many cases we do not care about selection attributes and direction. We could use `[` and `]` the same way we define ranges in the view tests:
```
<p><attr:bold value=true>[]foo</attr:bold>bar</p>
```
Then you can pass selection order or attributes in the option parameter.

**Comment by pjasiun** [comment]
Also we could use converters and view testing tools for the model testing tools. Thanks to it we would have merged attributes (by writer). Also code should be smaller and we would not have to support our own XML parser for tests. 

All we need to add is a generic converter which will convert any element to container element, any attribute to attribute element and converter selection to text nodes (`[` and `]`). Then use view test tools to stringify it.

Loading data should works similar way.

This would be also a nice test for converter.

**Comment by pjasiun** [comment]
Two related tickets: https://github.com/ckeditor/ckeditor5-engine/issues/441, https://github.com/ckeditor/ckeditor5-engine/issues/433.

**Comment by Reinmar** [comment]
Another related ticket: #455.

**Comment by pjasiun** [comment]
We decided we do not need

> 3 Test the history (undo/redo) if needed (?),

and

> 7 Compare DOM to an HTML string (ckeditor/ckeditor5-utils#19) (needed for example for testing view rendering).

for now.

Also:

> 6. Way to browse contents of the model and view (needed for manual tests).

is handled be a separate ticket (https://github.com/ckeditor/ckeditor5-engine/issues/170). 

It means that to close this ticket we only need to update model testing tools (see 4 comments above).
