### ISSUE TITLE
Model to View Selection conversion

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#313]
There should be pluginable mechanism to convert selection form the model to the view.

It should fire events on 3 level:
 - 'selection' - for features which handle selection as a whole, like table column selection,
 - 'range' - for cases where range selection is something different then two positions, for example widget selection,
 - 'position' - for standard text selection.

Each event should have a list of consumable, as structure conversion have. It should be possible to consume each position as well as each attribute.

**Comment by pjasiun** [comment]
Cases to consider:
```
foo<b>^</b>bar
<b>foo</b>^<b>bar</b>
<b>foo^</b> // typing
<b><u>[foo</u></b><i>ba]r</i>
```

Cases for the future (does not need to be handled now, but to keep in mind):

 - Table column selection:
```
<table>
	<tr>[<td></td>]<td></td><td></td></tr>
	<tr>[<td></td>]<td></td><td></td></tr>
	<tr>[<td></td>]<td></td><td></td></tr>
</table>
```
 - Markdown editor (``` `` ``` are displayed but does not have model representation, so the information if the selection is ``` ^`` ```, ``` `^` ``` or ``` ``^ ``` is kept in the selection attribute):
```
<span>`^`<strong>test</strong>``</span>
<span>`[`<strong>test</strong>`]`</span>
```

**Comment by scofalik** [comment]
Fix for #359 is needed for this issue. I'll work on it.

**Comment by pjasiun** [comment]
We talked about it and agreed that the solution should not be overengineered. Instead of 3 events (`selection`, `range` and `position`) we could have one: `selection` with additional events for selection attributes (`selection:bold`).

In fact, in basic cases, we need to handle selection attributes only if it is a collapsed selection. If the range is not collapsed we do not want to break any structure. Also then it is not that important to have selection in the proper attribute element cause we do not know anyway what was the users intention (`<b>f{oo</b>}bar` or `<b>f{oo}</b>bar`). What we can improve it mapper which should always put the position in the text node if there is text node right after or before the position.

Then we have more complex cases, but they can simple be handled in `selection` listeners. Widget selection listener can check if selection contains widget and add or remove special classes if needed. Table column selection should be handle as a whole anyway. Then there is a Markdown case (```<span>`[`<strong>test</strong>`]`</span>```), but note that the information where is the beginning and the end of the range is kept not per position, but as selection attributes. It means that again it makes sense to have a: `selection:markdownStart` and `selection:markdownEnd` then trying to fire `startPosition:markdown` and `endPosition:markdown` events somehow.

It is always doable to iterate over the ranges or positions in the `selection` listener, but if we fire separate even for each range it is more difficult to get the overall context. And note that we have selection attributes, not range attributes, so that overall context may be important. Lets keep it simple.

**Comment by pjasiun** [comment]
We could also rename the event to `selectionChange` because:
 - this is how view event is called,
 - model to view dispatcher handle changes, not structures.
