### ISSUE TITLE
View to Model Selection conversion

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#314]
Without the view to model selection converter we are able to map the position using the `Mapper`. However, mapped position does not contain attributes. It could be enough, since we are not able to find a case where we need to get selection with attributes from the DOM, but I believe that sooner or later such information will be important and we will need to be able to convert selection both ways.

**Comment by pjasiun** [comment]
The possible case is the position at the of the line. When user press the up key and move the caret to the end of the shorter line of the bolded text, the new position might be inside a `<b>` tag, or outside:

`<p><b>foo^</b></p>` or `<p><b>foo</b>^</p>`

Without the converter we get a only the position "3" without the information about the attribute. If we prefer the position inside, we will add the attribute from the last letter to the selection so it will be allways put inside a `<b>` tag.

Now, if the browser put the position natively outside the `<b>` we will move the selection and break the 'x' position so when user move the position back to the longer line it will not be put further then the end of the shorter line.

**Comment by scofalik** [comment]
I have to check whether this is not done already.
