### ISSUE TITLE
Selection research

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#315]
- Check order of the selection change and mutations observer event events.
 - Check if there is an information which key was pressed in keydown event on Android (https://bugs.chromium.org/p/chromium/issues/detail?id=118639, https://codereview.chromium.org/393933004).

**Comment by pjasiun** [comment]
> Check order of the selection change and mutations observer event events.

Selection change and mutations observer events are fired in different order depending on the browser.

On Firefox `selectionchange` is disabled by default and user need to change `dom.select_events.enabled` setting in the browser to enable it.

**Comment by Reinmar** [comment]
> On Firefox selectionchange is disabled by default and user need to change dom.select_events.enabled setting in the browser to enable it.

WAT? Do you mean that it's not fired by default? I see https://developer.mozilla.org/en-US/docs/Web/Events/selectionchange that unfortunately I understood you correctly ;/ That's a bad news for us.

**Comment by Reinmar** [comment]
I commented under https://bugzilla.mozilla.org/show_bug.cgi?id=571294#c57 to see if there's a chance for this flag being enabled by default sooner than later.

**Comment by pjasiun** [comment]
As for Android: it is possible to get enter `keyCode`, but not Backspace. The only hope is that https://bugs.chromium.org/p/chromium/issues/detail?id=227231#c80 will fix it.

**Comment by pjasiun** [comment]
On Safari @ iOS: the situation looks better. There is key code for backspace, enter, and any other key. There is no key event for arrows (see on the right of the screenshot), but there is an selection change event which is good enough.

![image](https://cloud.githubusercontent.com/assets/1166967/14321977/9be34f32-fc1b-11e5-889d-7d0ad3572777.png)

**Comment by pjasiun** [comment]
> Selection change and mutations observer events are fired in different order depending on the browser.

On most browsers, expect Safari (both desktop and mobile) the mutation event is before selection, what is good. Fortunately, on Safari we can use `takeRecords` to get mutations on selection change, so we can change the order of these events.

**Comment by pjasiun** [comment]
To sum up, I tested Chrome@Mac, Firefox@Mac, Safari@Mac, IE11@Win10, Edge@Win10, Chrome@Android, Safari@iOS.

There are 2 problems found:
 - no `selectionchange` on Firefox by default (https://bugzilla.mozilla.org/show_bug.cgi?id=571294#c57 ),
 - no key code on Chrome@Android for backspace key (https://bugs.chromium.org/p/chromium/issues/detail?id=227231#c80).

Both features may be fixed soon, so we should wait a while and see. All other events were fired as expected.

**Comment by pjasiun** [comment]
Because of the lack of the `selectionchange` on Firefox this might be usefull: https://github.com/2is10/selectionchange-polyfill
