### ISSUE TITLE
Selection should not end up in the graveyard

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#331]
Test:

``` html
f<selection>o</selection>o
```

``` js
batch.remove( selection.getFirstRange() );
```
- Expected: selection collapsed between `f^o`.
- Actual: selection in the graveyard.

**Comment by scofalik** [comment]
The question is whether this is `Selection` accountability or maybe other part of code should set it? It seems that `Selection` should take care of it, but let's think about it for a while.

**Comment by Reinmar** [comment]
I'd go for the selection handling this case for three reasons:

* We made the assumption that the selection is always in the document (so we implemented the default selection position). Graveyard is kinda outside of the document. It's hidden and it confused me where's my selection after the delta that I applied.
* I can't think of a case where one would like to have (move) a selection to the graveyard.
* There will be some logic needed to keep the selection in the root editable, so if we'll require that other features take care of this we'll have the logic scattered around and no DRY.
