### ISSUE TITLE
Mark placed where bogus should be put

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#338]
That's tricky. Now we simple put boguses in empty blocks, what works for now. But in the generic case we may want to have a boguses between:

 - beginning of  outer and inner blocks:
```
<div><br><div>foo</div></div>
```

 - between blocks:
```
<div>foo</div><br><div>bar</div>
```

 - ending of outer and inner blocks:
```
<div><div>foo</div><br></div>
```

All of these boguses has semantic meaning, they create an empty line allowing user to editor the content.

Now. We can said that the last case in not realistic.

The second case is inserting text between two `<hr>`:
```
<hr /><br><hr />
```

The first case is nested list:
```
<ul><li><br><ul><li>x</li></ul></li></ul>
```

In the editing view we could decide to put empty `<div>`, if we do not want to have `<p>` there. Such `<div>` seems to be the best solution to keep DOM <-> View binding.

The problem is data view where we can not but helper elements. On the other hand, we want this place to be marked as "need filling" so DOM Converter we will put `&nbsp;` there:
```
<ul><li>&nbsp;<ul><li>x</li></ul></li></ul>
```

I see two solutions: we could introduce special, "transparent" block, which create a `<div>` in the editing view to keep binding, but create nothing in the data view. Such block would also put `<br>`/`&nbsp;` if there is nothing inside.

Alternatively we could mark sibling element (`<li>` or `<ul>`) that the bogus is needed in that place.

**Comment by fredck** [comment]
I feel that the second case is wrong. We don't need to handle it and that's the reason for tools like the magic-line.

**Comment by pjasiun** [comment]
I agree that by default there should be no `<br>`. And agree that, for the near future only the list case is valid. 

But thinking about generic cases what should happen when one do not want to wrap everything in `<p>` and click on the magic line between two `<hr>` elements?

**Comment by fredck** [comment]
> But thinking about generic cases what should happen when one do not want to wrap everything in <p> and click on the magic line between two `<hr>` elements?

Well, that's not a problem for the generic bogus BR code. You're probably talking about the "enter mode BR" thing that, if we'll ever support it, will have to have its custom integration with the magic-line so it'll include a `<br>` when using magic-line, instead of a `<p>`, just like it'll have to customize the enter key.

IMHO, this is plain out of the scope of our initial implementation and it'll just cause distraction, therefore I would opt to let it out for now.

**Comment by pjasiun** [comment]
> IMHO, this is plain out of the scope of our initial implementation and it'll just cause distraction, therefore I would opt to let it out for now.

:+1:

Still, the nested list is a case.

**Comment by fredck** [comment]
> Still, the nested list is a case.

Yes, that's for sure... and I'm wondering if there would be any chance for the list feature itself handle this.... just like we're doing with backspace and enter :?

**Comment by fredck** [comment]
... because while we want it for lists, we don't want it for your `<div>` example :?

**Comment by pjasiun** [comment]
I think that it is list converter who should mark that place as "need bogus". The question is how such marker should look like.

**Comment by fredck** [comment]
Hum... this sounds like dirty... after all, the converter should work with and produce a clean DOM structure.

Bogus BR is a pure quirks feature related to the usability of the dirty DOM. Couldn't features add their customizations at quirks level so?

In fact, everything about bogus BR should be at quirks level only.

**Comment by Reinmar** [comment]
TBH, I don't like how this ticket was reported because the discussion is blurry and misses few important points.

Let's try to put it differently.

There are many places where we may need to render an "editing space". Those are:

* at the beginning of a block if first node is a block as well (covers the nested lists case),
* at the end of a block if last node is a block as well,
* inside empty blocks,
* inside empty inline nested-editables,
* between blocks.

There are two reasonable ways to create that editing space:

* put there a `<br>`,
* put there an empty block (if doesn't exist yet) with a `<br>` inside.

In a reasonable implementation (where enter mode = paragraph) we can't create a block only in the nested lists case. In all other cases we will be creating paragraphs and of course it's features' responsibility to do that when they decide that this space should be editable. Of course, that should be done in the model, not while converting to view.

Similarly, in the nested lists case only the list feature will know that an editing space is required, so it should somehow mark this location.

**Comment by Reinmar** [comment]
> Bogus BR is a pure quirks feature related to the usability of the dirty DOM. Couldn't features add their customizations at quirks level so?

That's going to complicated even further already a complicated code. We can just lose time trying to make things like this extensible.

> Hum... this sounds like dirty... after all, the converter should work with and produce a clean DOM structure.

Let it create a clean DOM. Isn't a attribute `requires-editing-space-before` added to nested `<ul/ol>` a satisfiably clean solution? The feature will not have to know how the space is created. It just needs to mark it in the same way as other features will need to create empty paragraphs if they want to make some space editable (like the magicline will do).

**Comment by Reinmar** [comment]
After a short talk with @pjasiun I may also consider the transparent block solution. So a list feature would simply create that block while converting model to view. Now, the question is how the block can be rendered to real DOM and to data:

* in the data the block will render to an `&nbsp;`,
* in the editable the block may render to a `<br>` but we may also consider rendering to an empty `<div>`.

The solution with rendering to empty `<div>` is simpler to implement, but it would be one additional element in the editable. That element may be styled (though, that's very unlikely that someone will styler a div without any classes), but with CSS's [`unset`](https://developer.mozilla.org/en/docs/Web/CSS/unset) value we may secure also that case.

So, if @pjasiun thinks that avoiding the case when we need to put a bare `<br>` at the beginning of a `<li>` will simplify the implementation, I think we could go this way. The implementation would then be really simple – you want a space, you always need a block. Just, you can make it transparent, so it does not render to the data.

PS. Perhaps the two-way rendering to data and editable could be extensible as @fredck wanted.

**Comment by pjasiun** [comment]
> Bogus BR is a pure quirks feature related to the usability of the dirty DOM. Couldn't features add their customizations at quirks level so?

The point is that the information that some area is editable or not is not only a UI quirks.

The representation of it is quirk, agree. There should not be a `<br>` in the model nor converter. But the converter should put some marker that this place is editable.

For instance:

List with bogus:
`<ul><li><br><ul><li>x</li></ul></li></ul>`

And list without bogus:
`<ul><li><ul><li>x</li></ul></li></ul>`

Are both correct. The different is that in the first case there will be empty editable line before the nested list and in the second case the nested list will start at the same line. I am not sure if we should hardcode that case. I think we should let list feature to mark the place where additional editable area should be. Then the view will handle this marker properly putting there bogus `<br>` or whatever is needed.

And, as I mention at the end of the first post, we can consider various ways of marking such places: using special element of attribute of the sibling.

**Comment by pjasiun** [comment]
> The solution with rendering to empty <div> is simpler to implement, but it would be one additional element in the editable.

I wonder about the DOM - View binding. It seems to be much simpler to recognise where mutation occurred if we put "transparent" `<div>`.

**Comment by pjasiun** [comment]
And we do not need to put such `<div>` in the data view, because we do not need to care about mutations there.

**Comment by fredck** [comment]
Now, considering that the nested list thing is the one and only case we can think about right now, why not total KISS and simply make this check at quirks layer without the feature having to care about it at all? If we'll ever need more in the future, we can think about adding dedicated features for that.

**Comment by Reinmar** [comment]
> Now, considering that the nested list thing is the one and only case we can think about right now, why not total KISS and simply make this check at quirks layer without the feature having to care about it at all? If we'll ever need more in the future, we can think about adding dedicated features for that.

I don't like hardcoding such things. It later a pain in the ass (absolutely not workaroundable) if you don't want this behaviour. Then, after a couple of years someone will ask us – how do I prevent from inserting that block here? ... And we'll need to update all plugins which assumed that this block is inserted there by default or we'll need to add even worse attribute `do-not-do-that-to-me-please`. Lot's of those in CKEditor 4 after all these years.

**Comment by pjasiun** [comment]
> KISS and simply make this check at quirks layer without the feature having to care about it at all? If we'll ever need more in the future, we can think about adding dedicated features for that.

Note that we do not even have DTD in CKEditor 5. We do not said what is block, what is inline, what child elements are allowed, do not have fixed list of tag names. Everything is defined by converters. So it would be strange if we hardcoded that there should be `<br>` before `<ul>` in `<il>`.

**Comment by fredck** [comment]
So if we're talking about not hacking, let's avoid magic attributes as well and have list items defining an inner element in the mode, called "content" or whatever similar, where the content of the list item ends up:

```
+ list item
|-- content
|-+ list (nested)
  |-+  list item
    |-- content
```

This sounds pretty reasonable, considering that list items accept mixed children.

**Comment by pjasiun** [comment]
But, if we do not want to have "transparent" element, how the data should looks like when you call `getData`?

**Comment by fredck** [comment]
It's all converter's job then and it has different strategies for converting `content`:

 * If empty:
   * A transparent `<div><br></div>` while editing.
   * Or simply `<br>` while editing.
   * A `&nbsp;` on output.
 * Not empty:
   * A transparent `div` with the data inside `content`.
   * The data inside `content`.

The `br` inside the transparent `div` may be even avoided, my marking the `div` directly with some magic attribute them, just like we would do with any element that needs to be expanded for editing.

Or.... just came to my mind.... we don't use a div but a custom element that represent a transparent block that needs to be expanded for editing.

**Comment by pjasiun** [comment]
https://github.com/ckeditor/ckeditor5-engine/pull/397 introduce `getFillerOffset ` method in `AttributeElement` and `ContainerElement`:  https://github.com/ckeditor/ckeditor5-engine/blob/3ce4c32aa71d43b5147c1890f91a3eeebfd58706/src/treeview/containerelement.js#L55-L62 which define if and where block filler (a.k.a. bogus br) should be put. It means that for list we could have `ListItemElement` which overwrites this method and returns the position before nested list if we need to put bogus there.

**Comment by pjasiun** [comment]
Since this can be done using `getFillerOffset` there is no reason to keep this ticket open.
