### ISSUE TITLE
Introduce model composer

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#341]
We need a handful of functions for most common operations on the document. We decided to group them under the name "composer". It's not perfect, but we could not find a better one. The view writer will be renamed to view composer as well.

Couple example ones:

* `deleteContents`,
* `weakInsertContents` and/or `insertContents`,
* `getContents`,
* `modifySelection` (expand, shrink),

The main idea about these functions is that they need to be extensible. They will be used by backspace/delete/typing/enter/etc. handlers which cannot know about all the features that can exist. Hence, some basic implementations can exist, but many features (like lists, tables, widgets) will want to tune up these algorithms.

We will also have view events such as "delete", "input", "enter", "copy", etc. Some features will want to listen to those too (e.g. to enter), but some actions combine multiple operations (e.g. typing does `deleteContents` and then `insertContents`) . If one of the features needs to override the delete action and if only the view events were the extension point, then it would also need to override input and enter events to tune how the delete action works there. Furthermore, there may be other algorithms about which that feature might not know and which might be deleting or inserting contents some.

The way how composer extensions will work is that events will be fired by `document.composer` methods. They will have default actions in form of a functions that can also be imported directly (so their logic can be reused without firing next events).

**Comment by pjasiun** [comment]
We need to find a good way to extend these algorithms. In might be not enough to overwrite a function in special cases. For instance selection may start inside the list, continue on the text and end inside the table. If one call `deleteContents` on such selection, default function should handle the text, list feature should handle list to merge it properly and table feature should handle part of the selection which is on table to remove only content inside cells, but keep the table structure. I think than we are going in the good direction and firing events on the composer instance in the way to go.

**Comment by Reinmar** [comment]
Deleting selection which spans over multiple type of elements is a tricky case indeed. It may happen that we'll need more than one event – e.g. `deleteContents:remove` and `deleteContents:merge` to reflect the two steps in which the algorithm usually works. But even then the algorithms may conflict with each other if we implement them imprecisely. So it's up to us and fortunately we'll be the authors of most of these tricky features anyway.
