### ISSUE TITLE
Implement TreeWalker options.direction

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#344]
It's currently impossible to iterate backwards which is a super common task (most algorithms work forwards and backwards – e.g. delete and backspace). I need to first scan the whole document and then pick up the last item.

This will become a performance issue pretty soon as simple backspace needs to scan the document to the left.

**Comment by Reinmar** [comment]
It'd be also good to close https://github.com/ckeditor/ckeditor5-engine/issues/345 to clarify which positions are returned (what may be unclear when we iterate backward).

**Comment by pjasiun** [comment]
We had `previous();` method in the `TreeWalker` not so long ago: https://github.com/ckeditor/ckeditor5-engine/pull/241/files But then maintaining that code, adding support to all options, when no one wast using it was a waist of time. No you can restore (and updated) that code if such logic is needed.

**Comment by oskarwrobel** [comment]
I have a question about detail.

What will be better?
`option.direction = 'backward|forward'; // default forward`
or
`option.backward = true|false; // default false`;

**Comment by pjasiun** [comment]
I like `direction` option. With a small change: "backward" and "forward", as flag should be all upper case.
