### ISSUE TITLE
Implement useful range constructors

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#355]
```js
new Range( onePos ) // collapsed range (@pjasiun doesn't like collapsed ranges, I'm not pushing either)

Range.createIn( el/docFrag ) // <el>[foo]</el>
Range.createOn( node ) // [<text>] or [<el>foo</el>]
Range.createOn( node, 'START' ); // [<el>]foo</el> (@scofalik says it's needed)
Range.createOn( node, 'END' ); // <el>foo[</el>] (cause we can :D)
```

**Comment by scofalik** [comment]
One of notes that I have after toying with converters is that "ModelRange and ModelPosition static creators should have shorter names". I am for refactoring this part of code, but also taking care of `engine.treeModel.Position`.

**Comment by szymonkups** [comment]
We can also consider changing static creators that use same class instanes to `clone` methods:
```
const newRange = Range.createFromRange( range );
// change to
const newRange = range.clone();
```

**Comment by Reinmar** [comment]
`Range.createFromRange()` is a bit more than just clone – it converts other kinds of ranges (live ranges) to the class from which you call this method.

**Comment by Reinmar** [comment]
But I agree that a shorter names would be better. And the methods could be more generic. For instance, recently I created `Position.createAt()` which reuses 3 other position constructors making 2 of them quite redundant.

**Comment by pjasiun** [comment]
> Range.createFromRange() is a bit more than just clone – it converts other kinds of ranges (live ranges) to the class from which you call this method.

We do not use `clone` because it is not clear what `range.clone()` will do. If the range was a live range should live range be create? If so, user need to remember to detach it later. `Range.createFromRange()`/`LiveRange.createFromRange()` is cleaner. On the other hand we have `Range.createFromRange()` in the view too because to the API similarity, what is strange a little. We could consider having `range.clone( live )`, so the clone method always return regular range by default, like selection do (returning regular range, when you want to get reference). Then the view API would be simpler, having only `range.clone()` as all other classes have.

**Comment by scofalik** [comment]
We already made this switch once, let's not get back to the same discussion and problems. It's good as it is. If anything, I'd change `Range.createFromRange()` to `.createFrom()` or `.clone()` but keep it as a static function that takes only range as parameter.

**Comment by pjasiun** [comment]
> `new Range( onePos ) // collapsed range (@pjasiun doesn't like collapsed ranges, I'm not pushing either)`

I think we could try to use `Position` in all cases we created collapsed `Range` in CKEditor 4. Then we will see if it make sense and add methods for creating collapsed range if `Position`s appear not be enough.

> Range.createOn( node, 'START' ); // [<el>]foo</el> (@scofalik says it's needed)

This API is unclear for me. `createOn` with `START` flag does not sound like range containing only the opening tag. `Range.createOn( node, 'WITHOUT_CHIDREN' );` sounds better. But also all methods which we want to use with a range containing such range should also accept element for instance: `batch().setAttribute( element, 'bold', true );`.

**Comment by Reinmar** [comment]
> I think we could try to use Position in all cases we created collapsed Range in CKEditor 4. Then we will see if it make sense and add methods for creating collapsed range if Positions appear not be enough.

Making something harder for developers just because we didn't expect them to use ranges when they need to point at a single position is a bit short-sighted. It's a general API and just because in most places ranges aren't empty doesn't mean that you won't be creating empty ranges quite a lot in your code. I already needed that. You may have algorithms accepting ranges and doing something with them. What if the algorithm should handle collapsed ranges and non-collapsed? Sometimes an information that "this thing is empty" is an information itself.

So really, there are absolutely valid usecases for collapsed ranges. We can make the API better with absolute minimum effort, so let's do.

> This API is unclear for me. createOn with START flag does not sound like range containing only the opening tag.

See how you read this "make the range on the start tag of the element". A flag saying "without children" goes IMO too much into why you need this range in that specific case, not what the method does.

> Now the only case is fireing conversion dispatcher on such range in tests, afair. I would introduce such method later, when we found more cases where we need it.

OK, even better, cause we don't have to think about it :P.

**Comment by scofalik** [comment]
`createOnElement` is used only in tests and have ambigous name. This method will be removed and change to test utils (if anything). From proposed constructors, I'd kept `createIn` and `createOn` without flags, and collapsed range constructor (I think it is useful and fine). BTW. `createIn` is same as current `createFromElement` but the name is much better, so I'll rename that method.

**Comment by scofalik** [comment]
OTOH, `createOnElement` (or proposed `createOn` + `'start'` flag) may be needed for features that we will start coding. It will be important for setting attributes only on model elements, not their children. I will think on better name for it.

**Comment by pjasiun** [comment]
> From proposed constructors, I'd kept createIn and createOn without flags, and collapsed range constructor (I think it is useful and fine).

:+1:

> createIn is same as current createFromElement but the name is much better, so I'll rename that method.

:+1:

> OTOH, createOnElement (or proposed createOn + 'start' flag) may be needed for features that we will start coding. It will be important for setting attributes only on model elements, not their children. I will think on better name for it.

Then we will implement it. :) Note, that it is far simpler to introduce new API then to remove a method.

I think that these methods should accept element instead of the range. Also note that It is not that hard to create any range manually so we need helpers only for the most popular cases.
