### ISSUE TITLE
Tree view Writer should not split text nodes inside containers.

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-engine#359]
Now writer splits text nodes when they are placed directly inside container elements (as tested [here](https://github.com/ckeditor/ckeditor5-engine/blob/e068de2/tests/treeview/writer/breakattributes.js#L48)). This is wrong behavior - writer should not split text nodes in that situation.

**Comment by szymonkups** [comment]
I looked closely at that issue and I think `breakAttributes` method should behave this way - it is used by other methods which relay on this. True is that result of `breakAttributes` method  is not a valid tree and it needs to be processed further  (and methods that use it are doing so). Maybe we should make `breakAttributes`, `breakRange` and `mergeAttributes` methods as private? Will they be used outside?

**Comment by pjasiun** [comment]
We could make these methods, with such logic, private, if such logic is needed for other methods. But at the same time we need, at least `breakAttributes` for positions conversion so we need a public method too. This public method should not break text nodes though.
