### ISSUE TITLE
Find better name for doc.enqueueueueueueChanges

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#370]
This name perfectly shows what it does, but it's super hard to type.

The alternatives which come to my mind are: `enqChanges`, or `enq`.

**Comment by wojtekidd** [comment]
What about [_line up_](http://idioms.thefreedictionary.com/line+up)? `lineupChanges`?
But `enqChanges` is also OK and it's shorter :)

**Comment by Reinmar** [comment]
I wouldn't understand `lineup` unfortunately. `Enqueue` is a more commonly used word (at least in IT).

**Comment by pjasiun** [comment]
I do not like `enqChanges` since we decided not to use shortcuts with the very limited list of exceptions.

**Comment by wojtekidd** [comment]
What about [_cue up_](http://grammarist.com/usage/cue-queue/) - the meaning here is a bit different, but perhaps it might fit our purpose?

**Comment by Reinmar** [comment]
We kept `enqueueChanges()` but the most commonly used method will be `change()`.
