### ISSUE TITLE
Unify model and view test tools.

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-engine#385]
As described here: https://github.com/ckeditor/ckeditor5-engine/pull/381#issuecomment-215351177, model and view tools needs some unification.

> 1. We also need two functions getData( treeView, rootName, options ) and setData( treeView, rootName, options ) which will work directly on the tree view, with that view's selection.
2. We need parse() and stringify() in the model. They should have similar capabilities to view's functions. getData() and setData() are defined there already.
3. Model getData()'s options.selection should be renamed to options.withSelection to conform to the naming in the view.

**Comment by pjasiun** [comment]
`setData` needs also... `data` parameter :)

And since we agreed to have a default root name (https://github.com/ckeditor/ckeditor5-engine/issues/390), the name might merged into options:

`setData( treeView, data, options )`

**Comment by pjasiun** [comment]
Because I used such methods in multiple test files I introduced simple version of `getData` and `setData` in: https://github.com/ckeditor/ckeditor5-engine/commit/7cbd17bea7d65245cf80c1fd12efcc17f7768440#diff-b47ebe54b5cb8d8272af93829f8d7632R848. Feel free to use or discard this code.
