### ISSUE TITLE
Default root name

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#390]
We need a default name of the root, at least for the tests consistent. @Reinmar suggested `main` what is fine for me. I think we could go further and set it as a default parameter of the `(model|view).document.(get|create)Root`. Then a single root editor creator would not need to care about the root name.

**Comment by Reinmar** [comment]
We could also change the order or params in `createRoot` because `elementName` will need to be specified more often than `rootName` (and usually when you have multiple roots you need to set element name anyway).

**Comment by pjasiun** [comment]
Most methods use `main` as a default root name value now, other tickets introduced these changes. 

Still we need to change the order of parameters in `model.document.createRoot`, ensure if there is no method which still need default parameter and do the clean-up after the changes (remove root name from tests which does not need it).
