### ISSUE TITLE
Delta transform _utils doesn't have 100% code coverage

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#391]
See: /tests/engine/treemodel/delta/transform/_utils/utils.js.html

**Comment by pjasiun** [comment]
![screen shot 2016-05-13 at 15 36 13](https://cloud.githubusercontent.com/assets/1166967/15249571/7d32b6dc-1920-11e6-9718-7e4a79736e41.png)

**Comment by Reinmar** [comment]
The quality of this project dropped so badly that I'm considering starting it from scratch.

**Comment by scofalik** [comment]
Hacking instanbul was not worth it.

**Comment by pjasiun** [comment]
Isn't is beautiful? :)

![screen shot 2016-05-17 at 13 40 21](https://cloud.githubusercontent.com/assets/1166967/15321142/edce174e-1c34-11e6-821b-ec0c9e0abbdf.png)

**Comment by Reinmar** [comment]
Even better than kittens.
