### ISSUE TITLE
Support selection direction

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#401]
To simplify the first implementation `Renderer` and `DomConverter` now ignore selection direction. They should handle it.

See https://github.com/ckeditor/ckeditor5-engine/issues/574 for awesome screencasts.

**Comment by Reinmar** [comment]
I think this is quite important feature. Maybe we don't have to have it in 0.1.0, but definitely ASAP.

**Comment by Reinmar** [comment]
A duplicate: https://github.com/ckeditor/ckeditor5/issues/314.
