### ISSUE TITLE
No selectionchange on Firefox

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#407]
As a result of a research (https://github.com/ckeditor/ckeditor5-engine/issues/315) we found out there is no `selectionchange` on Firefox by default (https://bugzilla.mozilla.org/show_bug.cgi?id=571294#c57), user need to change `dom.select_events.enabled` setting in the browser to enable it.

Therefore, selection observer (https://github.com/ckeditor/ckeditor5-engine/issues/310) will not properly without a polyfill (https://github.com/ckeditor/ckeditor5-engine/issues/315#issuecomment-212465509).

If Firefox will not support `selectionchange` soon we will need to introduce such polyfill in our code.

**Comment by Reinmar** [comment]
This makes for an iteration 3 ticket, because iteration 3 will be about browser compatibility.

**Comment by Reinmar** [comment]
It seems that selectionchange may land in Firefox veeeeery soon (https://bugzilla.mozilla.org/show_bug.cgi?id=1242718) so:

1. Let's wait to have some confirmation when that may happen.
2. If that's too long from now, let's not spend too much time on this anyway, as it finally seems that we'll have 100% native support.

**Comment by Reinmar** [comment]
I gently asked FF team to release the ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1231923#c16 :D

**Comment by Reinmar** [comment]
The issue to track now is https://bugzilla.mozilla.org/show_bug.cgi?id=1309612. And the response is very promising https://bugzilla.mozilla.org/show_bug.cgi?id=1231923#c17 :)))

**Comment by Reinmar** [comment]
https://developer.mozilla.org/en-US/Firefox/Releases/52 – so the event will ship in March :)

**Comment by Reinmar** [comment]
FF 52 was released and everything is fine.
