### ISSUE TITLE
view-converter-builder #fromAttribute() doesn't cover all characters

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#436]
The `/.*/` regexp will not pass line terminators: `\n`, `\r`, `\u2028` or `\u2029`.

We used to define such patterns as `/[\s\S]*/`.

**Comment by Reinmar** [comment]
There's a PR, but it requires tests.

**Comment by pjasiun** [comment]
Closed by https://github.com/ckeditor/ckeditor5-engine/issues/1239.

**Comment by Reinmar** [comment]
It wasn't:

```js
/workspace/ckeditor5/packages/ckeditor5-engine/src/conversion/buildviewconverter.js:
  139  	 * @returns {module:engine/conversion/buildviewconverter~ViewConverterBuilder}
  140  	 */
  141: 	fromAttribute( key, value = /.*/ ) {
  142  		const pattern = {};
```

**Comment by pjasiun** [comment]
Now it is closed. After the engine refactoring, we don't have `fromAttribute` method anymore.
