### ISSUE TITLE
Batch type

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#443]
We need the way to initialise data in the editor. The problem is that on the one hand we need a `change` event, so the data will be converted to the view, but we do not want to have an undo step for the initial data.

**Comment by pjasiun** [comment]
More I think about it more I feel that it might be useful to mark batches which should be ignored in the undo stack. 

It would work for both initialisation and collaborative editing.

For now, we agreed that deltas from other users can be applied without any `batch`. Such batch-less deltas would be ignored then by the undo feature. But what if we want to show group of changes introduced by certain user, for instance in suggestion mode? My point is, that these changes, introduced by other, which we want to ignore in the undo stack, may need to be grouped too, batches works for such grouping very well.

Also note that creating deltas, without a batch is not an easy task, right now. So for initialisation it would not be the simplest solution.

We can not also not put these changes to the history, because then the document version will be different then the number of operations in the history, what can be a reason of issues, especially when you think about collaboration and sending this initial data for other users.

**Comment by pjasiun** [comment]
Also note that re-initialization is a different case. When a use call `setData` and we decide it should reset the history we can do it. We can reset the model by clearing the history, removing all roots and reseting base version. Then we can create a root and set data the way we do it at the first place. Note that this way history will be empty but also match document version.

**Comment by pjasiun** [comment]
In https://github.com/ckeditor/ckeditor5-typing/issues/7 we realised that changes caused by undo should break typing batch, but changes causes by collaboration should not. This is why be can not put all of them as deltas without a batch. We need to group these changes in batches and created batch types.

For now we need special batches for:
 - collaboration,
 - undo/redo,
 - initialization.

**Comment by scofalik** [comment]
When we made this change we can consider whether it is a good practice to use `ModelDocument#applyOperation` without using a `batch`. I.e. in undo there is a code:
```javascript
for ( let delta of updatedDeltas ) {
	for ( let operation of delta.operations ) {
		this.editor.document.applyOperation( operation );
	}
}
```
This could be change to "transparent" `batch`.

I am writing this because in some places we already made kind-of-an-assumption that we check if applied `Operation` has a `batch`. If not, we treat it as "transparent" operation, that should not be considered by, i.e. undo mechanisms or typing mechanisms. Now we would be able to just check batch type instead of checking if batch is equal to `null`.

**Comment by Reinmar** [comment]
The idea about batch types was that you'll be checking them instead of whether the batch exists or not... so I guess that this means that you'll always need to generate batches. Does it sound feasible?

**Comment by scofalik** [comment]
Yes, you wrote basically what I wrote. I just wanted to point out that there already might be places that will need to be fixed.

**Comment by scofalik** [comment]
Needs https://github.com/ckeditor/ckeditor5-undo/issues/13

**Comment by scofalik** [comment]
For now we will stick only with two types:
* `default` - for almost all batches
* `transparent` - for batches that should be ignored by features, for now this is initial batch and OT batches (OT batches should be ignored by typing, undo and possible other features).

**Comment by pjasiun** [comment]
Closed via: https://github.com/ckeditor/ckeditor5-engine/pull/499.
