### ISSUE TITLE
View.Document.createRoot() does not transform tag name to lower case when take from HTML Element

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#450]
When executed as `view.createRoot( htmlElement )` the root's name is sed to e.g. `DIV`.

Everywhere else we're using lower case names.

**Comment by pjasiun** [comment]
You know that it's one line of code to change and you created 2 lines of ticket instead of fixing? ;)

**Comment by Reinmar** [comment]
Remember about tests and the fact that my current project configuration is so huge that it'd take me hour to switch :P.
