### ISSUE TITLE
DomConverter getCorrespondingDomText throws error

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#458]
`DomConverter#getCorrespondingDomText` should return null instead of throwing error if given `viewText` has no previous sibling.

**Comment by scofalik** [comment]
Pushed to branch https://github.com/ckeditor/ckeditor5-engine/tree/t/458

**Comment by scofalik** [comment]
This is already fixed on master. I pushed a test on master that is testing this issue.

**Comment by Reinmar** [comment]
The mentioned test: https://github.com/ckeditor/ckeditor5-engine/commit/05b02c5f1312e62333e822e8d4f8c87cdffb1f81.
