### ISSUE TITLE
Default selection should be inside the first element where text is allowed

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#465]
If there is no selection we create one at the beginning of the document. It should be inside the first element where text is allowed, to be rendered properly.

**Comment by fredck** [comment]
Just want to leave a small note here as this feature can be very troublesome. The algorithm that would correctly identify the proper placement of the selection must be very well thought, taking in consideration the various combinations of elements we may have inside the document.

**Comment by pjasiun** [comment]
It was tricky it CKEditor 4. In CKEditor 5 we do:
```js
for ( let position of Range.createFromElement( root ).getPositions() ) {
	if ( document.schema.check( { name: '$text', inside: position } ) ) {
		return new Range( position, position );
	}
}
```
What can go wrong? ;)

**Comment by fredck** [comment]
I was wondering if we have inline elements, non editable elements, inner-editables and things like that.

**Comment by Reinmar** [comment]
Yep... it's renderers job to make sure that selection has its spot. In the model we're only interested in what's the first element which can accommodate a text.

**Comment by Reinmar** [comment]
Although, I've got to say that I still can't believe that it may be that simple :P.
