### ISSUE TITLE
Selection.setRanges/addRange() should throw when not a range passed

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#471]
I spent half an hour on this... My code was correct, but it turned out that I removed import statement at some point, so I've been using native `Range` class which works. It only breaks deep in our code, but with a non-obvious error.

**Comment by Reinmar** [comment]
I'm also thinking about switching off browser env in JSHint config. Having to explicitly add browser globals could save us from issues like this.

**Comment by pjasiun** [comment]
We should definitely improve type checking. `Range` is not the only case, but the most popular.

**Comment by oskarwrobel** [comment]
I've added validation for Range as a first step of improving type checking. @Reinmar are you thinking about switching off browser env for each repository including ui or only for selected as engine?

**Comment by scofalik** [comment]
I've created follow-up issue #526 concerning JSHint setting. We should move discussion there. I will close this issue after related PR is closed.
