### ISSUE TITLE
Introduce view.Document#focus()

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#488]
We need a method which features will be able to use to tell the engine to focus the editor.

The method should check in which editable the selection is now and focus that specific editable if it's not yet focused.

Related issue: https://github.com/ckeditor/ckeditor5-headings/issues/7

**Comment by pjasiun** [comment]
See https://github.com/ckeditor/ckeditor5-engine/issues/491.

**Comment by pjasiun** [comment]
The `focus()` method may simply fire `document#focus` event the same way `FocusObserver` do. It should be enough to set the editor focus, because all listeners will handle it.

**Comment by pjasiun** [comment]
Or maybe `render` will be needed too.
