### ISSUE TITLE
Renderer should focus editable to which the selection was moved

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#489]
Case:

1. You've got two editables.
2. Model and view selections point to 1st of them.
3. Someone changes selection in the model so it points to 2nd editable.

Expected: Renderer may need to focus that second editable. I'm not 100% sure about this, because it may turn out that browsers will focus the editable to which renderer moved selection, but this needs to be checked.

Related issue: ckeditor/ckeditor5-headings#7

**Comment by pjasiun** [comment]
Note that https://github.com/ckeditor/ckeditor5-engine/issues/491 will change the way focus works. Now the renderer do not render selection if the editable, where the selection is, is not current focussed editable. After the change renderer will check if document is focused and render selection if it is. I think that editable will focus automatically if we will set selection there.

**Comment by szymonkups** [comment]
Now, after introducing `engine.view.Document#focus()` method, `engine.view.Renderer#render()` is updating focus and moving it to editable where selection is currently placed.
