### ISSUE TITLE
Check why selection is moved to the start of the document when d&d happens in drop-down panel

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#490]
This is a cross-package issue, but it needs to be debugged in the engine first

TC:
1. Open http://tests.ckeditor.dev:1030/build/amd/tests/headings/manual/headings
2. Select something in the editor.
3. Open the dropdown.
4. Try to select text in the dropdown.

What happens:
- You cannot select the text. We thought that this is due to CSS (`webkit-user-select:none`), but we removed that style and the text still could not be selected.
- On mouse down editable is blurred. This makes sense.
- On drag start editable gets focus and selection is moved to the beginning of the document. This does not make sense at all ;|.

The latter causes https://github.com/ckeditor/ckeditor5-headings/issues/7. We need to check whether the engine behaves correctly and if so, try to prevent such situation by preventing proper native events on the dropdown (what would make this a UI issue).

**Comment by szymonkups** [comment]
It looks like when `user-select:none` style is applied, mouse events are propagated to the editable element. This happens when you start dragging on one of the drop-down items:

![selection](https://cloud.githubusercontent.com/assets/2396463/16563272/5492bcfe-4201-11e6-9d72-a534714aa41a.gif)

This can be prevented by `event.preventDefault()` on `mousedown` event fired on list element, so maybe we should use that instead of `user-select:none`, @oleq?

**Comment by oleq** [comment]
Don't you think that d&d in a dropdown panel is an edge case? Especially that the API is still unstable and full of bugs. Let's focus on essentials, not edge cases – at least at this stage of development.

**Comment by szymonkups** [comment]
It's an edge case, but it happens quite often when you try to select an item from the drop down and move mouse at the same time. We have other priorities now, I'm not insisting on fixing this right away.

**Comment by Reinmar** [comment]
It's a bug that I found pretty quickly and I've been able to reproduce it what means that it's not that edgy. Otherwise, you can expect that after encountering it once I wouldn't be able to figure out what I did the first time.

Anyway, it's not for 0.1.0. We may address it later, in 0.3.0 or wait for more devs reporting it.

**Comment by Reinmar** [comment]
PS. Note that after you opened the dropdown (by clicking the button) you usually move mouse down to the option you want to click. Perhaps that's what make it that frequent.

**Comment by oleq** [comment]
> Anyway, it's not for 0.1.0. We may address it later, in 0.3.0 or wait for more devs reporting it.

👍

**Comment by Reinmar** [comment]
How serious bug it is I've just learnt on myself. I've been testing @szymonkups's PR in headings and I was surprised it doesn't work. Turned out I've been consistently triggering the d&d case even though I knew that it doesn't work. Simply because clicking without mouse move is that hard.

**Comment by scofalik** [comment]
I'll check this soultion:

> This can be prevented by event.preventDefault() on mousedown event fired on list element, so maybe we should use that instead of user-select:none

**Comment by scofalik** [comment]
> You cannot select the text. We thought that this is due to CSS (webkit-user-select:none), but we removed that style and the text still could not be selected.

This is untrue, after removing the style text in dropdown can be selected (unless you are talking about dropdown preview area (the one that shows "list of options" once clicked)).

**Comment by Reinmar** [comment]
> This is untrue, after removing the style text in dropdown can be selected (unless you are talking about dropdown preview area (the one that shows "list of options" once clicked)).

AFAIR, I was talking about dropdown list.

> It all works well after removing this style, so I'd just get rid of it and apply proper event cancelling for given UI controls.

Yep, I'm for (again, AFAIR :D) `dragstart` listener canceling it. This should prevent stealing focus from the editable.

> EDIT: above will, unfortunately, let select some things in toolbar if selection starts somewhere else. So maybe it's better to leave the style but try to do something so that the editable is not focused when dropdown is clicked.

In CKE4 we've been preventing this, but I don't feel (yet) that it matters. So I'm ok with removing the style, especially that it isn't cross-browser anyway.

If you feel that we understand each other, I'll close this ticket and report one in ckeditor5-ui-default.

**Comment by oleq** [comment]
> In CKE4 we've been preventing this, but I don't feel (yet) that it matters. So I'm ok with removing the style, especially that it isn't cross-browser anyway.

Do you remember how was it done in v4? I couldn't find it anymore.

**Comment by Reinmar** [comment]
What do you mean? How do we prevent selecting pieces of UI? There is the `user-select` style used and `mousedown` is prevented:

![screen shot 2016-10-05 at 14 42 21](https://cloud.githubusercontent.com/assets/156149/19113459/fef0456c-8b09-11e6-8812-270abd8df74c.png)

**Comment by oleq** [comment]
My question was in this context:

> EDIT: above will, unfortunately, let select some things in toolbar if selection starts somewhere else.

**Comment by Reinmar** [comment]
So, I don't know the full answer. Selecting the toolbox is definitely blocked in Chrome, but `-webkit-user-select: none` will work only on Blink/Webkit based browsers. At least I'd expect that, but I can't select the toobox also in Firefox. 

I also remember that in the dropdown we didn't have `mousedown` prevented and there was even a PR which was meant to fix that. So it's definitely expected that such things will be blocked  everywhere on the UI.

**Comment by Reinmar** [comment]
Works fine now. Fixed by https://github.com/ckeditor/ckeditor5-ui/issues/228.
