### ISSUE TITLE
Selection & focus, second approach

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#491]
**Scene:**
`view`

**Dramatis Personae:** 
`view.document`,
`view.selection`,
`FocusObserver`.

## Scene 1: The current situation.
Document has a `focusedEditable` property which is set by the `FocusObserver`. If `focusedEditable` is `null` it means that editor is blurred.

What should `focus()` method do? It should take the editable from view selection and set it as a `focusedEditable`. 

## Scene 2: The problem.
This realised an architectural issue. The selection editable is in fact the `focusedEditable`, it should be the same as `focusedEditable` if the `focusedEditable` is not null. What is selection change and `focusedEditable` does not change? Which one is the real `focusedEditable`? Which should be used?

## Scene 3: The conclusion.
It looks that we have redundant information. The selection has the real information which editable is focused. The only additional information `focusedEditable` bring is if the editor is focused or not. In fact, the selected editable is an useful information, even when the editor is blurred.

## Scene 4: The fix.
To fix this situation we should replace `focusedEditable` which two properties:
 - `selectedEditable` - which can be a getter, and always return editable which contains selection, even when editor is blurred.
 - `isFocused` - boolean property which is handled by the `FocusObserver`.

**Comment by Reinmar** [comment]
5.5/6. -0.5 for periods at the end of headings.

**Comment by pjasiun** [comment]
Also renderer now listen on `focusedEditable` and render selection only if selection is in the focused editable. This is a wrong behavior. It should prevent selection rendering only if editor is blurred. It means it should observe only `isFocused` to know if editor is focused or not.

Also, since, `renderer`, `domConverter` and `observers` are  the only one who play with DOM, `renderer` should also handle calling native `focus` on the element which needs focus.
