### ISSUE TITLE
Renderer miss 100% code coverage

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#509]
In `/ckeditor5/engine/view/renderer.js`.

No else path for:
```
[E] if (selectionPosition.parent instanceof _text2.default) {
	if (fillerPosition.isEqual(_position2.default.createBefore(selectionPosition.parent))) {
		return true;
	}
}
```

And:
```
[E] if ((0, _filler.isInlineFiller)(domFillerNode)) {
	domFillerNode.parentNode.removeChild(domFillerNode);
} else {
	domFillerNode.data = domFillerNode.data.substr(_filler.INLINE_FILLER_LENGTH); // no coverage
}
```

**Comment by szymonkups** [comment]
I found which PR changed code coverage of `Renderer`: https://github.com/ckeditor/ckeditor5-engine/pull/504. There is a change in `Renderer` test file which changes `before()` to `beforeEach()`. It looks like each test was working fine but was using already initialized `Selection`, `DomConverter` and `Renderer` objects so the missing paths were covered. Now each test case uses newly initialized objects and new tests cover missing paths.
