### ISSUE TITLE
Select all and delete places selection in incorrect location

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#520]
Reproducible at least in Chrome and Safari.
1. Go to https://ckeditor5.github.io/
2. Focus the editor.
3. Press ctrl+a and backspace.
4. Type a letter.

That letter will be inserted outside `<h2>` (should be inside a block ofc).

There's also a question whether deleting after `ctrl+a` shouldn't remove all contents and leave a simple paragraph. This may require reporting a bug in delete feature (and `deleteContents` in the engine).

**Comment by Reinmar** [comment]
https://github.com/ckeditor/ckeditor5/issues/242 shows a bit different bug. And in http://giphy.com/gifs/3oEjI9qZIWjFsRToEo I recorded even different one (different errors are thrown, but this one was recorded on Safari).

That's the DOM after the screencast:

![screen shot 2016-07-18 at 17 26 19](https://cloud.githubusercontent.com/assets/156149/16920325/87020868-4d0d-11e6-8c68-ca15b1545ad7.png)

**Comment by Reinmar** [comment]
Actually, I've just understood that on Safari the popup that we know from iOS appears and the error in the console is caused by it. So this screencast shows two issues :D. One that an empty paragraph remains after `ctrl+a,del` (so this issue) and second that an error is thrown after the popup is used (I'll report it in ckeditor5-typing).

**Comment by Reinmar** [comment]
Another duplicate: https://github.com/ckeditor/ckeditor5/issues/306. May contain some more cases.

**Comment by Reinmar** [comment]
Very related issue: https://github.com/ckeditor/ckeditor5-engine/issues/614.

**Comment by fredck** [comment]
Does this mean that we need an active selection monitor that fixes it whenever it ends up into invalid places?

**Comment by Reinmar** [comment]
You mean the idea I described in #614? Yes, I'm considering something like this. Either we control selection or we control the result of all algorithms. Can be both ways. Actually, the latter may be even better idea. I don't know yet.

**Comment by Reinmar** [comment]
This case is now fixed. But there's a separate one to be handled: https://github.com/ckeditor/ckeditor5-engine/issues/670
