### ISSUE TITLE
Switch off `browser` environment setting in JSHint

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#526]
Related to #471.

We should consider switching off `browser` setting in JSHint what would result in having errors whenever native DOM objects and classes are used. The result would be that we will have to define globals like this by hand but we would not run into problems like described in #471.

I am creating this as a follow-up issue so we can close #471 which originally was about something else.

**Comment by scofalik** [comment]
We should also decide if this should be done only in `ckeditor5-engine` or maybe also in other repos?

**Comment by Reinmar** [comment]
I think that this ticket makes sense, but I'd move it to `ckeditor5` because this should be fixed generally, in all repos.

Check https://github.com/ckeditor/ckeditor5/pull/237 to see how to apply a change to all repos.
