### ISSUE TITLE
Selection check infinite loop kicks in too often

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#535]
1. Go to https://ckeditor5.github.io/
2. Put selection in the first heading.
3. Start pressing up, down, up, down arrows quickly.

If you do it frequently enough and repeat enough times you got:

```
selectionchange-infinite-loop: Selection change observer detected an infinite rendering loop. undefined
```

and the seleciton stops refreshing (the label of the headings dropdown stops updating).

**Now, god bless our marvellous idea to log stuff like this to the console!!!** Imagine the hours spent on debugging this security check if it ended up with a silent errror.

**Comment by Reinmar** [comment]
This is even easier to trigger (which makes it pretty critical). Just keep pressing backspace for a longer time. The warning will be logged pretty quickly.

**Comment by scofalik** [comment]
After fixing #401 selection infinite loop kicks in also happen at the edge of `<strong>` element.

**Comment by scofalik** [comment]
> This is even easier to trigger (which makes it pretty critical). Just keep pressing backspace for a longer time. The warning will be logged pretty quickly.

I can't reproduce this. However in this case:

> Go to https://ckeditor5.github.io/
Put selection in the first heading.
Start pressing up, down, up, down arrows quickly.

The warning/check kicks in incorrectly. When you comment out the whole if nothing breaks or crashes (no infinite loop).

**Comment by scofalik** [comment]
Okay it appears that the `_loopbackCounter` in `SelectionObserver` is not cleared on user action which is just wrong. The infinite loop condition should kick in only if there were multiple dom selection changes without user interaction. Do you have an idea how to check it without having interaction between other observers?

**Comment by Reinmar** [comment]
I think that what we want to check is the number of selection changes in a period of time. Like whether 100 last changes happened in a second. If that's true, then we have loop.

The first way to implement this which comes to my mind is having an array of last change timestamps. You add the current one and checks the one that you remove (like in a FIFO queue). I guess there may be smarter ways too :D.

Anyway, this should not fail us. In fact, this is how I thought it worked.

**Comment by Reinmar** [comment]
PS. The numbers must be chosen in such a way that it won't fail in automated tests :D. But it should be fine if in every `beforeEach()` we create a new observer. If not, then this is test what's broken.

**Comment by Reinmar** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-engine/pull/671.
