### ISSUE TITLE
Check RTL support

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#543]
We should check how engine and existing features work with RTL content.

**Comment by Reinmar** [comment]
1. Open any sample.
2. Change language to Arabic.
3. Press 'a' multiple times.
4. Shift+left.

<img width="717" alt="screen shot 2016-09-23 at 12 19 37" src="https://cloud.githubusercontent.com/assets/156149/18782714/1313fcae-8188-11e6-9404-28b1b96a5574.png">

As you can see the range boundaries are reversed *when printed on the console*. It must be checked whether they really are reversed in the DOM.

But I'm afraid they are, because if you press Ctrl+B, then:

<img width="718" alt="screen shot 2016-09-23 at 12 21 19" src="https://cloud.githubusercontent.com/assets/156149/18782786/6d72151e-8188-11e6-8318-aa8f99999697.png">

**Comment by Reinmar** [comment]
Note: The above can only be reproduced in Chrome and Safari. In Firefox you get:

<img width="1321" alt="screen shot 2016-09-23 at 12 31 41" src="https://cloud.githubusercontent.com/assets/156149/18783021/b570d5b6-8189-11e6-878c-99edb502b185.png">

However, when I copied the console output here, I got:

```html
<heading1>شششش[]</heading1>typing:123:3
<heading1>ششش[ش]</heading1>typing:123:3
<heading1>شششش[]</heading1>typing:123:3
<heading1>ششش[<$text bold="true">ش</$text>]</heading1>
```

**Comment by Reinmar** [comment]
<img width="953" alt="screen shot 2016-09-23 at 12 50 21" src="https://cloud.githubusercontent.com/assets/156149/18783476/530d32c2-818c-11e6-8f16-3f2c7f53cd51.png">

Contiguous DOM selection, non-contiguous box.

**Comment by fredck** [comment]
A good way to test it is comparing the behavior we have in our implementation with the one in the native contenteditable.

**Comment by Reinmar** [comment]
Heh... this is weeeird.

![oct-07-2016 15-44-02](https://cloud.githubusercontent.com/assets/156149/19192000/ef897c3c-8ca4-11e6-88ae-637c2889c0e0.gif)

**Comment by Reinmar** [comment]
This is weird:
![oct-07-2016 15-46-28](https://cloud.githubusercontent.com/assets/156149/19192123/6e94a5c4-8ca5-11e6-8c0d-239b434a803c.gif)

**Comment by Reinmar** [comment]
OK, it works as expected if the editable has `dir=rtl`. I wrapped the whole editor in `div[dir=rtl]` but apparently it must be the editable which has the attr.

**Comment by fredck** [comment]
Remember that we must, additionally, checked "mixed direction" in the content, like an Arabic word or phrase inside English content. Such content may appear within a `<span dir="rtl">` element but also without any element around it.

**Comment by Reinmar** [comment]
I created a manual test in which you can compare, and eventually debug, RTL support issues.

The most important thing I understood is that if you have a mixed content (RTL text next to LTR or RTL text in LTR container), then really weird things happen. Fortunately, it's exactly the same behaviour which you get in native `contenteditable`. Browsers also tend to differ between themselves in such cases.

So, I consider this done and everything is working fine (tested in Chrome and Firefox).

Tests were added in https://github.com/ckeditor/ckeditor5-typing/commit/64ad8c1208c2d936f3e2dfed80128130e7f8caec

**Comment by Reinmar** [comment]
> Remember that we must, additionally, checked "mixed direction" in the content, like an Arabic word or phrase inside English content. Such content may appear within a <span dir="rtl"> element but also without any element around it.

I tested mixed content without those spans. I don't think that something could be wrong with spans, because it's browser who renders that mess and moves the selection. In the DOM everything is in the right order – range end is always after range start in DOM order. E.g. this works nice, even though visually the range is discontiguous:

![oct-07-2016 17-15-33](https://cloud.githubusercontent.com/assets/156149/19195379/b3476092-8cb1-11e6-930f-1ad83f74a551.gif)

**Comment by AGhasemzadeh** [comment]
Hello,
I think having RTL support is so easy.
Just don't add dir=ltr when replace editor.
