### ISSUE TITLE
LiveRange loses position after removing data from document

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#569]
### How to reproduce:

Set some data to the editor by DataController:
```javascript
dataController.set( '<p>foobar</p>' );
```

Put selection anywhere:
```javascript
// Collapset selection at the middle of the text node.
model.enqueueChanges( () => {
    document.selection.setRanges( [
        ModelRange.createFromParentsAndOffsets( modelRoot.getChild( 0 ), 3, modelRoot.getChild( 0 ), 3 )
    ] );
} );
```

Remove data:
```javascript
dataController.set( '' );
```

Selection start and end path should be equal `[ 0 ]` but is equal `[ 0, 0, 3 ]`

# Note
This fix https://github.com/ckeditor/ckeditor5-engine/pull/570/files is a workaround to this bug. To reproduce please comment this changed code.

**Comment by scofalik** [comment]
This is kind of related to: https://github.com/ckeditor/ckeditor5-engine/issues/331

As far as I can see in example you propvided, `LiveRange` is working correctly. If you are not aware, removing in CKE5 is done through moving removed nodes to an artifical "graveyard root". It is a special root in model, that stores removed parts of model tree. It is correct behavior, that positions in `LiveRange` are updated to be in that root. For example a feature might have stored a position pointing to where something should be displayed. If those positions would be set to `[ 0 ]` in a root, we would have a lot of mess. Also, if removed content is reinserted through undo, we need to get the range position's back in place.

In fact, every feature that uses/operates on `LiveRange`/`LivePosition`/selection should introduce their own way of fixing them, if it is needed. What should be done is a callback for `engine.model.Document#selection` which will fix the selection if it ends up in graveyard. This makes sense, as we don't want that exact selection to ever end up in graveyard (which may not be true for other uses of `Selection` class). And this is what the linked issue is about.

**Comment by oskarwrobel** [comment]
Thanks, now it make sense for me. I'm closing ticket because it looks like the same case as #311.
