### ISSUE TITLE
Custom attribute value for AttributeCommand

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#571]
Now `AttributeCommand` allows only to set/remove attribute with hard coded value `true`. It is ok for features like `bold` or `italic` but e.g. `link` https://github.com/ckeditor/ckeditor5-link/issues/1 feature needs to set custom value.

**Comment by Reinmar** [comment]
I guess that this is a wrong repo ;)

**Comment by Reinmar** [comment]
BTW. I found this https://github.com/ckeditor/ckeditor5/issues/112 which touches the topic that we've been discussing today. You can link it or close it if you'll report a new issue for what you plan to do with this command now.

**Comment by oskarwrobel** [comment]
I'm closing https://github.com/ckeditor/ckeditor5-core/issues/9

**Comment by scofalik** [comment]
`AttributeCommand` AFAIR was meant for this: setting `true` or `false` for given attribute. It was for features like `bold`, `italic`, `underline`, `inline quote`, etc. Something that you just switch off and on. More complicated attribute setting features will require more complex UI and logic so it is natural they would need different code.
