### ISSUE TITLE
Removing empty paragraph throws error

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-engine#575]
**Browsers checked:** Chrome

**Steps to reproduce:**
- Go to manual test [http://localhost:1030/build/modules/amd/tests/engine/manual/editingcontroller](http://localhost:1030/build/modules/amd/tests/engine/manual/editingcontroller),
- put cursor in the empty paragraph between `foo` and `bar`,
- press Delete (Fn+Backspace on most Macs),

**Results:**
- in the Console you will see error:

  ```
Uncaught CKEditorError: move-operation-nodes-do-not-exist: The nodes which should be moved do not exist.
```
- when you try to move cursor up and down couple of times with arrow keys, you'll get another warning in the Console:

 ```
selectionchange-infinite-loop: Selection change observer detected an infinite rendering loop. undefined
```

**Comment by Reinmar** [comment]
I think that this test doesn't support Fn+delete (so forward delete). Looking at its code, it was only supposed to support backspace (which on some Macs is named "delete"). I'll fix the description.

**Comment by maxbarnas** [comment]
I used Fn+Delete, because the backspace key was doing nothing.

**Comment by Reinmar** [comment]
Yeah, you're right. I've just checked the key codes precisely.

But this test is not supposed to work at the end of blocks – it's not what it checks. But this must be clarified, so I'll fix the test decription or use some feature to replace those mock.

**Comment by Reinmar** [comment]
I removed the whole test. It didn't make sense here, duplicating a lot of code which features introduce. Instead, I'll add simple manual tests for features which don't have them.
