### ISSUE TITLE
Compatibility issues in tests

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-engine#576]
Related: https://github.com/ckeditor/ckeditor5/issues/312.

**Comment by maxbarnas** [comment]
Currently, I added fake polyfill for `String.prototype.normalize()` to check if it is the real problem in Safari 9. Real, working alternative to this is https://github.com/walling/unorm, but it is around 140 kB. I am open to suggestions. Maybe there is already some package in CKEditor 5, that solves this problem.

I also highlighted problematic tests with `// x` comment, and will deal with them now.

**Comment by Reinmar** [comment]
cc @scofalik – he mentioned that that normalization isn't necessary (or something similar :)).

**Comment by scofalik** [comment]
We can remove normalization for now.

**Comment by Reinmar** [comment]
@maxbarnas found also some issue with regexps. Could you elaborate on that, @maxbarnas? Perhaps @scofalik will be able to help you. I only know that ES6 added support for multi-byte chars in regexps, so perhaps their transpilation fails somehow... but OTOH, it should make tests fail.

**Comment by maxbarnas** [comment]
@scofalik I explained the problem a little in https://github.com/ckeditor/ckeditor5-utils/issues/66#issuecomment-242045302

**Comment by Reinmar** [comment]
This issue covered only a part of problems. There's a followup in https://github.com/ckeditor/ckeditor5/issues/325.
