### ISSUE TITLE
Introduce click observer

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#577]
Simple click observer is needed by link feature.

**Comment by Reinmar** [comment]
Why is it needed?

**Comment by oskarwrobel** [comment]
We need to show balloon panel attached to the link after clicking on it.

**Comment by scofalik** [comment]
Observers is the part of engine which I understand least xD but I AFAIR you don't need observer, there is already observer that that handles mouse clicks. What you need is just simple event callback added to mouse click event.

**Comment by scofalik** [comment]
Okay I stand corrected - there are no default mouse observer at the moment.

**Comment by Reinmar** [comment]
@oskarwrobel – I'm not 100% sure about that clicking. You may later learn that it's better to combine mouseup or selection change or whatever else together to get better results. I'd propose to first implement this functionality in the link package and eventually hoist observers to the engine later on. OTOH, we can be pretty sure that someone will need a click observer... so you can implement it and couple other ones anyway :D.

**Comment by oskarwrobel** [comment]
> You may later learn that it's better to combine mouseup or selection change or whatever else together to get better results

It's possible, but for now click handler works fine for me, and seems to be the simplest solution.

> I'd propose to first implement this functionality in the link package and eventually hoist observers to the engine later on.

I've put `ClickObserver` class to engine observers, but is not registered at default. Link feature will register it.
