### ISSUE TITLE
Changes required by List feature.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#583]
This is an overall issue for changes required in engine by List feature. It also covers bugs discovered and fixed during implementing List feature. For complete list of changes look at commits in related PR.

#266, #267 and #367 will be handled in this issue (and related PR), however discussion may be continued in those issues.

**Comment by Reinmar** [comment]
I reeeeeeeealy miss a list of things which changed.

**Comment by Reinmar** [comment]
OK, shame on me :D I haven't checked the list of issues :D.

**Comment by scofalik** [comment]
As I said, you can check list of commits, but I'll copy it here for you...

Changelog:
* `Mapper` now uses callbacks for position mapping.
* Introduced `Mapper#registerViewToModelLength` function that takes a view element name and a function that evaluates view element length in the model.
* Introduced `RenameOperation`, `rename` change type conversion and default callback for `rename` change.
* Added: Schema#itemExtends. which enables checking whether item with name A extends item with name B.
* Changed: view.Position#getAncestors changed order of ancestors.
* Added: model.Position#getAncestors.
* Changes in `view.Writer`: added `view.Writer#breakContainer` and `view.Writer#mergeContainers`, renamed `view.Writer#breakAt` to `#breakAttributes` and merged it with `#breakRange`.
* Changed how `move` and `remove` change types are dispatched, now they are similar to `insert` and `xxxAttribute` change types (have `consumable` and the changed range is converted item-by-item).

Bug fixes:
* Fixed: In AttributeOperation, 0 as attribute value was treated as no value and caused removing attribute.
* Fixed: view.TreeWalker jumped over range boundary when creating return value.
* Added missing LiveSelection#getLastRange() method, which lack of caused not returning default range when the method was called on empty live selection.
* Multiple doc fixes.
