### ISSUE TITLE
Filler (?) is infinitely created in a specific case

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#590]
1. Open https://ckeditor5.github.io/.
2. Open dev tools and inspect a paragraph in which you'll type.
3. Make a collapsed selection.
4. Press ctrl+b.
5. Type one letter.

See that some text node is created infinitely.

http://giphy.com/gifs/3o6ZsVwMmFFLZuJSRW

**Comment by pjasiun** [comment]
Related: https://github.com/ckeditor/ckeditor5-engine/issues/462, https://github.com/ckeditor/ckeditor5-engine/issues/613.

**Comment by Reinmar** [comment]
OK, what @pjasiun meant by "related" is that this bug is actually caused by #462. So #462 must be resolved first and this is a pretty big topic.

**Comment by pjasiun** [comment]
The proper order of fixing is: https://github.com/ckeditor/ckeditor5-engine/issues/259 -> https://github.com/ckeditor/ckeditor5-engine/issues/462 -> this.

**Comment by Reinmar** [comment]
Seems to be fixed by https://github.com/ckeditor/ckeditor5-engine/pull/634.
