### ISSUE TITLE
Model: Element renaming and Schema issues.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#591]
There are two issues connected with element renaming, that has not been yet solved. Both are connected with model correctness and `Schema`:

1. Element with given name may not be allowed by `Schema` in the place it was before.
2. Some attributes may not make sense after the element got renamed. In worst case scenario "garbage" attributes will have different/wrong impact on conversion/view than before the element was renamed. Not to say that this will lead to invalid model states, even for a while (we can still remove attributes just after renaming the element, still it would be better if the attributes changed happened at the same time as element renaming).

There are two ways we can go:

1. Write algorithm that will remove attributes that are not valid with schema. To get good results we would need really good/complex algorithm, preferably one that would check all possible combinations. If we will check whether just attribute X or Y is allowed on the item, we might find in a situation where an element has no attributes even though it is allowed when it has both X and Y attributes.
2. Leave it to the developer. I have a feeling that in most cases, when renaming an element, the feature has a perfect information how the element should look like. I.e. when `paragraph` is changed to `listItem` (and back) we know that we need to add (remove) `type` and `indent` attributes.

No matter what solution we will choose, to solve problem 2. we need to be able to pass some information about attributes to the `RenameDelta` and `RenameOperation`.

I propose that we:

1. Don't write any algorithm for automatic schema solving.
2. Add two optional parameters to `RenameDelta` (and `RenameOperation`):
  - `attributesToSet` - an object with key/value pairs - those attributes will be set in `RenameOperation` after element is renamed
  - `clearAttributes` - if set to `true`, all attributes will be cleared (this will be done before setting attributes from `attributesToSet`.
3. At the end of `RenameOperation`, add schema check that will throw if schema is invalid after changes to model are done by the operation. No automatic solving, just throwing.

**Comment by Reinmar** [comment]
> 2. Leave it to the developer. I have a feeling that in most cases, when renaming an element, the feature has a perfect information how the element should look like. I.e. when paragraph is changed to listItem (and back) we know that we need to add (remove) type and indent attributes.

+1

**Comment by Reinmar** [comment]
Nothing to do here. It's simply a developer's job to remove or add necessary attributes in the correct order when renaming things.

We also noticed that perhaps rename operation should become replaceTag operation so we can also modify attributes at once. It may help with OT when e.g. one person was changing list type and another was converting this list item to a paragraph.

**Comment by scofalik** [comment]
"Simply a developer's job" - however, there will be features that do not know anything about themselves and you would not know which attributes should be removed. Truth is that some kind of check should be done after each `RenameDelta` so it should be either a part of `RenameDelta` or `RenameOperation` or some kind of easy-to-use util.

**Comment by Reinmar** [comment]
I've been thinking about cases like paragraph to heading changes. E.g. you can imagine the alignment feature which applies alignment attr to ps and hs. However, those features know nothing about themselves, so when a heading feature converts a paragraph to a heading it will need to check in the schema whether its existing attrs are correct. If they are, then they can be converted. But the problem arise when some can be, some can't – should we accept only all or nothing or can we pick the valid ones? The latter sounds better, but there may be (hopefully, super rare) situations where picking some of attrs will lead to a bad results.
