### ISSUE TITLE
Selection constructor should accept ranges array

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#600]
Cause, currently I have to do this:

``` js
const sel = new Selection();
sel.addRange( range );
```

Which could be simplified.

**Comment by ma2ciek** [comment]
As I talked with @Reinmar, we'll create a new static function rather than change the constructor, so there'll be no need to rewrite existing code.

### Usage:
```js
const sel = Selection.createFromRanges( [ range1, range2 ] );
 // And with isLastBackward set to true:
const sel2 = Selection.createFromRanges( [ range1, range2 ], true );
```

The ` Selection.createFromRanges` uses the `Selection#setRanges` under the hood, so it's firing `change` event for now which is not needed I suppose.

**Comment by Reinmar** [comment]
>  The Selection.createFromRanges uses the Selection#setRanges under the hood, so it's firing change event for now which is not needed I suppose.

It's not needed but it changed nothing because you can't listen on it :D

> As I talked with @Reinmar, we'll create a new static function rather than change the constructor, so there'll be no need to rewrite existing code.

TBH, I think I might've changed my mind. `Range()` does accept two positions and `Position()` does accept root and path. So, since range + direction is the most typical way of creating a selection I guess it could be the constructor's option.

Why I initially thought about moving it to a separate method was that I wasn't sure whether this is an identical case to `Range` and `Position` because the view selection can also be a fake one (so that's like another type of selection so why would the constructor handle just one). But... I've just completely overcomplicated this.

**Comment by ma2ciek** [comment]
Ok, it makes sense, so I'll move this code to the constructors :D

**Comment by ma2ciek** [comment]
I pushed the corrected version which still uses `setRanges()`. But now `setRanges` is reassigning `_ranges` and `_lastRangeBackward` and fires `change` event which is unnecessary. Maybe we can use the default parameters in the constructor function + simple `range instanceof` checks?

**Comment by Reinmar** [comment]
Let's discuss this under #918.
