### ISSUE TITLE
Batch API miss some methods

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#608]
Because the batch API is the way we expect users will modify the model, it should be simple to use. We should check if there are no missing methods. For sure there is not `batch.appendElement` and if we will introduce `element.remove()` (https://github.com/ckeditor/ckeditor5-engine/issues/607) we should have `batch.removeElement` too. We may also check if there are default  parameters we could introduce to make the API nicer. It should be as useful as the using the `Node|Element` API.

**Comment by scofalik** [comment]
I agree, however I don't think we need this right now. Can be postoponed to iteration 4 or 5.

**Comment by Reinmar** [comment]
Do I understand correctly, that these methods will simply call existing batch methods? Like `removeElement()` will create a range and call `batch.remove()`?

I guess this is simple and can be implemented by anyone at any time. I'd assign it to any milestone.

**Comment by pjasiun** [comment]
For instance `batch.append()` will call `batch.insert()` with the proper position. The same way `element.append()` call `element.insert()`.

**Comment by pjasiun** [comment]
And yep. It is simple.

**Comment by Reinmar** [comment]
I think we have most of these already in the writer, so bye bye.
