### ISSUE TITLE
Move dev utils to src

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#610]
As requested here: https://github.com/ckeditor/ckeditor5/issues/333

The dev utils (`tests/_utils/*`) should be moved to `src/`. We agree to call those utils which will be moved from `tests/` to `src/` "dev utils" to differentiate them from "test utils". The former can be useful while development. The latter are fully oriented on tests.

So, in this ticket:

1. Move `test/_utils/*` to `src/dev-utils/` and update API docs.
2. Move `test/_utils-tests/` to `tests/dev-utils/`.
3. Prepare branches fixing paths to these utils in other repositories (don't create PRs).

**Comment by pjasiun** [comment]
And (of course) change absolute paths to related.

**Comment by maxbarnas** [comment]
Relative paths are needed in files inside `src/dev-utils/`, correct?

**Comment by maxbarnas** [comment]
@pjasiun confirmed my assumption.

**Comment by maxbarnas** [comment]
I moved/renamed `dev-utils`and corrected paths to `src/dev-utils/*` and `tests/dev-utils/*`.

I also modified repositories that use `src/dev-utils/`. Changes are in `engine/t/610` branches in following repos:
- `ckeditor5-undo`,
- `ckeditor5-utils`,
- `ckeditor5-paragraph`,
- `ckeditor5-core`,
- `ckeditor5-basic-styles`,
- `ckeditor5-link`,
- `ckeditor5-enter`,
- `ckeditor5-headings`,
- `ckeditor5-typing`.

It is still work-in-progress and needs further check, but recent changes are already pushed.
