### ISSUE TITLE
Caret moved to the end of paragraph when filling chars removed.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#633]
After fixing issue #259 editor finally is able to create empty inline tags (like `<em></em>`) with filling characters, basing on `model.Document#selection` attributes.

However, there is a bug when user types a letter at such position:
`<p>foo<em>&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;&#8203;^</em>bar</p>`. After typing one character at such position, all filling characters are (correctly) removed. But the selection is moved to the end of paragraph.

This is a followup issue to #259 and #462. It was a hidden bug.

**Comment by Reinmar** [comment]
I think it's a DUP of #590.

**Comment by Reinmar** [comment]
And of https://github.com/ckeditor/ckeditor5-typing/issues/47.

**Comment by scofalik** [comment]
It is a DUP of #47
