### ISSUE TITLE
Add a view to model pipeline to the EditingController

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#641]
The `DataController` has the `parse()` method which gets a string and returns a model fragment. The `EditingController` also needs such method and it should accept an HTML string and return a model fragment.

To do that we need to  add `viewToModel` dispatcher to the `EditingController`. Actually, we could add only it and let the feature do `parse()` by itself. This may be even better because then the feature will be able to provide a view fragment it wants to convert (it won't be forced to provide an HTML string). It may be the way to go in case of the clipboard pipeline – we'll be able to implement it using the view structure, not a string.

**Comment by pjasiun** [comment]
Note that this change causes changes in all features, because they will need to add a converter to the new pipeline too.

**Comment by pjasiun** [comment]
> This may be even better because then the feature will be able to provide a view fragment it wants to convert (it won't be forced to provide an HTML string).

I think that there is no point in making this API too flexible. It will be used only for paste/drop and should be designed directly for this feature.

**Comment by Reinmar** [comment]
> I think that there is no point in making this API too flexible. It will be used only for paste/drop and should be designed directly for this feature.

That's true. But you don't know how paste and drop will be implemented :D. That was exactly the mistake I made – I assumed that I want to convert data from a string. But then I realised that clipboard should rather work with a view structure (`view.Document#clipboardInput` will be fired with a view structure). So I would even avoid adding any method to the `EditingController` if all the clipboard command will need to do is:

```js
editingController.viewToModel.convert( viewDocumentFragment, { context: [ ? ] } 
```

Maybe only the context deserves a default which makes me think that a method could be helpful. But how would it be named?

**Comment by pjasiun** [comment]
`input( viewDocumentFragment, context )`?

**Comment by Reinmar** [comment]
I wonder if it should do the whole `input()` or just the processing. E.g. after `drop` we want the selection to look differently, so we'd need to postfix this. OTOH, `Composer#insertData` will set some selection anyway, so regardless of how we'll use it, we'll need to postfix the selection.

Let's see if `input()` will be enough. If we'll need a better granularity, we'll change it.

**Comment by Reinmar** [comment]
Right after writing the previous comment I realised that e.g. `DataController.set()` does `enqueueueueueChanges` and `input()` shouldn't if we plan to post fix the selection, so considering that I'm against `input()`. I want `DataController.parse()`'s equivalent.

**Comment by Reinmar** [comment]
Second thought – we should be using the data pipeline for the clipboard. E.g. when copying a widget you don't want its drag handler, container, special classes to land in the clipboard. You want its "data" representation.

So, I'm closing this ticket and I'll open new for `DataController.toModel()` method.

**Comment by Reinmar** [comment]
I reported a ticket for the `insertContent` method https://github.com/ckeditor/ckeditor5-engine/issues/648.
