### ISSUE TITLE
Remove Composer and clean up controller's methods

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#646]
It's been always bothering me. There's native `range.deleteContents()` and I followed this naming convention, but it doesn't seem to be grammatically correct. And it becomes a problem when we want to have `insertContent()` (where "contents" makes even less sense) method.

So, we'll have `insertContent()` and we should renamed `deleteContents()` to `deleteContent()`.

In both cases we take the more popular option:
- https://www.google.com/trends/explore?q=%22delete%20content%22,%22delete%20contents%22
- https://www.google.com/trends/explore?q=%22delete%20content%22,%22insert%20contents%22

**Comment by Reinmar** [comment]
We've talked with @pjasiun about moving all of these methods to the `Document`. There's only a single instance of it, so all features can listen on the method events (hooks) on the document. We'll keep the `DataController.insert()` method because it lets you use a view nodes.

I'm fine with that. But now it raises a problem – I needed to move the controllers to `engine/controller/` directory in order to be able to have `insert.js` next to them (it keeps the code of the data insertion algorithm). Since all the 3 methods will be moved to the document, I'd need to create `engine/model/document/` directory... and to be consistent move the `document.js` there too.

Now. First of all, I'll need to change hundreds of tests. Second, this will be inconsistent with the view :D. Therefore, I'm thinking that perhaps those function could stay in something like `engine/model/utils/` or more specific like `engine/model/document-management/`.

RFC.

**Comment by pjasiun** [comment]
I think `engine/model/` is fine for for model helpers. `Document` is a models facade, do we can say that everything in `engine/model/` is the model. Do you remember when we were thinking about making document a factory for ranges (`Document.createRange`, there should be a ticket about it)? It's the same story.

**Comment by Reinmar** [comment]
If `engine/model/` is fine, then it will grow quite fast to a pretty big size (number of files). I'd like to avoid the situation where 3 weeks later we notice that there's 20 files and dirs in it and it's a mess so we want to group some files in directories.

E.g. `engine/model/insertcontent.js` or just `engine/model/insert.js`? The latter may be a bit unclear. We'll have:

```
composer/
delta/
operation/
batch.js
delete.js // new
document.js
documentfragment.js
element.js
getcontent.js // new (btw. it must be "content" in this case)
history.js
item.jsdoc
insert.js // new
liveposition.js
liverange.js
liveselection.js
model.jsdoc
node.js
nodelist.js
modifyselection.js // new
position.js
range.js
rootelement.js
schema.js
selection.js
text.js
textproxy.js
treewalker.js
writer.js
```

For me, it begins to get messy...

**Comment by pjasiun** [comment]
I prefer to group the real code, not potential. In fact, we could do be bigger clean-up:
 - selection connected classes could be in a separate folder: `position.js`, `range.js`, `selection.js`, `liveposition.js`, `liverange.js`, `liveselection.js`
 - element connected classes could be in a separate folder: `element.js`, `documentfragment.js`, `node.js`, `item.jsdoc`, `nodelist.js`, `rootelement.js`, `text.js`, `textproxy.js`.
 - then we could have a folder with utils: `delete.js`, `getcontent.js`, `modifyselection.js`, `treewalker.js`, `writer.js`

After such clean-up only "big" API parts stay in the main folder: `batch.js`, `document.js`, `history.js` and `schema.js`, what makes some sense.

For sure such clean-up should be done in the view too and in the separate ticket.

**Comment by Reinmar** [comment]
Such "cleanup" doesn't make sense. We'd only make import paths longer. There are now only big and important classes in `view/` and `model/` which is totally fine. And I want to keep that so that's why `deletecontent.js`, `getcontent.js` and the rest would need a separate directory. Besides, these are utils which will be very rarely used, in a very special cases where you need to reuse the base behaviour of the functions exposed in `Document` and `Selection`.

**Comment by Reinmar** [comment]
We've finally defined the base API in https://github.com/ckeditor/ckeditor5-engine/issues/678#issuecomment-260608098. The conclusion from this design is that there should be couple of methods on the controller. For now, we'll place them on the `DataController`, however, these methods will work with `model.DocumentFragment` not with the view (as they do now).

Also, I'd like to keep the longer names `insertContent()`, `deleteContent()`, `getSelectedContent()`, `modifySelection()` because they won't be confused when listed next to other controller's methods.

**Comment by Reinmar** [comment]
TODO:

* [ ] remove the composer,
* [ ] rename `insert()` to `insertContent()`,
* [ ] make `insertContent()`  accept model doc frag.
