### ISSUE TITLE
Create WidgetElement and EmptyElement

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-engine#657]
We need special view elements for widgets and empty elements.
`WidgetElement` will be used to represent widgets inside the view.
`EmptyElement` will be used to represent elements that cannot be divided and cannot contain any elements inside (for example `<img>`).

Things to have in mind:
- View writer should handle these new elements,
- both new element types should provide proper `getFillerOffset` method,
- both should extend view's `Element` class.

**Comment by Reinmar** [comment]
During the course of this ticket we decided to not implement `WidgetElement` as the number of base classes should be kept low. It's now `ContainerElement`, `AttributeElement` and `EmptyElement`. The rest inherit from these 3 and inject different strategies (currently – one strategy – how to handle the filler node).
