### ISSUE TITLE
Expose Selection's method to inherit attributes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#658]
Use cases:
1. `<p><strong>x</strong>y^</p>`, press delete. The bold button should be active.
2. `<p>y^z</p>`, paste bold text. The bold button should be active.

In both cases it's not.

We need a method that you'd call inside `DataController's` `input()` and `delete()` methods after setting the selection.

PS. Normally selection attrs are automatically updated when you change its ranges, but not in this case, because the selection is automatically moved to those places by "live" algorithms.

**Comment by Reinmar** [comment]
PS. Of course, we should also use this method in those places where it's needed.

**Comment by Reinmar** [comment]
The `refreshAttributes()` method will be introduced by https://github.com/ckeditor/ckeditor5-engine/pull/653.

**Comment by scofalik** [comment]
Or we could just refresh selection not only on "api" events, but on all of them. Then, however, `_updateAttributes` would be called much much more often (i.e. after every typed letter). 

On the other hand if we can keep on adding `refreshAttributes` directly in various algorithm, we may end up with the same amount of `_updateAttributes` calls anyway.

**Comment by Reinmar** [comment]
I still prefer an explicit calls. OTOH, so far the cases that we have are that we call `selection.setRanges()` or some other selection's method to modify selection but with ranges which equal where selection is right now. So maybe `_refreshAttributes()` should be called in all these cases, regardless of whether the ranges have changed?

**Comment by scofalik** [comment]
This is doable but would require moving `_refreshAttributes()` call from event callback to all the methods modifying ranges.

**Comment by Reinmar** [comment]
We solved this by refreshing the attributes on every attempt to change the selection by API (regardless of whether it has changed or no).
