### ISSUE TITLE
ModelConversionDispatcher does not dispatch change event when attribute value is an object

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#665]
I'm working on a case where attribute value is an array. When I change value inside array then `model -> view` converter do nothing with this change because dispatcher does not dispatch change event. It works fine on add/remove attribute, but doesn't work on change.

**Comment by scofalik** [comment]
How do you change a value inside array?

With current architecture, every change on model document has to be done through `Batch` API, that is you have to use `batch.setAttribute( ... )`. However the problem is that the attribute won't change if you pass the same array.

This means that you have to do it like this:
```javascript
const arrayVal = myElem.getAttribute( 'attr' );
const newArrayVal = arrayVal.splice();
newArrayVal.push( anotherValue );
batch.setAttribute( myElem, newArrayVal );
```

I know this is cumbersome but that's how it works like now. I am not sure whether we want to change it because that would require additional logic in attributes apis all over the engine. I am also not sure whether we will keep on supporting any value as an attribute value (maybe we'll introduce "array-like" keys or something).

**Comment by oskarwrobel** [comment]
I was trying by

```javascript
batch.setAttribute( range, 'attr', newArrayValue );
```

and also

```javascript
batch.removeAttribute( range, 'attr' );
batch.setAttribute( range, 'attr', newArrayValue );
```

I was trying to change value from array to some primitive and this was working

```javascript
newArrayValue = 1;
batch.setAttribute( range, 'attr', newArrayValue );
```

**Comment by oskarwrobel** [comment]
> However the problem is that the attribute won't change if you pass the same array.

Sorry I didn't read this.

**Comment by scofalik** [comment]
As you can see in my example, `newArrValue` is a different object than original value.

**Comment by oskarwrobel** [comment]
> As you can see in my example, newArrValue is a different object than original value.

It helped with missing change event, but:

Converter:
```javascript
buildModelConverter().for( data.modelToView, editing.modelToView )
	.fromAttribute( 'attr' )
	.toElement( ( arrayValue ) => new AttributeElement( 'span', { 'attr': JSON.stringify( arrayValue ) } ) );
```

then:

```javascript
setModelData( modelDoc, 'foo <$text attr="[1,2,3]">bar</$text> biz' );
getViewDoc( viewDoc ) // 'foo <span attr="[1,2,3]">bar</span> biz'
```
works as expected

then:
```javascript
const el = modelDoc.getRoot().getChild( 1 );
batch.setAttribute( Range.createIn( el ), 'attr', [1,3] );

getModelData( modelDoc ) // 'foo <$text attr="[1,3]">bar</$text> biz' );
getViewDoc( viewDoc ) // 'foo <span attr="[1,3]"><span attr=[1,2,3]>bar</span></span> biz'
```

double span in view

**Comment by scofalik** [comment]
This is weird, converter builder should build a converter that removes old stuff from view when attribute changed and it should work well, especially since attribute value is casted from array to a json string.

**Comment by oskarwrobel** [comment]
It is possible that I'm doing something wrong :) I'm still investigating this.

**Comment by oskarwrobel** [comment]
I'm just stupid. Problem with double span was because I was modifying reference, and after that (not before) I was creating clone of array. So problem with missing change event is solved by

> However the problem is that the attribute won't change if you pass the same array.
