### ISSUE TITLE
Markers: Selection after creating marker.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#701]
1. Open manual test for markers integration http://localhost:8125/tests/engine/tickets/643/1.html
2. Make a selection intersecting with initial marker.
3. Create a marker using a button.
4. Selection after marker is created is in a wrong place.

This may be smaller or bigger issue. There might be more cases producing incorrect result.

**Comment by Reinmar** [comment]
I can still confirm it.

If you make a selection like (`{}` is the existing marker):

```
Lor[em ipsu{m do]lo}r sit amet.
```

Then upon creating a red marker, the end of the selection will be extended to `lo]}r`.

I wonder if this could be related to https://github.com/ckeditor/ckeditor5-engine/issues/922 (which has some similar evidences). But it also can be just a coincidence.

**Comment by szymonkups** [comment]
Buttons used in manual test are stealing focus from the editor and this is why selection is not updated after markers insertion. I will update the manual so the buttons will not steal the editor's focus.
