### ISSUE TITLE
Blockquote implementation

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-engine#710]
This is an initial issue describing `Blockquote` feature implementation. 
There is no requirements list yet, but we already see that it will require some changes in the engine. Let's gather them here.

#### Add support for nested elements to `DataController#modifySelection`:
Extending selection in situation like this:
```html
<blockquote><p>foo[]</p></blockquote><p>bar</p>
```
should return:
```html
<blockquote><p>foo[</p></blockquote><p>]bar</p>
```

**Comment by Reinmar** [comment]
I'm also curious how's `deleteContent()` dealing with such a cases. I remember that I didn't want to think too much on it back then so the implementation may be poor.

**Comment by Reinmar** [comment]
Besides, it's tricky to understand which rules are specific to blockquote and which are general and should land in the default algorithms.

**Comment by fredck** [comment]
Btw, be sure to check [Editor Recommendations on Quotes](http://ckeditor.github.io/editor-recommendations/features/quote.html).

**Comment by Reinmar** [comment]
Good point. Do we want to have a caption support? If so, then it's a far more complex feature than what we have in CKEditor 4. It may need to be implemented with a widget or some smart model operations. The latter would be a very interesting test for our data model, but I'm afraid that we don't have time for that now.

We'd need to start this with a UX research too, cause I'm not sure how should the caption be reachable when vs how to escape blockquote. Perhaps it's a simple rule that enter in an empty paragraph in a blockquote removes that paragraph and moves selection out of the quote and below the caption.

**Comment by Reinmar** [comment]
I talked with @fredck. We're going now with a CKEditor4 like implementation (but rendering to a `<figure class="quote">`). We'll rethink the captioning in the future.

**Comment by szymonkups** [comment]
When modifying selection in situation described in  [first comment](https://github.com/ckeditor/ckeditor5-engine/issues/710#issue-192804232) will be implemented, it should also support objects and widgets should also use it during `delete` and `backspace` handling:
```html
<widget></widget><blockquote><p>[]</p></blockquote>
// backspace pressed
[<widget></widget>]
```
```html
<blockquote><p>[]</p></blockquote><widget></widget>
// delete pressed
[<widget></widget>]
```

**Comment by Reinmar** [comment]
I can see that `modifySelection()` is covered by `describe( 'beyond element – skipping incorrect positions' )` and works as expected.

So the problem with https://github.com/ckeditor/ckeditor5-block-quote/issues/7 lays inside `deleteContent()`.
