### ISSUE TITLE
Rendering issue – text disappears after removing a style

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#711]
![dec-01-2016 13-54-05](https://cloud.githubusercontent.com/assets/156149/20794686/c3a3e392-b7cd-11e6-8b1b-0cb44bc9f492.gif)

**Comment by Reinmar** [comment]
Still reproducible.

**Comment by oleq** [comment]
I couldn't reproduce the exact issue but there's still some problem with the selection:
![kapture 2017-06-20 at 13 16 17](https://user-images.githubusercontent.com/1099479/27330656-b5c08e66-55ba-11e7-8c18-d713c823cec7.gif)

**Comment by Reinmar** [comment]
I'm also only able to reproduce the problem with selection.

**Comment by Reinmar** [comment]
The rendering issue was fixed in #922. The selection problem will be handled in #992.

**Comment by Reinmar** [comment]
I'm closing this ticket because it was about text being lost.
