### ISSUE TITLE
Improvements for model document.getNearestSelectionPosition

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-engine#712]
Some improvements are needed in order to correctly support object elements:
* it should return `Range` as it might return correct position in text or selected object,
* it should support direction: `forward`, `backward` or `both` - it will be especially needed when dealing with arrow keys
* it should have more tests and tests should use use our test utilities.

**Comment by szymonkups** [comment]
Shouldn't this method return `null` instead of `new Position( position.root, [ 0 ] )`? It might be hard for API users to determine if returned value is a correctly found position/range or fallback one. But with this change we will must handle `null` value everywhere outside this method.

**Comment by Reinmar** [comment]
Makes sense. But the `defaultRange` should never be `null`, cause it will break a lot of algorithms.

**Comment by szymonkups** [comment]
> defaultRange should never be null, cause it will break a lot of algorithms.

I will handle this situation there.

**Comment by scofalik** [comment]
More often than not, situation where we would return `null` means that there is something wrong in the editor anyway. So it's hard to say what is the better scenario.

**Comment by Reinmar** [comment]
That's true. But here we're talking only about what this method returns, not what happens next. E.g. `Document._getDefaultRange` can then return a range at `[ 0 ]` position. Insert content may do something else. And other algorithms may depend on that search to understand other things (like – there's no selection spot before the selection, which may be preferred, but there's space after).
