### ISSUE TITLE
There should be a try-catch around enqueueChanges

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#731]
Most of the error occur from the inside of the `enqueueChanges` block. There should be a `try-catch` which call `log.error`, so the `error` event is fired and can be handled.

**Comment by pjasiun** [comment]
See: https://github.com/ckeditor/ckeditor5/issues/383

**Comment by Reinmar** [comment]
Let's tackle it in ckeditor/ckeditor5#383

**Comment by pjasiun** [comment]
Actually, it should be part of https://github.com/ckeditor/ckeditor5/issues/1304. I do not think it should be part of ckeditor/ckeditor5#383. We have plenty of tickets related to error handling and if we will try to solve all of them in ckeditor/ckeditor5#383 it will become a super-uber-ticket. It is better to have a number of smaller task.

**Comment by Reinmar** [comment]
It's good to have an epic ticket where we can track those things, though. As you could see – I didn't know where to look :)

But yeah, I can be a DUP of the other one.
