### ISSUE TITLE
view.Element.clone() will not clone EditableElement

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#743]
It's going to fail because EditableElement accepts one more param in the constructor. It should not change the constructor in this way.

**Comment by Reinmar** [comment]
I think that we need to move `_document` to custom props and remove it from the constructor. The class can then have a getter and setter which will be used by e.g. the `view.Document` class like that:

```js
	createRoot( domRoot, name = 'main' ) {
		const rootTag = typeof domRoot == 'string' ? domRoot : domRoot.tagName;

		const viewRoot = new RootEditableElement( rootTag.toLowerCase(), name );
		viewRoot.document = this;
```

**Comment by Reinmar** [comment]
Related ticket: https://github.com/ckeditor/ckeditor5-engine/issues/744. We can get rid of that `arguments` use and the special `clone()` method by simply checking that the 3rd arg of the constructor is either falsy or and empty array.

**Comment by szymonkups** [comment]
When we move `_document` to custom properties we will have to have getter and setter for the `document` property. It will then create a situation when document can be set again for particular element (now it is read-only property). Should we prevent this, that document can only be set once?

**Comment by szymonkups** [comment]
I've created [t/743 branch](https://github.com/ckeditor/ckeditor5-engine/compare/t/743) with custom properties, also fixing `arguments` issue in `EmptyElement`. I'll create PR from that branch when we will decide that we are ok with this solution.
