### ISSUE TITLE
Custom selection rendering

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#746]
This one is tricky.

On the one hand, we have the fake selection and widgets. Fake selection does not handle the selection visual representation, it is widgets implementation what know better how it should be done. In the case of the image, it can be a class which adds a border, in the case of the table it can be the border of a cell and in a case of any other widget, the fake selection can be represented in the way we can not predict.

On the other hand, we have the markers and the selection for the markers: it can be a selection of other users, comments or the search result. Each of these is represented with a different color or even shape.

Now, the question is: how to represent that it's image what is commented? Or that the other user select a column in the table?

My idea is that features could provide customizable selection API: at least color could be configurable. Then, every feature which wants to select this element in the custom way could use this API. 

Then, the problem is how to handle the case where both custom and fake selections are on the same widget element. In the case of text, where the real selection can be used it is always over the custom selection. In the case of the fake selection, user's selection should have always a higher priority than the custom selection.

I told you it's tricky.

**Comment by Reinmar** [comment]
It's pretty clear, I think, that we need a general fake selection feature and that this feature must be able to support the main user's selection and other user's selection or even more styles (like comments).

E.g. there's a case in which you want to show the current user's selection – when the focus is moved to the link panel. Then you need to fake the user's selection in the editable in a similar way that you fake selection on images, but without moving the real one to a hidden container. So this is very similar to showing other users' selections.

So, what I think we need is the ability to create multiple view selections with different styles (i.e. color). They will need to be rendered independently one of another, but only one will be able to touch the real selection. Handling this on such a level will allow us to have a built-in support for multiple selections in features like widgets or tables. I'm only a bit unsure whether we should use inline styles or some data attributes to set in the DOM what should be the color of a specific selection. Data attribute sounds better.

One more thing which worries me is that when changing the current user's selection to fake we now use its method `setFake()`. I don't know if we shouldn't have like a selection renderer passed to the selection constructor and changing the selection instance on the fly. Something like:

```js
// When faking the current user's selection:
const newSelection = new Selection( HiddenSelectionRenderer );
doc.removeSelection( doc.selection ); // assuming that doc.selection is always the current users sel.
doc.addSelection( newSelection );


// When marking selection once focus is moved to the link balloon:
const selection = new Selection( FakeSelectionRenderer );
doc.removeSelection( doc.selection );
doc.addSelection( selection );

// When reverting selection to real one:
const selection = new Selection( SelectionRenderer );
doc.removeSelection( doc.selection );
doc.addSelection( selection );

// When a new user joins:
const selection = new Selection( FakeSelectionRenderer );
doc.addSelection( selection, 'selectionIDOrSth' ); // we need to mark somehow that this isn't the doc.selection
```

I guess that the API can be greatly improved, but I wanted to show a raw version of it. The renderer could be e.g. set on the fly (`doc.selection.rendere = ...`). And we could have `doc.selection` for the real one and `doc.fakeSelections` for the rest.

Also, the renderers names would need some improvements. We need 3 – real selection, selection which only creates a span's on the content (I called it "fake", but it's not following the CKE4's naming) and selection which moves the real one to a hidden container (which I called "hidden").

**Comment by Reinmar** [comment]
So, now. This doesn't seem to be tricky :P. We just need to wrap it in a nice API and then agree how conflicting selections should be rendered (if 2 users focus an image).

**Comment by pjasiun** [comment]
> So, now. This doesn't seem to be tricky :P.

Yea. More like tons of code to write :)

**Comment by Reinmar** [comment]
> Yea. More like tons of code to write :)

Yes, that's true. But I don't think that we need this in 1.0. We should keep this model in minds, but e.g. in 1.0 you don't need to show fake selections of other users (I mean – when they select images).  First, minimal implementation shouldn't be that big.

**Comment by pjasiun** [comment]
> Yes, that's true. But I don't think that we need this in 1.0. We should keep this model in minds, but e.g. in 1.0 you don't need to show fake selections of other users (I mean – when they select images). First, minimal implementation shouldn't be that big.

Yep, agree.

**Comment by pjasiun** [comment]
We introduced `highlight` feature to solve this problem.
