### ISSUE TITLE
MarkersCollection returns inconsistent data type

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#751]
`MarkersCollection` fires `add` event which provides instance of `Range` created from marker `LiveRange`, but `MarkersCollection#get()` returns `LiveRange` instance. AFAIK every collection in CKE5 returns consistent data for `add` event and `get()` method.

There is an idea to create `Marker` class to represent single Marker instead of pure `LiveRange` / `Range`. This should solve a problem with decision what `MarkersCollection` should return.

**Comment by pjasiun** [comment]
I agree that the instance of the `Marker` would be nice. You will be able to get the name of the maker from it. We may also introduce some functions which take a marker as a parameter. From the logical POV marker is something more then the range.

**Comment by scofalik** [comment]
Yes, it's done this way to not create a new instance of `LiveRange` which would be super annoying as you'd have to destroy such instance each time you're done working with it.

Having a `Marker` class would solve the issue. I've been thinking about it but, I had two problems with it:
* that would be just an object with no methods and only two properties,
* users would have to import a new class and create new instance just to "mark" a range as "marker".

OTOH, the next requirement for markers is to provide a way to state that some markers are "local" and some should be updated between clients. This could also be solved by "marker wrapper object".

So, we either could make `Marker` class, which would have two (three) properties and no methods other than constructor. Or we may do it internally in `MarkerCollection`. `MarkerCollection#add` could take three parameters (`name`, `range`, `type`) but then `add` `event` will be fired with plain object (containing `LiveRange` instance). Also `get` method would return an object with `LiveRange` instance.

WDYT?

**Comment by scofalik** [comment]
`Marker` class will be introduced, as a simple API over `LiveRange`. `Marker` instances will be created when a `Range` is added to `MarkerCollection`. `Marker` instances will be returned by `MarkerCollection#get` method. `Marker` instances will be used in events fired by `MarkerCollection`.
