### ISSUE TITLE
Adding markers on editor init

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#755]
To add `Marker` we need a model `Range` instance to pass to the `MarkersCollection.add()`, but `Range` and `Position` constructors are not available with editor instance. I think that search util exposed in editor instance can be helpful. Util for matching text and returning `Range`. This util might also help to create `find and replace` feature in the feature.

Or if we think that search util is not necessary we need to figure out the other way of creating a `Range`.

**Comment by Reinmar** [comment]
I don't understand how the first two sentences are related to each other :D. The first says that constructors are not available "with the editor instance" – what does it mean? The second proposes a search util, which sounds like a completely different topic.

Could you clarify this?

**Comment by oskarwrobel** [comment]
You can not create a Range instance in:
```javascript
Editor.create().then( ( editor ) => {
    // Here Range constructor is not available, so you can't add eg `Marker` on init.
    // You can't do editor.document.markers.add( 'name', new Range( new Position(), new Position() ) )
} ); 
```

With search util:
```javascript
Editor.create().then( ( editor ) => {
    editor.document.markers.add( 'name', editor.document.findRange( /something/ ) ) )
} );
```

**Comment by Reinmar** [comment]
I think you mixed up here a few things. Lack of constructors is one problem – it needs a separate issue. The `findRange()` method could be useful, but it doesn't make sense to build it in the `Document` class. We need a util. Which, like the other constructors, won't be easily available if you're just hacking things around.

BTW, id you'd bundle samples like you bundle the rest of the code, then you wouldn't have any problems.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-engine/issues/756.
