### ISSUE TITLE
Getters should be changed to methods.

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#76]
Getter: 

 - `Node.depth`,
 - `Node.root`,
 - `Node.nextSibling`,
 - `Node.previousSibling`,
 - `Position.nodeBefore`,
 - `Position.nodeAfter`

should be changed to methods `Node.getDepth()`...

**Comment by Reinmar** [comment]
It does not make sense to change `Node.nextSibling` to a method, because it's a getter in the real DOM. We need to make decision in https://github.com/ckeditor/ckeditor5-design/issues/88 first anyway.

**Comment by Reinmar** [comment]
We agreed that some things make for perfect properties even though they do not conform to our current code style rules. We're going to change the rules rather than make the code uglier, so I'm closing this ticket.
