### ISSUE TITLE
View.Writer.unwrap should be smarter

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#784]
Because mapper does not return the exact position view writer have to be smarter. For instance:

```
[]<strong><span class="foo"></span>bar</strong>

-> unwrap(<span class="foo"></span>) ->

[]<strong>bar</strong>
```

**Comment by scofalik** [comment]
This is closed by introducing `view.Range#getEnlarged` and `view.writer#clear` but has to be done "by hand" by the developer writing the code.
