### ISSUE TITLE
Model to view converters should accept null from the creator

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#790]
If the element creator passed to the converter returns `null` it means that this change should no be converted. The converter should do nothing is such case. Now they are crashing.

**Comment by scofalik** [comment]
At least some of converters should react correctly. Which one is crashing?

**Comment by pjasiun** [comment]
There is a high chance that it was fixed by https://github.com/ckeditor/ckeditor5-engine/pull/810.
