### ISSUE TITLE
Markers to UI converters

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#792]
When the `UIElement` will be introduced (https://github.com/ckeditor/ckeditor5-engine/issues/788) a Marker to UIElemnt converter is needed. It should take care about:
 - creating the UI Elemenet (duh!),
 - mapper, ensure that it will not crash because there is no model element for that view element (it might be needed to tell mapper what is the length of the element),
 - removing the UI Element (note that mapper will not return the exact position the UI element is and the converter needs to enlarge that position https://github.com/ckeditor/ckeditor5-engine/issues/789).

In the future we may consider also `attribute` to UI converter.

**Comment by scofalik** [comment]
Can you give any example where `attribute` to "UI Element" makes sense? The whole point about UI Elements is that you cannot put content inside it.

**Comment by pjasiun** [comment]
I mean that you may want to have an UI Element before (or after) every text with an attribute. But it's not a real case.

**Comment by scofalik** [comment]
This is doable with marker, though it won't stick to the letter. I'd rather enhance `LiveRange` to have stickiness like `LivePosition` in case it is collapsed and use markers for that. OTOH if you will need many UI elements like this markers may be less efficient 🤔

**Comment by pjasiun** [comment]
Don't care about it right now. It's just a random thought for the future, nothing to talk right now.
