### ISSUE TITLE
view.Position may end up in view.DocumentFragment

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#805]
`view.Position` may end up in `view.DocumentFragment`. This is a fact. It is partially supported but we have to fix:

1. Docs - at the moment docs say that `view.Position#parent` is a `view.Node`.
2. Some things may fail and we need to check if given tests exist:
    - creating `view.Position` in `view.DocumentFragment`, getting node after it and node before it,
    - methods in `Position` that use `#parent` ( `#getAncestors()`, `#compareWith()` ),
    - iterating using `view.TreeWalker`, over `view.DocumentFragment`.

**Comment by oskarwrobel** [comment]
Related: https://github.com/ckeditor/ckeditor5-engine/issues/802

**Comment by scofalik** [comment]
After more thought I would left point 3. on discussion.

> Remove getAncestors() from view.DocumentFragment and update view.Position#getAncestors().

I will write missing tests and I will fix #802, but removing `getAncestors()` needs further discussion. What will we do with `#parent` and `#root`? What do we do about same stuff in model? These were added precisely to fight some errors so removing them will for sure, sooner or later, end up with errors. This may need bigger refactor and I don't want to dive into it now.

**Comment by scofalik** [comment]
Reported #807.
