### ISSUE TITLE
One test to test them all.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#819]
I propose creating a manual test in `ckeditor5-engine` that will have all the official plugins and features enabled. The test will check editor integrity. It will be similar to what we have on https://ckeditor5.github.io but we will be able to test it when developing features.

**Comment by fredck** [comment]
It's a pity to have this in `ckeditor5-engine`... it should go into `ckeditor5`.

**Comment by scofalik** [comment]
It's not the most elegant, but this is probably the most right place for it.

Unless we create a separate package for it.

**Comment by fredck** [comment]
Or maybe the creators are the ones to have this, like `ckeditor5-editor-classic` and `ckeditor5-editor-inline`?

**Comment by scofalik** [comment]
I also thought about it, that `ckedtior5-editor-classic` is another good place to put it. But I am not sure. We will also have presets soon and that would be the best place to put it (check if all features in a preset work well together).

**Comment by Reinmar** [comment]
You won't ever want to load all features anyway. E.g. we don't load the MD DP at all right now. There will be more conflicting packages in the future – creators e.g.

That's said, if you want to test the engine with all the features, then you don't care much about the creator. You need the standard set of features and your idea about the presets is really interesting. I think it'd be a good place to test integration of sets of features. E.g. you won't need to care about all the devDeps.

Another matching place would be ckeditor5 itself. It's absolutely doable to place manual tests here, we just need to change one glob in ckeditor5-dev-tests. We can do that, but that's tiny bit more expensive so I guess that we'll go with presets, even though it's less perfect :).

**Comment by scofalik** [comment]
I needed that test to check list and image integration (list command active when image is selected bug). I just thought that for sure we will have more cases like this and when introducing new feature we should test it together with all the others. I don't know when we will have presets. If it's soon future, then I can live without having the one test. But I know that some may be waiting for it.

**Comment by Reinmar** [comment]
If there are no major issues with my proposal in https://github.com/ckeditor/ckeditor5/issues/399, I can bootstrap this next week. Fortunately, presets are an extremely simple concept :)

**Comment by scofalik** [comment]
Noone besides me commented on them and I mostly agreed so I guess that there are no objections.

**Comment by Reinmar** [comment]
As mentioned in https://github.com/ckeditor/ckeditor5-engine/pull/820#issuecomment-284674017 – the integration tests will be provided by presets and builds.
