### ISSUE TITLE
Why was Document#_roots made public?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#844]
I see it was made public in https://github.com/ckeditor/ckeditor5-engine/pull/813. Why? Couldn't it be protected if the dev utils need to access them? Besides, wasn't `Document#getRootNames()` + `Document#getRoot()` + `Document#graveyard` enough?

**Comment by Reinmar** [comment]
cc @scofalik @szymonkups

**Comment by scofalik** [comment]
AFAIR, it was made public during writing logging tools for engine. I noticed that the implementation between `ModelDocument` and `ViewDocument` is different. I haven't seen that `ModelDocument` has `getRootNames` though.

If that's the case, we can think of unifying the implementations by making `_roots` private for both model and view document, and introduce `getRootNames()` for `ViewDocument`.

**Comment by Reinmar** [comment]
I think it's gone now, so closing.
