### ISSUE TITLE
Move dev utils to utils

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#866]
If I want to create an image with caption in tests I do:

```js
const imageElement = parse( '<image src="foo.png"><caption>foo bar</caption></image>' );
```

If I want to create an image with caption in the source I do:

```js
const imageElement = new Element( 'image', { src: 'foo.png' } );
const captionElement = new Element( 'caption', null, 'foo bar' );
const imageElement.appendChild( imageElement );
```

Not that much code to write, but it's a part of the API you need to remember or check how to use. XML syntax is much simpler to use, even if it's less efficient.

Also, note that if we will go with https://github.com/ckeditor/ckeditor5-engine/issues/858, this might be a way to create a part of the document tree without additional move operation.

**Comment by Reinmar** [comment]
I don't like this idea at all. By sticking to string format you'll create lots of XSS and other stability issues. You will need to remember to secure all the variables which you put in the template. Seems obvious but the past shows it's not. Even if we do remember about it you can't guarantee that others will. Plus... if "foo bar" (the caption's text) came from a variable you'd need a specialised anti-XSS library to clean this up.

Therefore, I'm absolutely against allowing creating elements using a syntax like this. If anything, let's work on defining a useful creators in #858.

**Comment by pjasiun** [comment]
Yea, I was also very unsure if it makes sense to report it, even without XSS it looks like a bad practice. So I am closing the issues.
