### ISSUE TITLE
Schema: allow all

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#878]
It should be possible to allow all elements in given element. I see it along these lines:
`schema.allow( { name: '*', inside: 'elem' } );`. `elem` chould be `$root` for example.

**Comment by pjasiun** [comment]
It's not enough to allow all. For instance, if one adds `quote` to `root` and then wants to add `paragraph` to that `quote` the config "Allow * inside root" will disallow adding `paragraph` in `quote`. We need "Allow * inside *":
```
schema.allow( { name: '*', inside: '*' } );
```

Also, we should be able to allow any attribute on any element.

**Comment by Reinmar** [comment]
Why do we need all this?

**Comment by Reinmar** [comment]
I'll close this as it's all part of #532. But please answer because I need to know why we need this.
