### ISSUE TITLE
Mapper: default position mapping algorithms may crash editor.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#884]
At the moment, model-to-view and view-to-model position mapping use first the default algorithm and then additional callbacks may be fired and alter the position calculated using default algorithm.

This behaviour sounds okay, but is a problem in `List` feature because for some list structures the default algorithm throws.

Hence I propose that default algorithm should be used only if no custom callback has been used.

**Comment by Reinmar** [comment]
Unfortunately, #885 blew up other features: https://travis-ci.org/ckeditor/ckeditor5/builds/214576912

**Comment by Reinmar** [comment]
And in MQ manual tests (on editor load):

![image](https://cloud.githubusercontent.com/assets/156149/24292167/72a55864-108c-11e7-9d66-bf7d46fb422b.png)

**Comment by scofalik** [comment]
Those errors are because of model-to-view position mapping callback for `List` feature. They will disappear after PR in `List` is merged.
