### ISSUE TITLE
DataController.insertContent() and insertContent event have incorrect docs

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#895]
We allowed passing an element to `insertContent()` function, but the docs of the method and event weren't updated and the change weren't tested on `DataController.insertContent()`.

**Comment by ma2ciek** [comment]
Do we have to test this change in the `DataController` if the `DataController#insertContent` fires only an event?

**Comment by ma2ciek** [comment]
Now I see, that actually one test is missing... I'll add it.
