### ISSUE TITLE
LiveSelection: LiveRanges are not detached correctly.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#903]
In https://github.com/ckeditor/ckeditor5-engine/issues/780#issuecomment-291171133 I've found a memory leak in `LiveSelection`. `LiveRange` callbacks are not correctly detached.

**Comment by jodator** [comment]
BTW: https://github.com/ckeditor/ckeditor5-engine/pull/904#issuecomment-337627487 As I wrote in PR rather then in issue.
