### ISSUE TITLE
Remove invaild catches from replayer 

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-engine#906]
[These catches](https://github.com/ckeditor/ckeditor5-engine/pull/902/files/dd3015b82786b648e0c77f949c79d8a0cace4ca3#diff-891fb910d1bb2fa1a25f134274923658R103) should be changed in order to provide some correct errors.

**Comment by Reinmar** [comment]
They are rather unnecessary – if the function return a promise it's usually enough when the caller handles errors.

**Comment by ma2ciek** [comment]
Yes. But they were designed to handle errors from the [applyNextDelta](https://github.com/ckeditor/ckeditor5-engine/pull/902/files/dd3015b82786b648e0c77f949c79d8a0cace4ca3#diff-891fb910d1bb2fa1a25f134274923658R119) method as I didn't notice that this can conflict with the errors coming from the engine

**Comment by Reinmar** [comment]
OK, so this is a bit beyond of my knowledge of this code and its application. So, my only point remains that there should be no silent catches. The rest is up to you :)

**Comment by ma2ciek** [comment]
I changed the `applyNextDelta` method and now it resolves also when there is no delta to replay. Thus, the methods that uses  `applyNextDelta` can correctly capture the engine errors, e.g. the `play` method ([test](https://github.com/ckeditor/ckeditor5-engine/pull/908/commits/1466f76c16ad4a0aa68233fd49928ee3d3efe4dc#diff-14eb683c43b821201ba7edab37c45845R151)).
