### ISSUE TITLE
Disappearing placeholder

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#916]
It's easy to play editor content in a way that placeholder disappears.

![apr-10-2017 10-23-42](https://cloud.githubusercontent.com/assets/1057056/24852571/489f6e02-1dd8-11e7-9ef3-e6908ffe4c41.gif)

**Comment by scofalik** [comment]
Isn't it just a case of removed element? If the placeholder was on an element and the element got removed, no wonder there is no placeholder.

**Comment by oskarwrobel** [comment]
I'm expecting when the editor is empty I see the placeholder.

**Comment by szymonkups** [comment]
:point_up: 
We may think about adding functionality to placeholder allowing it to be placed on the document root. It seems like it might be a common scenario.

**Comment by Reinmar** [comment]
It'd be lovely to allow configuring placeholders for every editor. I'd love to have it as a config option.

**Comment by scofalik** [comment]
@szymonkups Wouldn't it work already? We can add attributes on root model elements, however I am not sure about conversion or exact placeholder implementation.

**Comment by szymonkups** [comment]
> @szymonkups Wouldn't it work already? We can add attributes on root model elements, however I am not sure about conversion or exact placeholder implementation.

I will test it.

**Comment by Reinmar** [comment]
I found this ticket really confusing. At the beginning it's about a bug to later become a feature ticket :D.

So, let's have a proper feature request: https://github.com/ckeditor/ckeditor5/issues/479. We'll start from there and see where it leads us.
