### ISSUE TITLE
Introduce "autohoisting" during view-to-model conversion.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#924]
Autohoisting concept is described here: https://github.com/ckeditor/ckeditor5-paragraph/issues/10

Simply, the idea is that if an element cannot be converted in its current context (because schema does not allow for it), try moving it out of its parent (break parent) and convert in new context. The most basic example is: `<p>x<img />y</p>` -> `<p>x</p><img /><p>y</p>`.

The idea was to have a generic view-to-model converter for all `element`s, set with `low` (not `lowest`) priority so it will be fired before autoparagraph converter and to-model-fragment converter.

Unfortunately an idea to have some kind of generic converter is problematic. The generic converter would have to:

1. Check if the element has not been yet consumed.
2. Check if the element could be converted in other context.
3. Convert element like it was in that context.
4. Somehow mark where parents should be broken to allow the element to be in correct context.

Step 2. is difficult, because in generic converter, we would not know what is the model name of converted view element. We could add an easy-to-use default converter though, something that would be used like this:
```javascript
// Assume custom converter for `<myCustom>` view element that creates `my-custom` element in model.
data.viewToModel.on( 'element:myCustom', myCustomConverter );
// Register that for `<myCustom>` view element, auto-hoisting should assume that it is converted to `my-custom` model element.
data.viewToModel.on( 'element:myCustom', autohoist( 'my-custom' ) );
```
This could be also used in `ViewConverterBuilder` but each time custom callback is provided, user will have to add autohoisting for that view element.

Step 4. is difficult because when converting element that should be autohoisted, we don't have its parent content, not to say that we don't have access to `data.output` that will be returned by autohoisted element's parent. So we don't know how and where we should break parent.

This all leads me to a conclusion, that maybe it is actually a better idea to convert everything without looking at schema but at the end of conversion clear the model: autohoist what can be autohoisted, autoparagraph what can be autoparagraphed, remove all the rest?

**Comment by scofalik** [comment]
> This all leads me to a conclusion, that maybe it is actually a better idea to convert everything without looking at schema but at the end of conversion clear the model: autohoist what can be autohoisted, autoparagraph what can be autoparagraphed, remove all the rest?

The idea seemed neat and would allow us to "forget" about schema checks in converters. I tried it but unfortunately there are some obstacles:

1. If we allow all conversion by default and then clean "bad" stuff we run into problem when converting unrecognized, non-paragraph-like elements:
`<section>foo</section>` first is converted by default to-document-fragment converter but then cleaning-converter does not know whether it should clean it (in this case - no).
2. Assume that bold is not allowed on text in paragraph and we have text in paragraph:
`<paragraph>foo</paragraph>`. Then we apply bold: `<paragraph><$text bold=true>foo</$text></paragraph>`. Then we do cleaning and ... have empty paragraph.

So unfortunately we can't go this route (or at least it will require complicated algorithms -- and this idea was to simplify things in the first place).

**Comment by scofalik** [comment]
I've updated previous comment (the list with problems).

Now I'll try the other approach with `autohoist` converter (described in first post).

**Comment by scofalik** [comment]
Okay, this one might be difficult too, also because of attributes :/.

Let's assume this is our `autohoistElement` converter:

```javascript
export function autohoistElement( modelElementName ) {
	return ( evt, data, consumable, conversionApi ) => {
		if ( consumable.test( data.input, { name: true } ) ) {
			const allowedContext = _findAllowedContext( modelElementName, data.context );

			if ( allowedContext ) {
				// Convert in allowed context.
				// Mark converted element so we will later know to autohoist it.
				// Add to `data.output`.
			}
		}
	};
}
```
Looks fine, right? But what about attributes? In default conversion, possible attributes are applied after the element itself is converted. There can be two "bad" scenarios:
1. Element can be autohoisted if it doesn't have any attributes but later gets some attributes and cannot be autohoisted anymore.
2. Element could be autohoisted with attributes, but the converter above does not know about this and do not convert element (so the element is "cleared").

The first scenario is not that bad because we can re-check if there is any allowed context. Second one is more difficult though, cause we would have to pass to `autohoistElement` some additional parameter/function describing how to check what attributes the element will have. This is unwelcome when you think about `ViewConverterBuilder` because you cannot then automatically use `autohoistElement` there.

Back to drawing board...

**Comment by scofalik** [comment]
> This is unwelcome when you think about `ViewConverterBuilder` because you cannot then automatically use `autohoistElement` there.

Okay, I see that it actually might be possible to use it there:
```javascript
// Create model element basing on creator function or element name.
const modelElement = element instanceof Function ? element( data.input ) : new ModelElement( element );

// Check whether generated structure is okay with `Schema`.
const keys = Array.from( modelElement.getAttributeKeys() );

if ( !conversionApi.schema.check( { name: modelElement.name, attributes: keys, inside: data.context } ) ) {
	continue;
}
```
This part of code of `toElement()` method actually performs similar check... Episode 4: A New Hope.

**Comment by scofalik** [comment]
This PR https://github.com/ckeditor/ckeditor5-image/pull/107 introduces autohoisting for images.

Autohoisting converters were written using ideas described in this issue. Actually most of the converters code is pretty generic. There are probably two places that should be generalised:

https://github.com/ckeditor/ckeditor5-image/blob/t/98/src/image/converters.js#L117
```javascript
if ( !consumable.test( img, { name: true, attribute: [ 'src' ] } ) ) {
	return;
}
```

https://github.com/ckeditor/ckeditor5-image/blob/t/98/src/image/converters.js#L124
```javascript
const allowedContext = _findAllowedContext( { name: 'image', attributes: [ 'src' ] }, data.context, conversionApi.schema );
```

These two have some hardcoded stuff connected strictly to how `image` works. This could be generalised by making the converter accept some parameters - either direct or some callbacks generating needed data.

Apart from that and the variable name: `const autohoistedImages = new WeakSet();` rest of the code is generic.

**Comment by Reinmar** [comment]
Status of things:

1. Autohoisting was added in the image feature.
2. We still need some generic mechanism in the engine which would allow feature developers to add autohoisting to their features.

**Comment by pjasiun** [comment]
We introduced general autohoisting in https://github.com/ckeditor/ckeditor5-engine/issues/1213.
