### ISSUE TITLE
[Edge] Selection made by mouse gets stuck (freezes) in some cases

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#928]
First spotted in https://github.com/ckeditor/ckeditor5/issues/423.

![Selection issues on Edge](https://cloud.githubusercontent.com/assets/156149/25149623/5d31a562-247f-11e7-8cff-0e22de3fbb63.gif)

So I thought that this is a problem with CKEditor 5 itself. I also noticed some issues with selection being lost or frozen on focus/blur, but then I tested that all events are fired fine and I also noticed that the same issue is reproducible in CKEditor 4:

![apr-21-2017 14-36-50](https://cloud.githubusercontent.com/assets/156149/25277864/b6b730b6-26a0-11e7-86bb-89e1e3cb2e65.gif)

This means that it's not CKEditor's problem as CKEditor 4 does nothing to the selection.

CKEditor 5 sometimes fixes selections if they got fixed when passed through view->model->view pipeline but, fortunately, this doesn't seem to cause any issues. Even when I'm making selection by dragging and the engine decides that it needs to re-render the selection, it doesn't break anything.

**Comment by Reinmar** [comment]
I reported it to MS: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11746000/, but there's a high chance that we'll have to find the trigger for this bug because it doesn't appear to be reproducible in a bare contenteditable.

**Comment by Reinmar** [comment]
It's still reproducible on http://ckeditor.com, but for some reasons I couldn't reproduce it in CKEditor 5.

However, I also noticed some issues when selection was reaching edges of inline styling and widgets. I can't reproduce them consistently, though.

**Comment by Reinmar** [comment]
Another case – https://github.com/ckeditor/ckeditor5/issues/484.

Since @Mgsy confirmed that this particular case works fine in CKE4 we need to investigate how CKEditor 5 triggers it.

A couple of ideas:

* Different styling?
* Rendering after selection change which breaks selection-by-mouse-dragging.
* Some volatile and unrelated trigger which breaks this in Edge.

**Comment by Mgsy** [comment]
I found another issues related to selection on Edge : 

1. Selection started at the marker can't be moved outside of it.

![bug_cke5](https://user-images.githubusercontent.com/20988892/27588513-b532392a-5b48-11e7-8ee8-fdd64e0aaa6a.gif)

2. There's no possibility to select the marker character by character, because whole word receives selection immediately. 

![bug_cke5](https://user-images.githubusercontent.com/20988892/27588645-2aa764f0-5b49-11e7-851c-49dec7c5e503.gif)

**Comment by Reinmar** [comment]
Isn't the latter a standard Edge's behaviour when selecting text? It often extends the selection to whole words.

**Comment by Mgsy** [comment]
> Isn't the latter a standard Edge's behaviour when selecting text? It often extends the selection to whole words.

It is, but this behaviour occurs if you extend the selection to more than one word. Basically, you are able to select first word character by character. 

![bug_cke5](https://user-images.githubusercontent.com/20988892/27589230-037e17e6-5b4b-11e7-8c1f-4dc4fb91642b.gif)

Anyway, it's a tiny issue :)

**Comment by Mgsy** [comment]
Here is another case related to the selection on Edge. 

![bug_cke5](https://user-images.githubusercontent.com/20988892/27857027-6e7b8f12-6170-11e7-9192-d750d028bff9.gif)

**Comment by ma2ciek** [comment]
Some new(?) case:

1. Bold some fragment
1. Try to select text from the bold's boundary.

Result: cursor is stuck. I've checked and it works in CKE4.

**Comment by ma2ciek** [comment]
It works in CKE4 and doesn't work in CKE5 (https://ckeditor5.github.io/). I can check if it is not a regression.
