### ISSUE TITLE
ViewConverterBuilder#toAttribute may return array as conversion result.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#932]
`ViewConverterBuilder#toAttribute()` may return array as conversion result. This may happen when view element is converted to model attribute: https://github.com/ckeditor/ckeditor5-engine/blob/master/src/conversion/buildviewconverter.js#L369

Here, `convertChildren` returns array which is then passed as `data.output`.

The solution is to wrap `convertChildren` result in `model.DocumentFragment`.

**Comment by Reinmar** [comment]
We changed the scope of this ticket during the review https://github.com/ckeditor/ckeditor5-engine/pull/933#issuecomment-296743306.
