### ISSUE TITLE
Consider simplifying attribute conversion

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#945]
Looking at the image feature converters I particularly didn't like this piece:

```js
export function createImageAttributeConverter( dispatchers, attributeName ) {
	for ( let dispatcher of dispatchers ) {
		dispatcher.on( `addAttribute:${ attributeName }:image`, modelToViewAttributeConverter );
		dispatcher.on( `changeAttribute:${ attributeName }:image`, modelToViewAttributeConverter );
		dispatcher.on( `removeAttribute:${ attributeName }:image`, modelToViewAttributeConverter );
	}
}

function modelToViewAttributeConverter( evt, data, consumable, conversionApi ) {
	const parts = evt.name.split( ':' );
	const consumableType = parts[ 0 ] + ':' + parts[ 1 ];

	if ( !consumable.consume( data.item, consumableType ) ) {
		return;
	}

	const figure = conversionApi.mapper.toViewElement( data.item );
	const img = figure.getChild( 0 );

	if ( parts[ 0 ] == 'removeAttribute' ) {
		img.removeAttribute( data.attributeKey );
	} else {
		img.setAttribute( data.attributeKey, data.attributeNewValue );
	}
}
```

Couldn't we have just one event and the type of change as a data property? Could we simplify that consumable check code too? Maybe we could also have a shorthand method in `Element` – like `updateAttribute()` to avoid having to use both `remove/setAttribute()` methods.

**Comment by scofalik** [comment]
Why converter builder has not been used?

**Comment by Reinmar** [comment]
cc @szymonkups – there was some reason AFAIR. But you're right that my ticket should be about improving the builder as well.

**Comment by szymonkups** [comment]
If I remember correctly, with builder we cannot specify that we want to convert attribute only from given element. For example: "convert `src` attribute only from `image` elements".

**Comment by scofalik** [comment]
I can also see that there is `figure` involved in here, which looks like is mapped to the original `data.item`.

**Comment by szymonkups** [comment]
I was mentioning this here: https://github.com/ckeditor/ckeditor5-engine/issues/736.

**Comment by Reinmar** [comment]
Code sample that we need to improve: https://github.com/ckeditor/ckeditor5-image/pull/32/files#diff-181a641e45476f54a783a7ad41ed6f5bR101

**Comment by pjasiun** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-engine/pull/1274 and other refactoring tickets.
