### ISSUE TITLE
Revise `RemoveOperation` transformation

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#948]
Since `RemoveOperation` was created as a special kind of `MoveOperation`, a lot of conceptions changed around it. For all that time, `RemoveOperation` was considered a `MoveOperation` in transformation algorithms. This lead to creating some hacks (for example there are a few `if`s in `MoveOperation` x `MoveOperation` transformation).

I am not sure if some case were not missed, so I propose to revise `RemoveOperation` transformation. This might have an impact on OT stability (including undo feature).

Ideas are:
1. Rethink exactly cases for `RemoveOperation`. Make it have separate transformation algorithms.
2. Rethink whether `RemoveOperation` could be written in a way that holder elements are always put at the end of `$graveyard`. Another suggestion was to create separate graveyard root for each operation or try other solutions for synchronisation of detached trees.
3. Rethink whether it is possible to make `RemoveDelta` an `InsertOperation` + `RemoveOperation`.

Thing is that `RemoveOperation` was getting more and more complicated and I think it will be valuable to take a look back (again...) and see whether we go in right direction.

**Comment by Reinmar** [comment]
> Another suggestion was to create separate graveyard root for each operation or try other solutions for synchronisation of detached trees.

Just to make it clear – the graveyard names could be randomised to avoid conflicts. So, the only thing would be then to sent new roots (and their content) to other users.

**Comment by scofalik** [comment]
Related:

https://github.com/ckeditor/ckeditor5-engine/issues/950
https://github.com/ckeditor/ckeditor5-engine/issues/954

**Comment by scofalik** [comment]
> Another suggestion was to create separate graveyard root for each operation or try other solutions for synchronisation of detached trees.

To avoid bigger refactoring we may also introduce intermediate solution:
1. Introduce `GraveyardRootElement`.
2. Make `GraveyardRootElement#_children` a `Map` instance.
3. Change `GraveyardRootElement#insertChildren` to just `Map#set`. `appendChildren` would have to throw an error, unfortunately :(.
4. Graveyard holders would be put in "hashed" offsets.

This demands some changes in OT (any solution would though). But at least it should minimze changes in other parts of code.

**Comment by scofalik** [comment]
I am revising some ideas around undo and `RemoveOperation`. I am doing this, because at the beginning we have that bright idea that `RemoveOperation` could be just a `MoveOperation` and it should just work, if `MoveOperation` works. But then something went wrong and I am figuring out what.

I focused on history compression. On undo, deltas in history becomes compressed. Do we need? What harm does it bring? What problems does it solve?

I was trying to figure out whether we can get rid of it because of following issue. Consider batch with two deltas/operations:
```
INSERT image AT [ 0 ]
INSERT caption AT [ 0, 0 ]
```
Then consider undoing this:
```
~~~INSERT image AT [ 0 ]~~~
~~~INSERT caption AT [ 0, 0 ]~~~
~~~REMOVE [ 0, 0 ] -> graveyard [ 0, 0 ] (caption)~~~
~~~REMOVE [ 0 ] -> graveyard [ 1, 0 ] (image)~~~
```
When upload is aborted, `image` plugin removes that image (again):
```
~~~INSERT image AT [ 0 ]~~~
~~~INSERT caption AT [ 0, 0 ]~~~
~~~REMOVE [ 0, 0 ] -> graveyard [ 0, 0 ] (caption)~~~
~~~REMOVE [ 0 ] -> graveyard [ 1, 0 ] (image)~~~
REMOVE graveyard [ 1, 0 ] -> graveyard [ 2, 0 ] (image)
```
This seems valid. Thanks to that, we won't insert that image again on redo:
```
~~~INSERT image AT [ 0 ]~~~
~~~INSERT caption AT [ 0, 0 ]~~~
~~~REMOVE [ 0, 0 ] -> graveyard [ 0, 0 ] (caption)~~~
~~~REMOVE [ 0 ] -> graveyard [ 1, 0 ] (image)~~~  on reverse --> REINSERT graveyard [ 1, 0 ] -> [ 0 ]
REMOVE graveyard [ 1, 0 ] -> graveyard [ 2, 0 ] (image) on transform --> NOOPERATION (REMOVE is stronger)
NOOPERATION
```
But another redo is invalid. Caption has not been extra- removed. Since delta below has been compressed and removed from history, the script does not know that image has been removed:
```
~~~INSERT image AT [ 0 ]~~~
~~~INSERT caption AT [ 0, 0 ]~~~
~~~REMOVE [ 0, 0 ] -> graveyard [ 0, 0 ] (caption)~~~ --> REINSERT graveyard [ 0, 0 ] -> [ 0, 0 ]
~~~REMOVE [ 0 ] -> graveyard [ 1, 0 ] (image)~~~ --> no change on transform
REMOVE graveyard [ 1, 0 ] -> graveyard [ 2, 0 ] (image) --> no change on transform
NOOPERATION --> no change on transform
REINSERT graveyard [ 0, 0 ] -> [ 0, 0 ]
```

On the other hand here as a counter example showhing why we introduced history compression. Assume model is text 'abc':
```
REMOVE [ 1 ] -> graveyard [ 0, 0 ] (b) 
REMOVE [ 0 ] -> graveyard [ 1, 0 ] (a)
REMOVE [ 0 ] -> graveyard [ 2, 0 ] (c)
REINSERT gy [ 2, 0 ] -> [ 0 ] (undo remove c)
REINSERT gy [ 1, 0 ] -> [ 0 ] (undo remove a)
```
After two removing `b` `a` and `c` and making two undos we have state above. Now undo last remove:
```
REMOVE [ 1 ] -> graveyard [ 0, 0 ] (b)     --> REINSERT [ 0, 0 ] -> [ 1 ]
REMOVE [ 0 ] -> graveyard [ 1, 0 ] (a)     --> after transform: REINSERT [ 0, 0 ] -> [ 0 ]
REMOVE [ 0 ] -> graveyard [ 2, 0 ] (c)     --> no change on transformation
REINSERT gy [ 2, 0 ] -> [ 0 ] (undo remove c) --> no change on transformation
REINSERT gy [ 1, 0 ] -> [ 0 ] (undo remove a) --> no change on transformation
REINSERT gy [ 0, 0 ] -> [ 0 ] (undo remove b)
```
Which is obviously wrong.

This leds us to a conclusion that we need some kind of "helping tool" or "indicator" that gives some context to undo, because as we can see, just reversing and transforming operations is not enough. But history compression is incorrect tool.

**Comment by scofalik** [comment]
Here's a new plan for undo and redo.

1. Get rid of history compression.
2. Get rid of graveyard holder.
3. Revert `RemoveOperation` and `ReinsertOperation` to be similar to `MoveOperation` (or even get rid of them and just implement "smart" `MoveOperation#type`).
4. Implement contextual deltas ignoring in undo and redo.

How will it work? Example for undo (it is similar for redo).

First observation is that "context" is needed only for move operations (move, remove, reinsert). Insert adds new node, so there is no context. Other operations do not change tree structure so context is not important either.

Second observation is that "context" is needed only when moving nodes that were "close to each other", or, being more general, had same parent. Our problem now is with positioning, when undoing operation moves to the same position as undoing operation which was already applied. 

Hopefully, those two are true and there aren't any more tricky cases.

So, having those two in mind, here is the problem. We have to find relation between processed move operation and already applied undone+undoing operation, if the applied undone operation moves node from the same parent as the operation that we are just undoing. You may checkout the "abc example" from post above.

When looking for a way to find that relation I had an idea that we could maybe just ignore the undone+undoing operation pair (if "same parent" condition is met). That would be kind of "dynamic history compression" which would behave as we would like in both examples from post above.

I've already check that similar issues and solution apply to redo.

There are two things to check:
1. How will it fare with not-undoable operation somewhere in between.
2. Will this approach handle a situation where moved node from processed operation changes parent(s) somehow in meantime.

**Comment by scofalik** [comment]
> There are two things to check (...)

I found counterexample with those two things to check combined, when this approach doesn't work. We just can't remove stuff from history, period.

Let's find another way how to do it.

**Comment by scofalik** [comment]
Another idea.

When processing current undoing operation, when it is transformed by an undone operation, check and save, whether undone operation has a node that was before or after node connected with current undoing operation. This will be "context" information. Then, this information will be used when current undoing operation will conflict with already applied undoing operation to resolve whether it should be inserted after or before.

This nicely solves the counterexample I mentioned before but that "context" information would be used directly in transformation algorithms. This means that undo would have to be directly coupled with transformation. Or undo will have to overwrite transformations. It's all doable but I don't know how pretty the code will be and how much refactoring we need.

Also I have to check how to generalize this solution to work with ranges, instead of singular nodes.

**Comment by scofalik** [comment]
> Also I have to check how to generalize this solution to work with ranges, instead of singular nodes.

It looks that it is fine, even for operations that are split into two operations. Now the question is how to implement it in a nice way, so undo feature "needs" are not directly coded inside transformation algorithms? This will be tricky.

**Comment by scofalik** [comment]
`MoveOperation` x `MoveOperation` transformation has changed greatly. `RemoveOperation` itself got simplified in the process too. A lot of ideas from this issue has been implemented in the mean time.

I see this issue as solved. It was supposed to be closed earlier.
