### ISSUE TITLE
`AttributeDelta` x `SplitDelta` transformation crashes if `SplitDelta` has `ReinsertOperation`

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#950]
As the title says: `AttributeDelta` x `SplitDelta` transformation crashes if `SplitDelta` has `ReinsertOperation`.

`SplitDelta` has a `ReinsertOperation` (instead of `InsertOperation`) if it was created as reverse of `MergeDelta`. It has to be rethought whether this is a good idea. The code throws because if split element has attribute change, we need to add extra attribute operation and it has to have proper old value. If the `SplitDelta` has `InsertOperation`, old value can be read from that operation's node. But `ReinsertOperation` does not have a node. Maybe it should? Maybe it should work differently than now? Maybe we don't need `AttributeOperation#oldValue` (at least in constructor?).

**Comment by scofalik** [comment]
This is actually super tricky :(.

The ideas were three:
1. Drop `oldValue` in `AttributeOperation` if it wasn't applied now. Problem: `AttributeOperation` cannot be reversed unless it was applied, this is a hypothetical problem in OT, I don't know if we need to reverse such `AttributeOperation`s right now, but the problem will be that you would be able to reverse any operation except of `AttributeOperation`, which stinks. Unless we make some strict rules when you can reverse operations, but sometimes we have to do it during OT.
2. Make `SplitDelta` always create `InsertOperation`, even if it was reversed, but once again we have same problem -- if we are reversing in the middle of OT process, we don't know which node exactly is split.
3. Add `SplitDelta#nodes` and add "inserted node" there by hand. It is easy for `InsertOperation`, of course, but unfortunately since `RemoveOperation` affects other `RemoveOperation` we cannot do it, because once again, if in the middle of OT, we cannot find the node in the graveyard.

Possibly the best solution might be to abandon special case for this transformation for now. However this would mean that also same case for `RenameDelta` should be abandoned.

Where it would matter?

For example, assume collaborative editing of document that has a paragraph:
`<paragraph>Foobar</paragraph>`.
Client A splits: `<paragraph>Foo</paragraph><paragraph>Bar</paragraph>`.
Client B changes to list item: `<listItem type="bulleted" indent=0">Foobar</listItem>`.

The best result would be:
```
<listItem type="bulleted" indent=0">Foo</listItem>
<listItem type="bulleted" indent=0">bar</listItem>
```

If we drop the special case it will be:
```
<listItem type="bulleted" indent=0">Foo</listItem>
<paragraph>bar</paragraph>
```

BTW. It is kinda related to the issue I've added recently: https://github.com/ckeditor/ckeditor5-engine/issues/948. It would be much easier if `RemoveOperation` would never affect other `RemoveOperation`, but as for now, they do.

**Comment by scofalik** [comment]
Plot twist: I checked transformations and it appears that we don't use operations reversing in operations transformations but we use reversing of deltas in deltas transformations (which uses operations reversing).

Thankfully, we only reverse deltas that were already applied. This means that there is hope, that in current state, we could get rid of things like `AttributeOperation#oldValue` and `MarkerOperation#oldRange`.

**Comment by Reinmar** [comment]
What's the status of this?

**Comment by scofalik** [comment]
Transformation case got modified and is not applied when `SplitDelta` has operation other than `InsertOperation`.
