### ISSUE TITLE
Webpage scrolls when view's DomConverter focuses an element

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-engine#951]
It's a WebKit-specific behavior that makes the web page scroll to the beginning when editing view is focused. I see no other solution than post-focus `window.scrollTo` to fix the position of the scrollbar.

Note that Image text alternative balloon also suffers because of this.

A follow-up of https://github.com/ckeditor/ckeditor5-link/issues/100.

**Comment by oskarwrobel** [comment]
This fix should take into consideration not only window scroll but also editable scroll.

![may-11-2017 17-30-12](https://cloud.githubusercontent.com/assets/1057056/25957908/a705c63a-366f-11e7-9b14-d9801b773e79.gif)

**Comment by oleq** [comment]
@oskarwrobel Do you think that moving to previously cached `scrollTop` and `scrollLeft` of the element [here](https://github.com/ckeditor/ckeditor5-engine/pull/952/files#diff-4f185b1b840fc6d03b079b8cd12b27ebR746) would resolve it completely?

**Comment by oskarwrobel** [comment]
I'm afraid not. But restoring scroll only on window object doesn't fix it completely. We should create a manual test with few nested scrolled containers and check.

**Comment by oleq** [comment]
@oskarwrobel I [extended](https://github.com/ckeditor/ckeditor5-engine/pull/952/commits/60caaf4ff7968e479bf79630f0e8981b7303a608) the fix and it looks like it works for editables with `overflow:scroll`.
