### ISSUE TITLE
Fix CC

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#959]
![image](https://cloud.githubusercontent.com/assets/156149/26162851/282ea4ae-3b28-11e7-94a1-eda5cbdd1aa3.png)

In `dev-utils/enableenginedebug.js`.

**Comment by Reinmar** [comment]
Introduced in https://github.com/ckeditor/ckeditor5-engine/pull/942.

**Comment by Reinmar** [comment]
@ma2ciek, could you take it over from @scofalik?

**Comment by ma2ciek** [comment]
Sure. I'll take it.
