### ISSUE TITLE
Gitignore have wrong settings

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-engine#960]
I  think that gitignore should have:
```.gitignore
node_modules/
````
Look at trailing space that denotes folder.

not:
```.gitignore
node_modules/**
```

So it would ignore whole node_modules folder.

As in [gitignore patterns](https://git-scm.com/docs/gitignore#_pattern_format).

**Comment by Reinmar** [comment]
What's wrong with `**`?

> A trailing "/**" matches everything inside. For example, "abc/**" matches all files inside directory "abc", relative to the location of the .gitignore file, with infinite depth.

The only difference I know is that `node_modules/` matches all `node_modules/` directories anywhere and `node_modules/**` only the one relative to `.gitignore`.

**Comment by jodator** [comment]
`foo/**` does not match `foo` folder itself which might be problematic if it happens to be a git repository.
If it is a git repository then git will treat `foo` as submodule and will add it as such. As for `node_modules` this shouldn't be a case but anyway using `foo/` for ignoring a folder looks like a best practice.

The `foo/**` will match all directories:
- `./foo`
- `./baz/foo`
- ./baz/bar/foo`

If you want to ignore only "root" foo, you'd write: `/foo/`.

**Comment by Reinmar** [comment]
So, do you want to make `node_modules` a subrepository?

**Comment by jodator** [comment]
> So, do you want to make node_modules a subrepository?

You are tottally missing a point here. For `node_modules` itself it is save since no one would make it git repository there.

The main point is that: To exclude a folder from git you should use `node_modules/` not `node_modules/**` as it a common practice, better describes what it excludes.

As an example look at [this examples](https://github.com/github/gitignore) most of them have `foo/` notation for excluding directory not `foo/**`. If there is a `foo/**` the most common reason is to un-exclude some path from withing excluded folder:

```gitignore
/foo/*
!/foo/bar/*
```

Current setting works but might be better since for me `foo/**` might lead to side effects so why not write `foo/` as it should be, including for `node_modules` case.

**Comment by Reinmar** [comment]
OK, I just wanted to understand what's the reasoning here because it might be a bit more work for us. The `node_modules/**` notation comes from the CKEditor boilerplate project and was meant to work well with `gulp` (it was passed to JSCS and JSHint after some transformations). I think this is not needed anymore, but it may turn out that it is and then it won't be such a simple change.

**Comment by Reinmar** [comment]
Besides, we need to change this in all repos ;)

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5/issues/456.
