### ISSUE TITLE
Selection is incorrectly rendered when performing certain actions

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#992]
See:

* https://github.com/ckeditor/ckeditor5-engine/issues/711#issuecomment-309722442
* https://github.com/ckeditor/ckeditor5/issues/453
* https://github.com/ckeditor/ckeditor5-basic-styles/issues/46 (the reported bug is fixed, but you can observe the problem with selection and performing that steps)
* https://github.com/ckeditor/ckeditor5-engine/issues/701
* https://github.com/ckeditor/ckeditor5-engine/issues/741#issuecomment-319896039

---

![italic_blockquote_1](https://user-images.githubusercontent.com/422571/38137046-a470168a-3422-11e8-9a3a-5ace5945b15c.gif)

---

![italic_blockquote_2](https://user-images.githubusercontent.com/422571/38137047-a671bcf4-3422-11e8-8bdb-26ba32a60251.gif)

**Comment by Reinmar** [comment]
When reproducing https://github.com/ckeditor/ckeditor5-basic-styles/issues/46 I noticed that the model selection is, most likely, correct. It's only rendering problem. But since the incorrect DOM selection doesn't change the model selection it may be that it's some problem with position mapping.

**Comment by szymonkups** [comment]
It looks like this is a Chrome's problem with selection. Selection methods return proper anchor and focus nodes and offsets but selection is displayed incorrectly. I've created two fiddles showing this issue:
 * https://jsfiddle.net/szymonkups/nf0d44d9/
 * https://jsfiddle.net/szymonkups/eqez6gtb/

Both examples are almost identical, first example is probably the minimal test case.

**Comment by Reinmar** [comment]
I reported the issue: https://bugs.chromium.org/p/chromium/issues/detail?id=740085

**Comment by Reinmar** [comment]
I removed this from the next milestone. It doesn't make sense to hack it now because it's not a critical issue so let's wait and see if the Chrome's bug will be fixed.

**Comment by Reinmar** [comment]
DUP reported in https://github.com/ckeditor/ckeditor5/issues/932.

**Comment by Mgsy** [comment]
I can't reproduce any issue from this ticket, so I consider them fixed.
