### ISSUE TITLE
OT: RenameOperation transformation fails

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#995]
(Follow-up to: https://github.com/ckeditor/ckeditor5-engine/pull/977)

After https://github.com/ckeditor/ckeditor5-engine/pull/977 it is pretty easy to crash editor's OT using List feature. Probably there are some errors in `RenameOperation` or `RenameDelta` transformations.

**Comment by Reinmar** [comment]
What's the status of this?

**Comment by scofalik** [comment]
This got better after some fix for deltas transformation landed on master.
